//===- EarlyAnnotate.cpp - Annotator that runs early in the pipeline ------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Annotator that run early in the pipeline.
//
// This is intended to run early in the pipeline, typically after mem2reg (or
// the equivalent).
//
//===----------------------------------------------------------------------===//

#include "kitsune/Transforms/EarlyAnnotate.h"
#include "kitsune/Core/LoopAttrs.h"
#include "kitsune/Core/LoopUtils.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/IR/Intrinsics.h"

#define DEBUG_TYPE "kit-annotate-early"

using namespace llvm;

static void addMandatoryLoopAttrs(LoopInfo &li) {
  for (Loop *loop : li.getLoopsInPreorder())
    if (isTapirLoop(*loop))
      addMandatoryLLVMLoopAttrs(*loop);
}

static void annotateReductionLoops(LoopInfo &li) {
  auto isReductionLoop = [](const Loop &loop) -> bool {
    for (const BasicBlock *bb : loop.getBlocks())
      for (const Instruction &inst : *bb)
        if (const auto *call = dyn_cast<CallBase>(&inst))
          if (call->getIntrinsicID() == Intrinsic::kit_reduce_0)
            return true;
    return false;
  };

  for (Loop *loop : li.getLoopsInPreorder())
    if (isTapirLoop(*loop) && isReductionLoop(*loop))
      addReductionAttr(*loop);
}

static unsigned addLoopNestAnnotations(Loop &loop, unsigned depth) {
  assert(isTapirLoop(loop) && "Loop is a tapir loop");

  addPerfectLevelAttr(loop, depth);

  // Though we expect that any tapir loop whose parent is also a tapir loop is
  // perfectly nested relative to its parent, we should not assume that this is
  // guaranteed. Since it is difficult to reliably identify perfect nesting of
  // loops in LLVM IR, we do not attempt to handle the general case. Rather, we
  // only check for the cases that we can consistently identify.
  //
  //    forall (...) {           forall (...) {
  //      expr;                    forall (...)
  //      forall (...)               ...
  //        ...                    forall (...)
  //      expr;                      ...
  //    }                        }
  //
  // The loop nest on the left consists of imperfectly nested loops.
  // Nevertheless, the inner loop will be annotated with a perfect nesting
  // level of 2. On the other hand, neither of the inner loops in the nest on
  // the right will have any nesting level attributes added since they are,
  // obviously, not perfectly nested.
  //
  const std::vector<Loop *> &subLoops = loop.getSubLoops();
  if (subLoops.size() == 1) {
    Loop &subLoop = *subLoops[0];
    if (isTapirLoop(subLoop))
      return addLoopNestAnnotations(subLoop, depth + 1);
  }

  return depth;
}

static void annotateLoopNests(LoopInfo &li, ScalarEvolution &se) {
  // Since this runs early in the pipeline, it assumes that what it sees is
  // essentially exactly what was generated by the frontend (modulo having been
  // run through mem2reg, or an equivalent). Currently, we require Kitsune's
  // frontends to ensure that any non-top-level tapir loops are perfectly nested
  // with relative to their parents. We, therefore, just add the correct
  // annotations here. Obviously, it would be ideal if the frontend added these
  // annotations in the first place, but that gets ugly quickly, especially in
  // clang.
  for (Loop *loop : li.getLoopsInPreorder()) {
    if (isTopLevelTapirLoop(*loop)) {
      unsigned perfectDepth = addLoopNestAnnotations(*loop, 1);
      addPerfectDepthAttr(*loop, perfectDepth);
    }
  }
}

PreservedAnalyses EarlyAnnotatePass::run(Function &f,
                                         FunctionAnalysisManager &am) {
  // This pass is added to the function simplification pipeline. That pipeline
  // is run multiple times per function, but this pass should only be run once.
  if (hasEarlyAnnotatePassAttr(f))
    return PreservedAnalyses::all();

  LoopInfo &li = am.getResult<LoopAnalysis>(f);
  ScalarEvolution &se = am.getResult<ScalarEvolutionAnalysis>(f);

  addMandatoryLoopAttrs(li);
  annotateReductionLoops(li);
  annotateLoopNests(li, se);

  // At this time, the added annotations do not invalidate other analyses.
  // However, if we ever add any that do such as !tbaa (which affects alias
  // analysis), this must be changed.
  return PreservedAnalyses::all();
}
