//===- EmbLowerIntrinsicsEarly.cpp - Lower Kitsune-specific intrinsics ----===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lower Kitsune-specific intrinsics in an embedded module. Although most
// Kitsune-specific intrinsics are lowered by the backend, this is specifically
// intended to run as part of Kitsune's lowering pipeline in the middle-end.
//
// Currently, these only lower Kitsune-specific GPU thread-related intrinsics
// i.e. those that return the thread index, block index, block size etc. used in
// embedded modules generated by the hip tapir target.
//
// Kitsune's embedded bitcode optimization pipeline runs a standard set of
// optimization passes on the module late in the pipeline. For AMDGPU, that
// standard set includes the AMDGPUAttributor pass, which adds target-specific
// function attributes. This includes attributes such as
// `amdgpu-no-workgroup-id-y` that indicates that the function does not query
// workGroupId.y. There are corresponding attributes for the workitem,
// workGroupSize etc. The attributor pass looks for the correct target-specific
// intrinsic calls to determine whether these parameters are queried. If these
// attributes are added, but the function does query these parameters, an
// invalid value will be returned at runtime.
//
// It is, therefore, necessary to ensure that the correct target-specific
// intrinsics are introduced before the attributor pass is run. This is
// unfortunate because it means that the handling of Kitsune-specific
// intrinsics is split between codegen and IR passes. It is not clear if there
// is any other way around this.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Transforms/EmbLowerIntrinsicsEarly.h"
#include "kitsune/Core/ConstantUtils.h"
#include "kitsune/Core/ModuleUtils.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"

#define DEBUG_TYPE "emb-lower-intrinsics-early"

using namespace llvm;

static bool lowerKitIntrinsicsCuda(Module &embM) {
  // There are currently no Kitsune-specific intrinsics that must be lowered
  // early in modules generated by the cuda tapir target.
  return false;
}

static bool lowerKitIntrinsicsHip(Module &embM) {
  auto shouldReplace = [](Intrinsic::ID intr) -> bool {
    switch (intr) {
    case Intrinsic::kit_gpu_thread_id_x:
    case Intrinsic::kit_gpu_thread_id_y:
    case Intrinsic::kit_gpu_thread_id_z:
    case Intrinsic::kit_gpu_block_id_x:
    case Intrinsic::kit_gpu_block_id_y:
    case Intrinsic::kit_gpu_block_id_z:
    case Intrinsic::kit_gpu_block_size_x:
    case Intrinsic::kit_gpu_block_size_y:
    case Intrinsic::kit_gpu_block_size_z:
    case Intrinsic::kit_gpu_grid_size_x:
    case Intrinsic::kit_gpu_grid_size_y:
    case Intrinsic::kit_gpu_grid_size_z: return true;
    default: break;
    }
    return false;
  };

  // Replace the given call with another to the given intrinsic. The original
  // intrinsic is assumed to take no arguments other than the TTID. The
  // replacement intrinsic is assumed to not take any arguments at all.
  auto replaceSimple = [](CallBase *call, Intrinsic::ID newIntr) -> void {
    Module *m = call->getModule();
    Function *f = Intrinsic::getOrInsertDeclaration(m, newIntr);
    CallInst *newCall = CallInst::Create(f);
    ReplaceInstWithInst(call, newCall);
  };

  // Replace a call with another to a function with the given name. A
  // declaration for the function is added since it is assumed that the
  // definition will become available at link-time. The function takes a single
  // integer argument, which is also provided.
  auto replaceLibDevice = [](CallBase *call, StringRef fname,
                             unsigned dirxn) -> void {
    Module *m = call->getModule();
    LLVMContext &ctx = m->getContext();
    Type *i32 = Type::getInt32Ty(ctx);
    Type *i64 = Type::getInt64Ty(ctx);

    Type *type = call->getType();
    Function *libF = getOrInsertFunction(*m, fname, i64, i32);
    Constant *farg = toConstant(dirxn, ctx);

    CallInst *newCall = CallInst::Create(libF, {farg});
    if (libF->getReturnType() != type) {
      CastInst *newVal =
          CastInst::CreateIntegerCast(newCall, type, /*isSigned=*/false);
      ReplaceInstWithInst(call, newVal);
      newCall->insertBefore(newVal->getIterator());
    } else {
      ReplaceInstWithInst(call, newCall);
    }
  };

  // Replace the given call instruction.
  auto replace = [&](CallBase *call) -> void {
    // These functions are provide by ockl.bc - a bitcode file that is part of
    // the ROCm installation.
    constexpr StringRef getLocalSize = "__ockl_get_local_size";
    constexpr StringRef getGlobalSize = "__ockl_get_global_size";

    switch (call->getIntrinsicID()) {
    case Intrinsic::kit_gpu_thread_id_x:
      return replaceSimple(call, Intrinsic::amdgcn_workitem_id_x);
    case Intrinsic::kit_gpu_thread_id_y:
      return replaceSimple(call, Intrinsic::amdgcn_workitem_id_y);
    case Intrinsic::kit_gpu_thread_id_z:
      return replaceSimple(call, Intrinsic::amdgcn_workitem_id_z);
    case Intrinsic::kit_gpu_block_id_x:
      return replaceSimple(call, Intrinsic::amdgcn_workgroup_id_x);
    case Intrinsic::kit_gpu_block_id_y:
      return replaceSimple(call, Intrinsic::amdgcn_workgroup_id_y);
    case Intrinsic::kit_gpu_block_id_z:
      return replaceSimple(call, Intrinsic::amdgcn_workgroup_id_z);
    case Intrinsic::kit_gpu_block_size_x:
      return replaceLibDevice(call, getLocalSize, 0);
    case Intrinsic::kit_gpu_block_size_y:
      return replaceLibDevice(call, getLocalSize, 1);
    case Intrinsic::kit_gpu_block_size_z:
      return replaceLibDevice(call, getLocalSize, 2);
    case Intrinsic::kit_gpu_grid_size_x:
      return replaceLibDevice(call, getGlobalSize, 0);
    case Intrinsic::kit_gpu_grid_size_y:
      return replaceLibDevice(call, getGlobalSize, 1);
    case Intrinsic::kit_gpu_grid_size_z:
      return replaceLibDevice(call, getGlobalSize, 2);
    default: break;
    }
    llvm_unreachable("replaceKitIntrinsicsEarlyHip: Unexpected intrinsic");
  };

  SmallVector<CallBase *, 0> calls;
  for (Function &f : embM)
    for (inst_iterator i = inst_begin(f), e = inst_end(f); i != e; ++i)
      if (auto *call = dyn_cast<CallBase>(&*i))
        if (shouldReplace(call->getIntrinsicID()))
          calls.push_back(call);

  for (CallBase *call : calls)
    replace(call);

  return calls.size();
}

static bool lowerIntrinsics(TTID tt, Module &embM) {
  switch (tt) {
  case TTID::Cuda: return lowerKitIntrinsicsCuda(embM);
  case TTID::Hip: return lowerKitIntrinsicsHip(embM);
  default: break;
  }
  llvm_unreachable("lowerKitIntrinsics: TTID not handled");
}

bool EmbLowerIntrinsicsEarlyPass::run(TTID tt, Module &devM, Module &hostM,
                                      ModuleAnalysisManager &hostMAM) {
  return lowerIntrinsics(tt, devM);
}
