//===- EmbLowerKitIntrinsicsEarly.cpp - Lower Kitsune-specific intrinsics -===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lower Kitsune-specific intrinsics in an embedded module. Although most
// Kitsune-specific intrinsics are lowered by the backend, this is specifically
// intended to run as part of Kitsune's lowering pipeline in the middle-end.
//
// More details on why this is necessary can be found in the code comments.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Transforms/EmbLowerKitIntrinsicsEarly.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"

#define DEBUG_TYPE "emb-lower-intrinsics-early"

using namespace llvm;

namespace {

// Lower Kitsune-specific GPU thread-related intrinsics i.e. those that return
// the thread index, block index, block size etc. used in embedded modules
// generated by the hip tapir target.
//
// Kitsune's embedded bitcode optimization pipeline runs a standard set of
// optimization passes on the module late in the pipeline. For AMDGPU, that
// standard set includes the AMDGPUAttributor pass, which adds target-specific
// function attributes. This includes attributes such as
// `amdgpu-no-workgroup-id-y` that indicates that the function does not query
// workGroupId.y. There are corresponding attributes for the workitem,
// workGroupSize etc. The attributor pass looks for the correct target-specific
// intrinsic calls to determine whether these parameters are queried. If these
// attributes are added, but the function does query these parameters, an
// invalid value will be returned at runtime.
//
// It is, therefore, necessary to ensure that the correct target-specific
// intrinsics are introduced before the attributor pass is run. This is
// unfortunate because it means that the handling of Kitsune-specific
// intrinsics is split between codegen and IR passes. It is not clear if there
// is any other way around this.
class ReplaceGPUThreadIntrinsicsHip {
protected:
  using LibDeviceReplInfo = std::tuple<StringRef, unsigned>;
  using LibDeviceRepls = SmallDenseMap<CallBase *, LibDeviceReplInfo>;
  using SimpleRepls = SmallDenseMap<CallBase *, Intrinsic::ID>;

protected:
  // Simple replacements are when calls to a Kitsune-specific intrinsic can be
  // replaced with a call to an equivalent target-specific intrinsic. The
  // target-specific intrinsics take the same number and types of arguments as
  // the original, but may return a different type.
  SimpleRepls simpleRepls;

  // LibDevice replacements are when calls to a Kitsune-specific intrinsic must
  // be replaced with a call to a function from a vendor-provided
  // device-specific bitcode file. In this case, the signature of the libdevice
  // function may be different from that of the original Kitsune-specific
  // intrinsic.
  LibDeviceRepls libDeviceRepls;

protected:
  bool replaceAllSimple(Module &embM) {
    for (const auto &p : simpleRepls) {
      CallBase *call = p.first;
      Intrinsic::ID newCallee = p.second;

      IRBuilder<> builder(call);
      CallInst *newCall = builder.CreateIntrinsic(newCallee, {});

      newCall->takeName(call);
      call->replaceAllUsesWith(newCall);
      call->eraseFromParent();
    }

    return simpleRepls.size();
  }

  bool replaceAllLibDevice(Module &embM) {
    LLVMContext &ctx = embM.getContext();
    Type *i32 = Type::getInt32Ty(ctx);
    Type *i64 = Type::getInt64Ty(ctx);

    for (const auto &p : libDeviceRepls) {
      CallBase *call = p.first;
      StringRef libf = std::get<StringRef>(p.second);
      unsigned dirxn = std::get<unsigned>(p.second);

      StringRef name = call->getName();
      Type *type = call->getType();
      FunctionCallee newCallee = embM.getOrInsertFunction(libf, i64, i32);
      Constant *farg = ConstantInt::get(i32, dirxn, /*isSigned=*/false);

      IRBuilder<> builder(call);
      Value *newCall = builder.CreateCall(newCallee, {farg}, name + ".64");
      Value *newVal = builder.CreateIntCast(newCall, type, /*isSigned=*/false);

      newVal->takeName(call);
      call->replaceAllUsesWith(newVal);
      call->eraseFromParent();
    }

    return libDeviceRepls.size();
  }

  void addToSimpleRepls(CallBase *call, Intrinsic::ID id) {
    simpleRepls.insert({call, id});
  }

  void addToLibDeviceRepls(CallBase *call, LibDeviceReplInfo info) {
    libDeviceRepls.insert({call, info});
  }

  void maybeAddToRepls(CallBase *call) {
    // These functions are provide by ockl.bc - a bitcode file that is part of
    // the ROCm installation.
    constexpr StringRef getLocalSize = "__ockl_get_local_size";
    constexpr StringRef getGlobalSize = "__ockl_get_global_size";

    switch (call->getIntrinsicID()) {
    case Intrinsic::kit_gpu_thread_id_x:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workitem_id_x);
    case Intrinsic::kit_gpu_thread_id_y:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workitem_id_y);
    case Intrinsic::kit_gpu_thread_id_z:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workitem_id_z);
    case Intrinsic::kit_gpu_block_id_x:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workgroup_id_x);
    case Intrinsic::kit_gpu_block_id_y:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workgroup_id_y);
    case Intrinsic::kit_gpu_block_id_z:
      return addToSimpleRepls(call, Intrinsic::amdgcn_workgroup_id_z);
    case Intrinsic::kit_gpu_block_size_x:
      return addToLibDeviceRepls(call, {getLocalSize, 0});
    case Intrinsic::kit_gpu_block_size_y:
      return addToLibDeviceRepls(call, {getLocalSize, 1});
    case Intrinsic::kit_gpu_block_size_z:
      return addToLibDeviceRepls(call, {getLocalSize, 2});
    case Intrinsic::kit_gpu_grid_size_x:
      return addToLibDeviceRepls(call, {getGlobalSize, 0});
    case Intrinsic::kit_gpu_grid_size_y:
      return addToLibDeviceRepls(call, {getGlobalSize, 1});
    case Intrinsic::kit_gpu_grid_size_z:
      return addToLibDeviceRepls(call, {getGlobalSize, 2});
    }
  }

public:
  bool run(Module &embM) {
    bool changed = false;

    for (Function &f : embM)
      for (inst_iterator i = inst_begin(f), e = inst_end(f); i != e; ++i)
        if (auto *call = dyn_cast<CallBase>(&*i))
          maybeAddToRepls(call);
    changed |= replaceAllSimple(embM);
    changed |= replaceAllLibDevice(embM);

    return changed;
  }
};

} // namespace

static bool lowerKitIntrinsicsCuda(Module &embM) {
  // There are currently no Kitsune-specific intrinsics that must be lowered
  // early in modules generated by the cuda tapir target.
  return false;
}

static bool lowerKitIntrinsicsHip(Module &embM) {
  bool changed = false;

  changed |= ReplaceGPUThreadIntrinsicsHip().run(embM);

  return changed;
}

static bool lowerKitIntrinsics(TTID tt, Module &embM) {
  switch (tt) {
  case TTID::Cuda: return lowerKitIntrinsicsCuda(embM);
  case TTID::Hip: return lowerKitIntrinsicsHip(embM);
  default: break;
  }
  llvm_unreachable("lowerKitIntrinsics: TTID not handled");
}

bool EmbLowerKitIntrinsicsEarlyPass::run(TTID tt, Module &devM, Module &hostM,
                                         ModuleAnalysisManager &hostMAM) {
  return lowerKitIntrinsics(tt, devM);
}
