//===- EmbPrepareCuda.cpp - Prepare an embedded cuda module ---------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Prepare an embedded module, generated by the cuda tapir target for (eventual)
// code generation.
//
//===----------------------------------------------------------------------===//

#include "EmbPrepareImpl.h"
#include "kitsune/Core/AddrSpaceUtils.h"
#include "kitsune/Core/FuncAttrs.h"
#include "kitsune/Core/TTOptions.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"

using namespace llvm;

namespace {

class EmbPrepareCuda {
private:
  const TTOptions &tto;
  const detail::EmbPrepareOptions &prepOpts;

private:
  /// Fix the attributes on the "non-kernel" functions. The attributes on the
  /// kernel function will have been set by the tapir targets.
  bool fixDeviceFuncAttrs(Module &devM) {
    bool changed = false;
    for (Function &f : devM.functions()) {
      if (hasDeviceAttr(f)) {
        f.removeFnAttr("target-cpu");
        f.removeFnAttr("target-features");
        f.removeFnAttr("tune-cpu");

        f.addFnAttr("target-cpu", tto.getCudaArch());
        f.addFnAttr(
            "target-features",
            join_items(",", tto.getCudaTargetFeatures(), tto.getCudaArch()));

        bool hasNoInline = f.hasFnAttribute(Attribute::NoInline);
        if (prepOpts.inlineAllForce) {
          f.removeFnAttr(Attribute::NoInline);
          f.addFnAttr(Attribute::AlwaysInline);
        } else if (prepOpts.inlineAll and (not hasNoInline)) {
          f.addFnAttr(Attribute::AlwaysInline);
        }

        changed |= true;
      }
    }
    return changed;
  }

public:
  EmbPrepareCuda(const TTOptions &tto,
                 const detail::EmbPrepareOptions &prepOpts)
      : tto(tto), prepOpts(prepOpts) {}

  bool run(Module &devM) {
    bool changed = false;

    changed |= fixDeviceFuncAttrs(devM);
    changed |= stripKitsuneAddrSpaces(devM);

    return changed;
  }
};

} // namespace

bool llvm::detail::embPrepareCuda(Module &m, const TTOptions &tto,
                                  const detail::EmbPrepareOptions &prepOpts) {
  return EmbPrepareCuda(tto, prepOpts).run(m);
}
