//===- EmbPrepareImpl.h - Private header for EmbPreparePass ----*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Private header shared by the embedded module preparation implementations.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_EMB_PREPARE_IMPL_H
#define LLVM_EMB_PREPARE_IMPL_H

#define DEBUG_TYPE "emb-prepare"

namespace llvm {

class Module;
class TapirTargetOptions;

namespace detail {

/// Options to control the preparation of embedded modules.
struct EmbPrepareOptions {
  /// Inline all device functions in the kernel module, unless they have the
  /// 'noinline' attribute
  unsigned inlineAll : 1;

  /// Inline all device functions in the kernel module, including those that
  /// have the 'noinline' attribute
  unsigned inlineAllForce : 1;
};

/// Prepare an embedded module, generated by the cuda tapir target, for
/// (eventual) code generation. Return true if the module was changed, false
/// otherwise.
bool embPrepareCuda(Module &embM, const TapirTargetOptions &tto,
                    const EmbPrepareOptions &prepareOpts);

/// Prepare an embedded module, generated by the hip tapir target, for
/// (eventual) code generation. Return true if the module was changed, false
/// otherwise.
bool embPrepareHip(Module &embM, const TapirTargetOptions &tto,
                   const EmbPrepareOptions &prepareOpts);

} // namespace detail

} // namespace llvm

#endif // LLVM_EMB_PREPARE_IMPL_H
