//===- EmbPrepareCuda.cpp - Prepare an embedded cuda module ---------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Prepare an embedded module, generated by the cuda tapir target for (eventual)
// code generation.
//
//===----------------------------------------------------------------------===//

#include "EmbPrepareImpl.h"
#include "kitsune/Core/AddrSpaceUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"

using namespace llvm;

namespace {

class EmbPrepareCuda {
private:
  const TapirTargetOptions &tto;
  const detail::EmbPrepareOptions &prepOpts;

private:
  /// Fix attributes that must be handled the same way for both kernel and
  /// device functions.
  void fixCommonFuncAttrs(Function &f) {
    // The target attributes will have been set assuming that the code will
    // be run on the host.
    f.removeFnAttr("target-cpu");
    f.removeFnAttr("target-features");
    f.removeFnAttr("tune-cpu");

    // We do not support exceptions on GPU's.
    f.removeFnAttr("personality");
    f.removeFnAttr(Attribute::UWTable);

    // Add new target-specific attributes.
    f.addFnAttr("target-cpu", tto.getCudaArch());
    f.addFnAttr("target-features", join_items(",", tto.getCudaTargetFeatures(),
                                              tto.getCudaArch()));

    // Add other attributes that are relevant for GPU code.
    f.addFnAttr(Attribute::NoUnwind);
  }

  /// Fix the attribute on "kernel" functions. Some attributes will have been
  /// set by the tapir target. Ideally, those should be moved here as well.
  /// There is not a lot to be gained by doing this early.
  bool fixKernelFuncAttrs(Module &devM) {
    bool changed = false;
    for (Function &f : devM.functions()) {
      if (f.hasFnAttribute(Attribute::KitKernel)) {
        fixCommonFuncAttrs(f);

        changed |= true;
      }
    }
    return changed;
  }

  /// Fix the attributes on the "non-kernel" functions. The attributes on the
  /// kernel function will have been set by the tapir targets.
  bool fixDeviceFuncAttrs(Module &devM) {
    bool changed = false;
    for (Function &f : devM.functions()) {
      if (f.hasFnAttribute(Attribute::KitDevice)) {
        fixCommonFuncAttrs(f);

        bool hasNoInline = f.hasFnAttribute(Attribute::NoInline);
        if (prepOpts.inlineAllForce) {
          f.removeFnAttr(Attribute::NoInline);
          f.addFnAttr(Attribute::AlwaysInline);
        } else if (prepOpts.inlineAll and (not hasNoInline)) {
          f.addFnAttr(Attribute::AlwaysInline);
        }

        changed |= true;
      }
    }
    return changed;
  }

public:
  EmbPrepareCuda(const TapirTargetOptions &tto,
                 const detail::EmbPrepareOptions &prepOpts)
      : tto(tto), prepOpts(prepOpts) {}

  bool run(Module &devM) {
    bool changed = false;

    changed |= fixKernelFuncAttrs(devM);
    changed |= fixDeviceFuncAttrs(devM);
    changed |= stripKitsuneAddrSpaces(devM);

    return changed;
  }
};

} // namespace

bool llvm::detail::embPrepareCuda(Module &m, const TapirTargetOptions &tto,
                                  const detail::EmbPrepareOptions &prepOpts) {
  return EmbPrepareCuda(tto, prepOpts).run(m);
}
