//===- LowerReduceIntrinsicsCore.h - Lower reduce intrinsics ----*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Lower Kitsune's core reduction intrinsics. This is a private header
// containing utilities that are used to lower the core intrinsics used in both
// host and embedded bitcode modules.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_LIB_TRANSFORMS_LOWER_REDUCE_INTRINSICS_CORE_H
#define KITSUNE_LIB_TRANSFORMS_LOWER_REDUCE_INTRINSICS_CORE_H

namespace llvm {

class Module;

namespace detail {

/// Lower the core Kitsune reduce intrinsics in the given module. The core
/// intrinsics are those that are generated by the frontend and perform the
/// actual reduction. It does not include any intrinsics that are specific to
/// performing optimized parallel reductions on either CPU or GPU. Returns true
/// if at least one intrinsic was lowered, false otherwise.
///
/// kit.reduce.0 is reduced by simply calling the provided reducer function.
/// For example, the call below
///
///   call void kit.reduce.0(i32 1, ptr %r, i32 4, i32 %v, i32 1, ptr @f, i8 %e)
///
/// would become
///
///   call void @f(ptr %r, i32 %v, i8 %e)
///
/// Note that here, %e is part of the optional arguments that the reducer
/// function might accept.
///
bool lowerReduceIntrinsicsCore(Module &m);

} // namespace detail

} // namespace llvm

#endif // KITSUNE_LIB_TRANSFORMS_LOWER_REDUCE_INTRINSICS_CORE_H
