//===- kit-mdc.cpp - Kitsune tool to work with embedded device code -------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Query the embedded device code in archives and object files.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Core/CommandLineOptions.h"
#include "kitsune/Core/Tapir.h"
#include "kitsune/Object/EmbDeviceCodeParser.h"
#include "kitsune/Support/Error.h"
#include "kitsune/Support/TTUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;
using namespace llvm::object;

static cl::OptionCategory catKitMDC("Kitsune Options (kit-mdc)");

static cl::opt<std::string> clOutDir(
    "J", cl::init("."),
    cl::desc("The directory into which to copy the embedded device code"),
    cl::value_desc("dir"), cl::cat(catKitMDC));

static cl::opt<std::string>
    clOutFile("o", cl::init(""),
              cl::desc("The file into which to copy the embedded device code"),
              cl::value_desc("file"), cl::cat(catKitMDC));

static cl::opt<std::string> clInFile(cl::Positional, cl::Required,
                                     cl::desc("<file>"), cl::cat(catKitMDC));

static void setupCommandLineOptions() {
  cl::HideUnrelatedOptions({&catKitMDC, &catKitCommon});
  clSetOptionDescription(
      "tapir",
      "Only extract the embedded device code generated by this tapir target");
}

// Construct the output file name for an embedded device code object. The name
// will be based on the input file name and the tapir target that generated
// the embedded device code.
static std::string getOutputFile(const EmbDeviceCode &devCode) {
  SmallString<64> outFile;
  if (not clOutFile.empty())
    outFile = clOutFile;
  else
    sys::path::append(outFile, clOutDir, devCode.getName());

  std::error_code ec = sys::fs::make_absolute(outFile);
  if (ec)
    report_error(sjoin("Error getting absolute path: ", ec));
  return std::string(outFile);
}

static void write(const EmbDeviceCode &devCode) {
  std::error_code ec;
  raw_fd_ostream fs(getOutputFile(devCode), ec);
  if (ec)
    report_error(ec);
  fs << devCode.getCode();
  fs.close();
}

// The embedded device codes have been parsed. Write these out depending on the
// command line options.
static int processDeviceCodes(const Binary &bin, std::optional<TTID> tt) {
  Expected<EmbDeviceCodes> devCodesOrErr = EmbDeviceCodes::parse(bin);
  if (not devCodesOrErr)
    report_error(sjoin(devCodesOrErr.takeError()));
  const EmbDeviceCodes &devCodes = *devCodesOrErr;

  SmallVector<EmbDeviceCode, 1> codes;
  for (const EmbDeviceCode &devCode : devCodes)
    if (not tt or *tt == devCode.getTTID())
      codes.push_back(devCode);

  if (codes.empty()) {
    report_warning("no embedded device code found");
  } else if (codes.size() == 1) {
    write(codes[0]);
  } else if (not clOutFile.empty()) {
    // If the input file contains more than one embedded device code objects and
    // all of them must be extracted, they cannot be extracted into a single
    // file.
    report_error(sjoin("cannot write ", codes.size(),
                       " device code files to a single output file"));
  } else {
    for (const EmbDeviceCode &devCode : codes)
      write(devCode);
  }
  return 0;
}

// Process a static archive. Always returns 0.
static int processArchive(const MemoryBufferRef &memBuf,
                          std::optional<TTID> tt) {
  Expected<std::unique_ptr<Archive>> archiveOrErr = Archive::create(memBuf);
  if (not archiveOrErr)
    report_error(sjoin(archiveOrErr.takeError()));
  return processDeviceCodes(**archiveOrErr, tt);
}

// Process an object file. Always returns 0.
static int processObjectFile(const MemoryBufferRef &memBuf,
                             const std::optional<TTID> &tt) {
  Expected<std::unique_ptr<ObjectFile>> objFileOrErr =
      ObjectFile::createObjectFile(memBuf);
  if (not objFileOrErr)
    report_error(sjoin(objFileOrErr.takeError()));
  return processDeviceCodes(**objFileOrErr, tt);
}

int main(int argc, char *argv[]) {
  InitLLVM X(argc, argv);

  setupCommandLineOptions();
  cl::ParseCommandLineOptions(
      argc, argv,
      "Extract the embedded device code in archives and object files. The "
      "input file will not be modified");

  // If this is not empty, only extract the embedded device code generated by
  // the this tapir target. Otherwise, extract all embedded device code that is
  // found.
  std::optional<TTID> tt = std::nullopt;
  if (clTapir.getNumOccurrences())
    tt = clTapir;
  if (tt and not ttUsesEmbBC(*tt))
    report_error(sjoin(
        "'", *tt, "' tapir target does not generate embedded device code"));

  ErrorOr<std::unique_ptr<MemoryBuffer>> memBufOrErr =
      MemoryBuffer::getFile(clInFile);
  if (not memBufOrErr)
    report_error(sjoin(memBufOrErr.getError()));

  // The input file may be an archive or an object file.
  const MemoryBuffer &memBuf = **memBufOrErr;
  file_magic magic = identify_magic(memBuf.getBuffer());
  switch (magic) {
  case file_magic::archive:
    return processArchive(memBuf, tt);
  case file_magic::elf:
  case file_magic::elf_core:
  case file_magic::elf_executable:
  case file_magic::elf_relocatable:
  case file_magic::elf_shared_object:
    return processObjectFile(memBuf, tt);
  case file_magic::macho_object:
  case file_magic::macho_executable:
  case file_magic::macho_dynamically_linked_shared_lib:
  case file_magic::coff_object:
  case file_magic::coff_import_library:
  case file_magic::pecoff_executable:
    report_internal_error(sjoin(
        "NOT YET IMPLEMENTED: support for object file format '", magic, "'"));
    break;
  default:
    report_error(sjoin("unsupported file format '", magic, "'"));
    break;
  }

  return 0;
}
