//==- CodeGenFatBinariesCuda.cpp - Generate fat binaries for NVIDIA GPUs ---==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the cuda tapir target into fat
// binaries.
//
//===----------------------------------------------------------------------===//

#include "CodeGenFatBinariesImpl.h"
#include "kitsune/Config/config.h"
#include "kitsune/Core/EmbUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "kitsune/Core/TargetUtils.h"
#include "kitsune/Support/OptznLevelUtils.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"

using namespace llvm;

// The default mode of the transformation is to embed a single fat binary image
// for the selected target architecture. With this flag set, the PTX form of the
// code will also be embedded into the fat binary.
// FIXME: This is currently not used.
static cl::opt<bool> clEmbedPTXInFatbinaries(
    "cgfb-embed-ptx", cl::init(false), cl::Hidden,
    cl::desc("Embed PTX code in the fat binaries generated for the cuda tapir "
             "target (NOT YET IMPLEMENTED)"));

// Override the optimization level used by ptxas when generating GPU code. If
// this is not explicitly set, it will use the optimization level set in the
// tapir target options, which is usually whatever was passed to the frontend.
static cl::opt<int> clPtxasOptLevel(
    "cgfb-ptxas-opt-level", cl::init(-1), cl::Hidden,
    cl::desc("Set the optimization level for ptxas. Must be 0, 1, 2 or 3"));

namespace {

/// Helper class to generate code for NVIDIA GPU's from embedded bitcode.
class CodeGenFatBinaryCuda {
private:
  const TapirTargetOptions &tto;

private:
  std::unique_ptr<ToolOutputFile> generatePTX(Module &km) {
    LLVM_DEBUG(dbgs() << "\t- generating ptx...\n");

    // Take the intermediate form code in the kernel module and generate a PTX
    // file. The PTX file will be named the same as the original input source
    // module (M) with the extension changed to PTX.
    SmallString<1024> ptxFilename;
    std::string model =
        llvm::join_items("-", "kitcu", "%%%%%%%%", km.getName());
    sys::fs::createUniquePath(model.c_str(), ptxFilename, true);
    sys::path::replace_extension(ptxFilename, ".ptx");
    LLVM_DEBUG(dbgs() << "\t- ptx file: '" << ptxFilename << "'.\n");

    std::error_code ec;
    auto ptxFile = std::make_unique<ToolOutputFile>(
        ptxFilename, ec, sys::fs::OpenFlags::OF_None);
    if (ec)
      report_fatal_error(Twine("Could not create ptx file: ") + ec.message());

    // The build system should have ensured that the NVPTX target is available.
    TargetMachine *tm = createTargetMachine(TTID::Cuda, tto);
    assert(tm && "Could not create NVPTX target machine");

    // Setup the passes and request that the output goes to the specified PTX
    // file.
    legacy::PassManager passMgr;
    if (tm->addPassesToEmitFile(passMgr, ptxFile->os(),
                                /*DwoOut=*/nullptr,
                                CodeGenFileType::AssemblyFile,
                                /*DisableVerify=*/false))
      report_fatal_error(Twine("PTX generation failed: ") + ec.message());
    passMgr.run(km);

    LLVM_DEBUG(dbgs() << "PTX generation complete.\n\n");
    return ptxFile;
  }

  std::unique_ptr<ToolOutputFile> assemblePTX(ToolOutputFile &ptxFile) {
    LLVM_DEBUG(dbgs() << "\t- generating asm...\n");

    std::string ptxFilename = ptxFile.getFilename().str();
    SmallString<255> asmFilename(ptxFilename);
    sys::path::replace_extension(asmFilename, ".s");
    LLVM_DEBUG(dbgs() << "\t- asm file: '" << ptxFilename << "'.\n");

    std::error_code ec;
    auto asmFile = std::make_unique<ToolOutputFile>(
        asmFilename, ec, sys::fs::OpenFlags::OF_None);
    if (ec)
      report_fatal_error(Twine("Could not create asm file: ") + ec.message());

    // Build the command line for ptxas.
    std::vector<StringRef> args;

    StringRef ptxas = KITSUNE_CUDA_PTXAS;
    args.push_back(ptxas);

    // TODO: Do we need/want to add support for generating relocatable code?

    // The gpu architecture (e.g., sm_86)
    args.push_back("--gpu-name");
    args.push_back(tto.getCudaArch());

    // Warn if we spill registers and provide feedback on kernel stats.
    args.push_back("--warn-on-spills");

    if (tto.getTapirVerbose())
      args.push_back("--verbose");

    // If the ptxas optimization level has not been explicitly overridden, use
    // the optimization level set by the frontend.
    int ptxasOptLevel = clPtxasOptLevel;
    if (ptxasOptLevel == -1)
      ptxasOptLevel = getSpeedupLevel(tto.getOptznLevel());

    std::string optLevel = std::to_string(ptxasOptLevel);
    args.push_back("--opt-level");
    args.push_back(optLevel);

    std::string scodeFilename = asmFile->getFilename().str();
    args.push_back("--output-file");
    args.push_back(scodeFilename);

    args.push_back(ptxFilename);

    LLVM_DEBUG({
      dbgs() << "\t- ptxas command line:\n";
      dbgs() << "\t\t" << ptxas << "\n";
      unsigned i = 1;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });

    std::string errMsg;
    if (sys::ExecuteAndWait(ptxas, args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*SecondsToWait=*/0, /* 0 => unlimited */
                            /*MemoryLimit=*/0,   /* 0 => unlimited */
                            &errMsg))
      report_fatal_error(Twine("'ptxas' failed: ") + errMsg);

    LLVM_DEBUG(dbgs() << "asm file generation complete.\n\n");
    return asmFile;
  }

  std::unique_ptr<ToolOutputFile> createFatBinary(ToolOutputFile &asmFile) {
    LLVM_DEBUG(dbgs() << "\t- generating fatbin...\n");

    SmallString<255> fatbinFilename(asmFile.getFilename());
    sys::path::replace_extension(fatbinFilename, ".cufatbin");
    LLVM_DEBUG(dbgs() << "\t- fatbin file '" << fatbinFilename << "'.\n");

    std::error_code ec;
    auto fatbinFile = std::make_unique<ToolOutputFile>(
        fatbinFilename, ec, sys::fs::OpenFlags::OF_None);

    StringRef fatbin = KITSUNE_CUDA_FATBINARY;
    std::vector<StringRef> args;
    args.push_back(fatbin);
    args.push_back("--64");
    args.push_back("--create");
    args.push_back(fatbinFilename);

    std::string imgArgs =
        llvm::join_items("", "--image=profile=", tto.getCudaArch(),
                         ",file=", asmFile.getFilename());
    args.push_back(imgArgs);

    // FIXME: This code looks like it is broken.
    // std::list<std::string> PTXFilesArgList;
    // if (EmbedPTXInFatbinaries) {
    //   StringRef varch = ttOpts.getCudaVirtArch();
    //   if (varch == "unknown")
    //     report_fatal_error("cuabi: no virtual target for given gpuarch '" +
    //                        TTO.getCudaArch() + "'!");

    //   std::string PTXFixedArgStr =
    //       ("--image=profile=" + VArchStr + ",file=").str();
    //   for (auto &PTXFile : ModulePTXFileList) {
    //     std::string arg = PTXFixedArgStr + PTXFile;
    //     std::list<std::string>::const_iterator it;
    //     it = PTXFilesArgList.emplace(PTXFilesArgList.end(), std::move(arg));
    //     args.push_back(it->c_str());
    //   }
    // }

    LLVM_DEBUG({
      dbgs() << "\tfatbinary command line:\n";
      unsigned i = 0;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });

    std::string errMsg;
    if (sys::ExecuteAndWait(/*Program=*/fatbin,
                            /*Args=*/args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*(0 => unlimited) SecondsToWait=*/0,
                            /*(0 => unlimited) MemoryLimit=*/0,
                            /*ErrMsg=*/&errMsg))
      // TODO: Need to check what sort of actual state 'fatbinary' returns to
      // the environment -- currently assuming it matches standard practices
      report_fatal_error(Twine("fatbinary failed: ") + errMsg);

    return fatbinFile;
  }

public:
  CodeGenFatBinaryCuda(const TapirTargetOptions &tto) : tto(tto) {}

  bool run(GlobalVariable &gfb, const GlobalVariable &gbc, bool keepFiles) {
    std::unique_ptr<Module> km = parseEmbBCGlobal(gbc);

    std::unique_ptr<ToolOutputFile> ptxFile = generatePTX(*km);
    std::unique_ptr<ToolOutputFile> asmFile = assemblePTX(*ptxFile);
    std::unique_ptr<ToolOutputFile> fatbinFile = createFatBinary(*asmFile);
    detail::embedFatBinary(*fatbinFile, gfb);

    if (keepFiles) {
      ptxFile->keep();
      asmFile->keep();
      fatbinFile->keep();
    }
    return true;
  }
};

} // namespace

bool llvm::detail::cgFatBinaryCuda(GlobalVariable &gfb,
                                   const GlobalVariable &gbc,
                                   const TapirTargetOptions &tto,
                                   bool keepFiles) {
  return CodeGenFatBinaryCuda(tto).run(gfb, gbc, keepFiles);
}
