//==- CodeGenFatBinaries.cpp - Generate fat binaries from embedded bitcode -==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into fat binaries.
//
//===----------------------------------------------------------------------===//

#include "kitsune/CodeGen/CodeGenFatBinaries.h"
#include "CGFBImpl.h"
#include "kitsune/Analysis/TapirTargetAnalysis.h"
#include "kitsune/Core/EmbUtils.h"
#include "kitsune/Core/GlobalVariableUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ToolOutputFile.h"

using namespace llvm;

static cl::opt<bool>
    clPrintCommandLines("cgfb-###", cl::init(false), cl::Hidden,
                        cl::desc("Print command lines of external tools that "
                                 "are called during fat binary generation"));

static cl::opt<bool>
    clKeepFiles("cgfb-keep-files", cl::init(false), cl::Hidden,
                cl::desc("Do not delete intermediate files created during "
                         "generation of the fat binaries"));

// FIXME: Check if this is something that could be enabled and do so, if
// possible.
//
// The default mode of the transformation is to embed a single fat binary image
// for the selected target architecture. With this flag set, the PTX form of the
// code will also be embedded into the fat binary.
// static cl::opt<bool> clEmbedPTXInFatbinaries(
//     "cgfb-embed-ptx", cl::init(false), cl::Hidden,
//     cl::desc("Embed PTX code in the fat binaries generated for the cuda tapir
//     "
//              "target (NOT YET IMPLEMENTED)"));

// Override the optimization level used by ptxas when generating GPU code. If
// this is not explicitly set, it will use the optimization level set in the
// tapir target options, which is usually whatever was passed to the frontend.
static cl::opt<OptznLevel> clPtxasOptLevel(
    cl::init(OptznLevel::O3), cl::Hidden,
    cl::values(clEnumValN(OptznLevel::O0, "cgfb-ptxas-O0", "Pass O0 to ptxas"),
               clEnumValN(OptznLevel::O1, "cgfb-ptxas-O1", "Pass O1 to ptxas"),
               clEnumValN(OptznLevel::O2, "cgfb-ptxas-O2", "Pass O2 to ptxas"),
               clEnumValN(OptznLevel::O3, "cgfb-ptxas-O3", "Pass O3 to ptxas")),
    cl::desc("Override the optimization level passed to ptxas"));

namespace {

/// Implementation class to compile the embedded bitcode to fat binaries.
class CodeGenFatBinaries {
private:
  const TapirTargetOptions &tto;

public:
  CodeGenFatBinaries(const TapirTargetOptions &tto) : tto(tto) {}

  bool run(Module &m) {
    bool changed = false;

    detail::CGFBOptions cgfbOpts;
    cgfbOpts.keepFiles = clKeepFiles;
    cgfbOpts.printCommandLines = clPrintCommandLines;
    cgfbOpts.ptxasOptLevel = tto.getOptznLevel();
    if (clPtxasOptLevel.getNumOccurrences())
      cgfbOpts.ptxasOptLevel = clPtxasOptLevel;

    GlobalVariable *bcCuda = getEmbBCGlobal(TTID::Cuda, m);
    GlobalVariable *fbCuda = getEmbFBGlobal(TTID::Cuda, m);
    if (bcCuda and fbCuda) {
      detail::cgfbCuda(*fbCuda, *bcCuda, tto, cgfbOpts);
      bcCuda->eraseFromParent();
      changed |= true;
    }

    GlobalVariable *bcHip = getEmbBCGlobal(TTID::Hip, m);
    GlobalVariable *fbHip = getEmbFBGlobal(TTID::Hip, m);
    if (bcHip and fbHip) {
      detail::cgfbHip(*fbHip, *bcHip, tto, cgfbOpts);
      bcHip->eraseFromParent();
      changed |= true;
    }

    return changed;
  }
};

} // namespace

void llvm::detail::embedFatBinary(ToolOutputFile &fatbinFile,
                                  GlobalVariable &g) {
  ErrorOr<std::unique_ptr<MemoryBuffer>> bufOrErr =
      MemoryBuffer::getFile(fatbinFile.getFilename());
  if (std::error_code ec = bufOrErr.getError()) {
    report_fatal_error(StringRef(llvm::join_items(
        " ", "failed to load fat binary image:", ec.message())));
  }

  std::unique_ptr<MemoryBuffer> fb = std::move(bufOrErr.get());
  resetEmbFBGlobal(*fb, g);
}

/// Legacy pass to compile the embedded bitcode to fat binaries.
class CodeGenFatBinariesLegacyPass : public ModulePass {
public:
  CodeGenFatBinariesLegacyPass() : ModulePass(ID) {
    initializeCodeGenFatBinariesLegacyPassPass(
        *PassRegistry::getPassRegistry());
  }

  StringRef getPassName() const override {
    return "Generate Kitsune fat binaries";
  }

  void getAnalysisUsage(AnalysisUsage &au) const override {
    au.addRequired<TapirTargetAnalysisWrapperPass>();
  }

  bool runOnModule(Module &m) override;

public:
  static char ID;
};

char CodeGenFatBinariesLegacyPass::ID = 0;
INITIALIZE_PASS_BEGIN(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                      "Compile Kitsune fat binaries", false, false)
INITIALIZE_PASS_DEPENDENCY(TapirTargetAnalysisWrapperPass)
INITIALIZE_PASS_END(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                    "Compile Kitsune fat binaries", false, false)

ModulePass *llvm::createCodeGenFatBinariesLegacyPass() {
  return new CodeGenFatBinariesLegacyPass();
}

bool CodeGenFatBinariesLegacyPass::runOnModule(Module &m) {
  TapirTargetInfo tgi =
      getAnalysis<TapirTargetAnalysisWrapperPass>().getResult();
  if (not tgi.hasID())
    return false;

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  bool changed = CodeGenFatBinaries(ttOpts).run(m);

  return changed;
}

PreservedAnalyses CodeGenFatBinariesPass::run(Module &m,
                                              ModuleAnalysisManager &mam) {
  // If a primary tapir target ID has not been set, then tapir lowering was not
  // enabled and there is nothing to be done.
  const TapirTargetInfo &tgi = mam.getResult<TapirTargetAnalysis>(m);
  if (not tgi.hasID())
    return PreservedAnalyses::all();

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  CodeGenFatBinaries(ttOpts).run(m);

  // This does not invalidate any analyses, even if any fat binaries were
  // generated since only global variables will have been modified.
  return PreservedAnalyses::all();
}
