// Check that the tapir.loop.target metadata is added to forall loops
// correctly.
//
// -----------------------------------------------------------------------------
// If the tapir target is nolo, the loop must not have any loop.target metadata.
//
// RUN: %kitxx -DUSEF --tapir=nolo -O1 -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix NOLO
//
// NOLO-NOT: "tapir.loop.target"
//
// -----------------------------------------------------------------------------\
// If the tapir target is not nolo, the tapir loops must have a loop.target
// metadata whose value is the integer representation of the tapir target.
//
// RUN: %kitxx -DUSEF --tapir=serial -O1 -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix SERIAL
//
// SERIAL: !{!"tapir.loop.target", i32 1}
// SERIAL-NOT: "tapir.loop.target"
//
// -----------------------------------------------------------------------------
// If a loop has a tapir target attribute, it must override the value of the
// primary tapir target passed on the command line. loop.target metadata must be
// the value of the attribute, even if the specified tapir target is nolo.
//
// FIXME: The tests below actually trigger an assertion in LoopSpawningTI
// because it does not allow the loop.target metadata value to be different
// from the primary tapir target. This is because multi-target support in the
// middle end is not yet implemented properly.
//
// In these tests, we descend into the middle-end pass pipeline even though what
// we actually want is the IR immediately after it has been generated by clang.
// Since we cannot use -O0 with most tapir targets, the workaround is to print
// the IR before the first module pass in the pipeline. However, this doesn't
// stop us from descending into the pipeline, eventually trigering the
// assertion.
//
// At some point, a frontend option will be provided to emit llvm early and
// terminate at which point, an assertion will not be triggered and the
// `not` in the test below can be removed.
//
// RUN: not %kitxx -DUSEG --tapir=serial -O1 -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix ATTR
//
// RUN: %kitxx -DUSEG --tapir=nolo -O1 -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix ATTR
//
// ATTR: !{!"tapir.loop.target", i32 2}
// ATTR-NOT: "tapir.loop.target"

#include "kitsune.h"

#ifdef USEF
extern "C" void f(int *a, int scale, size_t n) {
  // clang-format off
  forall (size_t i = 0; i < n; ++i) {
    a[i] *= scale;
  }
  // clang-format on
}
#endif // USEF

#ifdef USEG
extern "C" void g(int *a, int scale, size_t n) {
  // clang-format off
  [[tapir::target("cuda")]]
  forall (size_t i = 0; i < n; ++i) {
    a[i] *= scale;
  }
  // clang-format on
}
#endif // USEG
