//===-- kitmbc.cpp - Kitsune tool to extract embedded bitcode -------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This tool extracts the embedded bitcode present in an LLVM module generated
// by Kitsune
//
//===----------------------------------------------------------------------===//

#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/Frontend/Tapir/CommandLine.h"
#include "llvm/Frontend/Tapir/Tapir.h"
#include "llvm/IR/KitsuneMetadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/SystemUtils.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/KitsuneUtils.h"

using namespace llvm;
using namespace llvm::sys;

cl::OptionCategory KitMBC("kitmbc Options");

static cl::opt<bool> clForce("f", cl::desc("Enable binary output on terminals"),
                             cl::cat(KitMBC));

static cl::opt<std::string>
    clOutFile("o", cl::desc("The file to which to write the extracted module"),
              cl::value_desc("filename"), cl::cat(KitMBC));

static cl::opt<std::optional<TapirTargetID>, false, cl::TapirTargetIDParser>
    clOnlyTapir("only",
                cl::desc("Only extract bitcode generated by this tapir target"),
                cl::value_desc("<tapir target>"),
                cl::init(std::optional<TapirTargetID>()), cl::cat(KitMBC));

static cl::opt<bool> clOutputAssembly("S",
                                      cl::desc("Write output as LLVM assembly"),
                                      cl::cat(KitMBC));

static cl::opt<std::string> clInFile(cl::Positional,
                                     cl::desc("<input bitcode file>"),
                                     cl::init("-"), cl::value_desc("filename"),
                                     cl::cat(KitMBC));

void writeModule(Module &m, raw_ostream &os) {
  if (clOutputAssembly)
    os << m;
  else
    WriteBitcodeToFile(m, os);
}

int main(int argc, char *argv[]) {
  InitLLVM X(argc, argv);
  cl::HideUnrelatedOptions(KitMBC);
  cl::ParseCommandLineOptions(
      argc, argv,
      "Extract embedded bitcode from an LLVM IR module generated by Kitsune\n");

  InitializeAllTargets();
  InitializeAllTargetMCs();
  InitializeAllAsmPrinters();
  InitializeAllAsmParsers();

  // Write the extracted module to stdout by default. Otherwise, if a file has
  // been provided, we will write the extracted module there as long as there is
  // exactly one embedded bitcode module in the host module.
  std::error_code ec;
  StringRef outFile = clOutFile.empty() ? StringRef("-") : StringRef(clOutFile);
  fs::OpenFlags flags = clOutputAssembly ? fs::OF_TextWithCRLF : fs::OF_None;
  std::unique_ptr<ToolOutputFile> outf(new ToolOutputFile(outFile, ec, flags));
  if (ec) {
    errs() << ec.message() << '\n';
    return 1;
  }

  LLVMContext ctx;
  SMDiagnostic err;
  std::unique_ptr<Module> hostM = parseIRFile(clInFile, err, ctx);
  if (!hostM) {
    err.print(argv[0], errs());
    return 1;
  }

  // If a specific tapir target has been provided, only extract bitcode
  // generated by that target. It is possible for a single tapir target to
  // generate multiple bitcode files. First collect the global variables
  // containing embedded bitcode.
  std::vector<GlobalVariable *> gs;
  if (clOnlyTapir) {
    for (GlobalVariable &g : hostM->globals())
      if (hasKitsuneBCMD(g, *clOnlyTapir))
        gs.push_back(&g);
  } else {
    for (GlobalVariable &g : hostM->globals())
      if (hasKitsuneBCMD(g))
        gs.push_back(&g);
  }

  // Now parse those into modules.
  std::vector<std::unique_ptr<Module>> embs;
  for (GlobalVariable *g : gs) {
    embs.emplace_back(parseEmbeddedBC(*g));
    if (not embs.back()) {
      WithColor::error() << "Could not parse embedded bitcode\n";
      return 2;
    }
  }

  bool outputToStdout = outf->getFilename() == "-";
  raw_ostream &os = outf->os();
  if (embs.empty()) {
    WithColor::warning() << "No embedded bitcode modules found\n";
  } else if (not outputToStdout and embs.size() > 1) {
    // We are writing to a file, but we cannot write more than one module to
    // the file. The likely common case is that there is only embedded module in
    // the input file, so the user may expect that the resulting file can just
    // be used by the LLVM tools. If there are multiple modules, the output
    // from the terminal can still be redirected to a file.
    WithColor::error() << "Cannot write " << embs.size()
                       << " embedded modules to a single output file\n";
    return 3;
  } else if (not outputToStdout) {
    // There is only a single embedded bitcode module that is being written to
    // file. Ensure that the file is not deleted after it has been written.
    writeModule(*embs.front(), os);
    outf->keep();
  } else if (clOutputAssembly or clForce or
             not CheckBitcodeOutputToConsole(os)) {
    // We are writing to the terminal. Don't write binary output to it unless
    // the user insists on it.
    for (const auto &m : embs)
      writeModule(*m, os);
  }

  return 0;
}
