; Check the basic operations of this utility in various cases.
;
; Create a temporary directory
; RUN: mkdir -p %t
;
; RUN: MBC_2=`echo "@cuda = global i32 2" \
; RUN:     | %kit-enc --tapir=cuda \
; RUN:     | grep "c\"BC" \
; RUN:     | sed 's/.kitsune.emb//g' \
; RUN:     | sed 's/@.bc/@.bc.2/g'`
;
; RUN: MBC_4=`echo "@hip = global i32 4" \
; RUN:     | %kit-enc --tapir=hip \
; RUN:     | grep "c\"BC" \
; RUN:     | sed 's/.kitsune.emb//g' \
; RUN:     | sed 's/@.bc/@.bc.4/g' \
; RUN:     | sed 's/#0/#1/g'`
;
; RUN: printf "%%s\n%%s\n%%s\n%%s\n\n%%s\n%%s\n%%s\n%%s" \
; RUN:         "${MBC_2}" \
; RUN:         "${MBC_4}" \
; RUN:         "@fb.2 = constant [0 x i8] zeroinitializer #2" \
; RUN:         "@fb.4 = constant [0 x i8] zeroinitializer #3" \
; RUN:         "attributes #0 = { kit_bc kit_tt(2) }" \
; RUN:         "attributes #1 = { kit_bc kit_tt(4) }" \
; RUN:         "attributes #2 = { kit_fb kit_tt(2) }" \
; RUN:         "attributes #3 = { kit_fb kit_tt(4) }" \
; RUN:     > %t/in.ll
;
; ------------------------------------------------------------------------------
;
; If -f is provided, bitcode should be written stdout. If it is not provided,
; the bitcode will be passed on to the pipe anyway. We cannot easily test that
; not passing -f on the terminal will not print anything except a warning.
;
; RUN: %kit-mbc %t/in.ll | FileCheck %s --check-prefix BITCODE
; RUN: %kit-mbc %t/in.ll -f | FileCheck %s --check-prefix BITCODE
;
; ------------------------------------------------------------------------------
;
; With -S, LLVM assembly should be printed to stdout.
;
; RUN: %kit-mbc %t/in.ll -S | FileCheck %s --check-prefix ALL
;
; ------------------------------------------------------------------------------
;
; Check that reading the module from stdin works correctly
;
; RUN: cat %t/in.ll | %kit-mbc -S | FileCheck %s --check-prefix ALL
;
; ------------------------------------------------------------------------------
;
; Check that the --tapir filter works as expected.
;
; RUN: %kit-mbc %t/in.ll --tapir cuda -S \
; RUN:     | FileCheck %s --check-prefix CUDA
;
; RUN: %kit-mbc %t/in.ll --tapir hip -S \
; RUN:     | FileCheck %s --check-prefix HIP
;
; RUN: %kit-mbc %t/in.ll --tapir serial -S \
; RUN:     | FileCheck %s --check-prefix EMPTY --allow-empty
;
; ------------------------------------------------------------------------------
;
; Check that the modules can be written to file and that the format of the
; file that is written is as expected.
;
; RUN: %kit-mbc %t/in.ll --tapir cuda -o %t/cuda.bc
; RUN: cat %t/cuda.bc | FileCheck %s --check-prefix BITCODE
;
; RUN: %kit-mbc %t/in.ll --tapir cuda -o %t/cuda.ll -S
; RUN: cat %t/cuda.ll | FileCheck %s --check-prefix CUDA
;
; ------------------------------------------------------------------------------
;
; If more than one embedded module is present in the input, it cannot be written
; to file. The output file will not have been created.
;
; RUN: not %kit-mbc %t/in.ll -o %t/all.bc 2>&1 \
; RUN:     | FileCheck %s --check-prefix ERROR
; RUN: not cat %t/all.bc
;
; ------------------------------------------------------------------------------
;
; An empty file will be parsed to an empty module. There will be no embedded
; bitcode modules.
;
; RUN: %kit-mbc %S/input/empty.ll \
; RUN:     | FileCheck %s --check-prefix EMPTY --allow-empty
;
; ------------------------------------------------------------------------------
;
; Embedded bitcode modules are present in the input, but none of them have been
; generated by the given tapir target. In this case, too, a warning should be
; printed
;
; RUN: %kit-mbc --tapir serial %t/in.ll \
; RUN:     | FileCheck %s --check-prefix EMPTY --allow-empty
;
; ------------------------------------------------------------------------------
;
; If no embedded bitcode modules are found, the output file will not have been
; created.
;
; RUN: %kit-mbc %t/in.ll --tapir serial -o %t/empty.bc
; RUN: not cat %t/empty.bc
;
; ------------------------------------------------------------------------------
;
; ALL-DAG: @cuda
; ALL-DAG: @hip
; CUDA: @cuda
; HIP: @hip
; EMPTY-NOT: {{.+}}
; BITCODE: {{^[B][C]}}
; ERROR: error:
; WARNING: warning:
