! REQUIRES: kitsune-examples, kitfc
!
! FIXME: Fortran support is as yet incomplete. When it is integrated in, we
! this should pass, but some changes, especially to the check lines may be
! requied.
! XFAIL: *
!
! Check that the embedded module passes in a pass plugin are registered and
! run as expected.
!
! NOTE: We only check for the presence of external_func called in the forall
! loop. A second function, the kernel function consisting of the body of the
! forall will also be present in the embedded module. However, the name of that
! function is generated by Kitsune and will change when the algorithm used to
! generate it is changed.
!
! RUN: %if kitsune-cuda %{ \
! RUN:   %kitfc --tapir=cuda --tapir-cuda-arch=sm_86 \
! RUN:       -O1 -S -emit-llvm -o /dev/null %s \
! RUN:       -fpass-plugin=%kit-emb-pass-plugin-demo 2>&1 \
! RUN:       | FileCheck %s --check-prefixes=ALL,CUDA \
! RUN: %}
!
! RUN: %if kitsune-hip %{ \
! RUN:   %kitfc --tapir=hip --tapir-hip-arch=gfx90a \
! RUN:       -O1 -S -emit-llvm -o /dev/null %s \
! RUN:       -fpass-plugin=%kit-emb-pass-plugin-demo 2>&1 \
! RUN:       | FileCheck %s --check-prefixes=ALL,HIP \
! RUN: %}
!
! ALL-DAG: external_func
! CUDA-DAG: llvm.nvvm.read.ptx.sreg.tid.x
! HIP-DAG: llvm.amdgcn.workitem.id.x

module m

interface
  integer(8) pure function external_func(i)
    integer(8), value :: i
  end function external_func
end interface

contains
  subroutine mset(a, n)
    implicit none
    integer(8), allocatable :: a(:)
    integer(8) :: i, n

    do concurrent (i = 1 : n)
      a(i) = external_func(i)
    end do
  end subroutine mset

end module
