//===- FuncAttrDocs.td - Docs for Kitsune's argument attrs -*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Documentation for Kitsune-specific function argument attributes. These are
// used to generate the HTML documentation.
//
//===----------------------------------------------------------------------===//

