//===- CommandLineOptions.h - Command line options for Kitsune --*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Core command line options for Kitsune's tools.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_CORE_COMMAND_LINE_OPTIONS_H
#define KITSUNE_CORE_COMMAND_LINE_OPTIONS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/Support/CommandLine.h"

namespace llvm {

/// Category for command line options that are shared between kitsune-specific
/// utilities.
extern cl::OptionCategory catKitCommon;

/// Category for core Kitsune-specific command line options. These are used to
/// populate the tapir target options, and are almost exclusively used by opt
/// and llc. Several options in this category have a corresponding option in
/// clang, flang and other language frontends.
extern cl::OptionCategory catKitCore;

/// Category for Kitsune-specific command line options that are mainly intended
/// for Kitsune developers and power-users. These are generally options that
/// override the behavior of Kitsune's passes. Most of the options in this
/// category are hidden and only visible when -help-hidden is used.
extern cl::OptionCategory catKitDev;

/// @{
/// The command line options used by several kitsune-specific utilities.
///
/// We generally prefer not to expose command line option objects directly, but
/// in some cases, it is much more convenient than adding wrappers to it.

/// The --tapir option. The value of this option will be the name of a tapir
/// target.
extern cl::opt<TTID> clTapir;

/// @}

/// Override the description of the option with the given spelling.
///
/// Some command line options are shared between the Kitsune tools, but their
/// purpose is slightly different depending on the tool. For example, in the
/// kit-mbc tool, the --tapir option instructs the tool to extract only the
/// embedded bitcode that has been generated by the given tapir target. On the
/// other hand, the --tapir option instructs the kit-mdc tool to only extract
/// the embedded _device_ code generated by the given tapir target. Since it is
/// difficult to create a command line option with the same spelling that does
/// not conflict with the shared options, we simply override the description of
/// the shared options when setting up the command line options for the tools.
/// This ensures that the help message provides a more meaningful description of
/// the option in each tool.
///
/// This utility function does some error checking to ensure that an option
/// with the given spelling has been registered.
///
void clSetOptionDescription(StringRef spelling, StringRef descr);

} // namespace llvm

#endif // KITSUNE_CORE_COMMAND_LINE_OPTIONS_H
