//==- EmbBitcodeUtils.h - Helper functions for embedded bitcode -*- C++ -*--==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Kitsune embeds device module bitcode and fat binaries into the host LLVM
// module. This provides utilities to create, retrieve and modify this
// embedded data.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_CORE_EMB_BITCODE_UTILS_H
#define KITSUNE_CORE_EMB_BITCODE_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/MemoryBufferRef.h"

#include <map>
#include <memory>

namespace llvm {

class GlobalVariable;
class TapirTargetOptions;

using EmbModulesMapTy = std::map<TTID, std::unique_ptr<Module>>;

/// Create a global variable whose initializer will contain the serialized
/// bitcode for the given module. It is an error to call this on a module that
/// already contains an embedded bitcode global for the given tapir target.
///
/// @param devM The module to be serialized to embedded bitcode
/// @param tt The ID of the tapir target that is creating this embedded bitcode
/// @param hostM The host module into which the global variable will be added
/// @returns The newly created global variable
GlobalVariable *createEmbBCGlobal(const Module &devM, TTID tt, Module &hostM);

/// Parse the initializer of the given global variable which contains serialized
/// LLVM bitcode and return the resulting LLVM module.
std::unique_ptr<Module> parseEmbBCGlobal(const GlobalVariable &g);

/// Get the global variable created by a previous call to @ref createEmbBCGlobal
/// with the given tapir target if one exists.
GlobalVariable *getEmbBCGlobal(TTID tt, Module &m);

/// Reset the initializer of the given global variable \ref g with the
/// serialized bitcode of the given module. All uses of \ref g will be replaced
/// with the newly created global. The old global will be erased from its parent
/// module.
///
/// @param m The module to be serialized to embedded bitcode
/// @param g The global variable to replace with the new global
/// @returns The newly created global variable.
GlobalVariable *resetEmbBCGlobal(const Module &m, GlobalVariable &g);

/// Deserialize the embedded bitcode generated by the given tapir target and
/// return the module. Return nullptr if there is no embedded bitcode generated
/// by the tapir target.
std::unique_ptr<Module> getEmbModule(TTID tt, Module &m);

/// Create a module for use as the embedded module for the given tapir target.
/// This will set the data layout and target triple of the module correctly, but
/// nothing else - so any metadata that is needed for correct optimization
/// and/or code generation will not be added.
std::unique_ptr<Module> createEmbModule(TTID tt, const TapirTargetOptions &tto,
                                        const Module &hostM);

/// Create a module for use as the embedded module for the given tapir target
/// if it does not already exist. If it does, return the existing module. See
/// \ref createEmbModule for more details on embedded module creation.
std::unique_ptr<Module>
getOrCreateEmbModule(TTID tt, const TapirTargetOptions &tto, Module &hostM);

/// Deserialize all the embedded bitcode and return the modules in a map keyed
/// on the tapir target id that created the module.
EmbModulesMapTy getEmbModules(const Module &m);

} // namespace llvm

#endif // KITSUNE_CORE_EMB_BITCODE_UTILS_H
