//===- TargetUtils.h - Helper functions for targets/machines ---*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for targets and target machines.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_CORE_TARGET_UTILS_H
#define KITSUNE_CORE_TARGET_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/Support/CodeGen.h"

namespace llvm {

/// \addtogroup kitsune
/// @{

class MCTargetOptions;
class TTOptions;
class TargetMachine;
class TargetOptions;
class raw_ostream;

/// Create a target machine to optimize/compile device code generated by the
/// given tapir target. Currently, this is only relevant for the GPU tapir
/// targets. The machine is configured with the options in \p tto.
/// The optimization level to use in the target machine is derived from the
/// optimization level set in \p tto.
///
/// \param tt The \ref TTID of the tapir target creating the target machine
/// \param tto The options used to setup the tapir target
/// \returns A new target machine
TargetMachine *createTargetMachine(TTID tt, const TTOptions &tto);

/// Create a target machine to optimize/compile device code generated by the
/// given tapir target. Currently, this is only relevant for the GPU tapir
/// targets. The machine is configured with the options in \p tto.
/// The exception is the optimization level which is provided explicitly in
///
/// \param tt The \ref TTID of the tapir target creating the target machine
/// \param tto The options used to setup the tapir target
/// \param cgOptLevel The optimization level to set in the code generator
TargetMachine *createTargetMachine(TTID tt, const TTOptions &tto,
                                   CodeGenOptLevel cgOptLevel);

/// Create a "default" target machine. This is typically the target machine for
/// the default triple for the current Kitsune build. This will typically be
/// the host. The machine will *NOT* be specialized for the specific host CPU.
TargetMachine *createHostTargetMachine(const TTOptions &tto);

/// Dump the contents of the TargetOptions object to the given output stream.
void dump(const TargetOptions &, raw_ostream &);

/// Dump the contents of the MCTargetOptions object to the given output stream.
void dump(const MCTargetOptions &, raw_ostream &);

/// @}

} // namespace llvm

#endif // KITSUNE_CORE_TARGET_UTILS_H
