//==- TargetUtils.h - Helper functions for targets/machines -----*- C++ -*--==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for targets and target machines.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_CORE_TARGET_UTILS_H
#define KITSUNE_CORE_TARGET_UTILS_H

#include "kitsune/Core/Tapir.h"

namespace llvm {

class TapirTargetOptions;
class TargetMachine;

/// Create a target machine to optimize/compile device code generated by the
/// given tapir target. Currently, this is only relevant for the GPU tapir
/// targets. The machine is configured with the options in the
/// TapirTargetOptions object that is provided.
TargetMachine *createTargetMachine(TTID tt, const TapirTargetOptions &tto);

} // namespace llvm

#endif // KITSUNE_CORE_TARGET_UTILS_H
