; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=normalize < %s | FileCheck %s

define i32 @foo(i32) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i32 [[A0:%.*]]) {
; CHECK-NEXT:  [[BB17254:.*:]]
; CHECK-NEXT:    %"vl10381([[A0]], 2)" = add i32 [[A0]], 2
; CHECK-NEXT:    %"op58847(vl10381)" = add i32 6, %"vl10381([[A0]], 2)"
; CHECK-NEXT:    ret i32 %"op58847(vl10381)"
;
entry:
  %a = add i32 %0, 2

  %b = add i32 %a, 6

  ret i32 %b
}
