; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=normalize < %s | FileCheck %s

define i32 @foo(i32 %a0) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i32 [[A0:%.*]]) {
; CHECK-NEXT:  [[BB17254:.*:]]
; CHECK-NEXT:    %"vl11253([[A0]], 2)" = add i32 [[A0]], 2
; CHECK-NEXT:    ret i32 %"vl11253([[A0]], 2)"
;
entry:
  %a = add i32 %a0, 2
  ret i32 %a
}

define i32 @bar(i32 %a0) {
; CHECK-LABEL: define i32 @bar(
; CHECK-SAME: i32 [[A0:%.*]]) {
; CHECK-NEXT:  [[BB17254:.*:]]
; CHECK-NEXT:    %"vl51677([[A0]], 2)" = add i32 [[A0]], 2
; CHECK-NEXT:    %"op58847(vl51677)" = add i32 6, %"vl51677([[A0]], 2)"
; CHECK-NEXT:    %"op58847(op58847)" = add i32 8, %"op58847(vl51677)"
; CHECK-NEXT:    ret i32 %"op58847(op58847)"
;
entry:
  %a = add i32 %a0, 2
  %b = add i32 %a, 6
  %c = add i32 %b, 8
  ret i32 %c
}
