//===- kit-enc.cpp - Kitsune tool to encode a module as embedded bitcode --===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This tool embeds an LLVM module into an empty "host" module as Kitsune
// would embed bitcode. The host module is rendered to stdout as LLVM assembly.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Core/CommandLineOptions.h"
#include "kitsune/Core/EmbBitcodeUtils.h"
#include "kitsune/Core/EmbDeviceCodeUtils.h"
#include "kitsune/Core/ModuleUtils.h"
#include "kitsune/Core/Tapir.h"
#include "kitsune/Support/Error.h"
#include "kitsune/Support/TTUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;

static cl::OptionCategory catKitMEnc("Kitsune Options (kit-enc)");

static cl::opt<std::string>
    clModuleName("name", cl::init(""), cl::value_desc("name"),
                 cl::desc("Override the encoded module name"),
                 cl::cat(catKitMEnc));

static cl::opt<std::string> clInFile(cl::Positional,
                                     cl::desc("<input bitcode file>"),
                                     cl::init("-"), cl::value_desc("filename"),
                                     cl::cat(catKitMEnc));

static void setupCommandLineOptions() {
  cl::HideUnrelatedOptions({&catKitMEnc, &catKitCommon});
  clSetOptionDescription("tapir",
                         "The tapir target to attach to the embedded bitcode");
}

int main(int argc, char *argv[]) {
  InitLLVM X(argc, argv);

  setupCommandLineOptions();
  cl::ParseCommandLineOptions(
      argc, argv,
      "Embed an LLVM module into an empty \"host\" module. Render the \"host\" "
      "module to stdout as LLVM assembly");

  InitializeAllAsmPrinters();
  InitializeAllAsmParsers();

  // If the --tapir option is not provided, pretend as if the embedded bitcode
  // has been generated by the cuda tapir target.
  TTID tt = TTID::Cuda;
  if (clTapir.getNumOccurrences())
    tt = clTapir;
  if (not ttUsesEmbBC(tt))
    report_error(
        sjoin("'", tt, "' tapir target does not generate embedded bitcode"));

  LLVMContext ctx;
  SMDiagnostic diag;
  std::unique_ptr<Module> embM = parseIRFile(clInFile, diag, ctx);
  if (not embM)
    report_error(diag);

  if (clModuleName.getNumOccurrences())
    embM->setModuleIdentifier(clModuleName);

  Module hostM("", ctx);
  (void)addDeviceModuleMetadata(tt, *embM);
  (void)createEmbBCGlobal(*embM, tt, hostM);
  (void)createSingletonFBGlobal(tt, hostM);

  outs() << hostM;

  return 0;
}
