/*
 * Copyright (c) 2020 Triad National Security, LLC
 *                         All rights reserved.
 *
 * This file is part of the kitsune/llvm project.  It is released under
 * the LLVM license.
 */

/* This generated file is for internal use. Do not include it from headers. */

#ifdef KITSUNE_CONFIG_H
#error kitsune/Config/config.h should only be included once.
#else
#define KITSUNE_CONFIG_H

#cmakedefine01 KITSUNE_KOKKOS_ENABLE

#define KITSUNE_KOKKOS_PREPROCESSOR_FLAGS           \
  "${KITSUNE_KOKKOS_DEFAULT_PREPROCESSOR_FLAGS} "\
  "${KITSUNE_KOKKOS_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_KOKKOS_COMPILER_FLAGS \
  "${KITSUNE_KOKKOS_DEFAULT_COMPILER_FLAGS} "\
  "${KITSUNE_KOKKOS_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_KOKKOS_LINKER_FLAGS \
  "${KITSUNE_KOKKOS_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_KOKKOS_EXTRA_LINKER_FLAGS}"

#cmakedefine01 KITSUNE_CUDA_ENABLE

#define KITSUNE_CUDA_PREPROCESSOR_FLAGS \
  "${KITSUNE_CUDA_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_CUDA_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_CUDA_COMPILER_FLAGS \
  "${KITSUNE_CUDA_DEFAULT_COMPILER_FLAGS} " \
  "${KITSUNE_CUDA_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_CUDA_LINKER_FLAGS \
  "${KITSUNE_CUDA_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_CUDA_EXTRA_LINKER_FLAGS}"

#define KITSUNE_CUDA_LIBDEVICE_BC \
  "${KITSUNE_CUDA_LIBDEVICE_BC}"

#cmakedefine01 KITSUNE_HIP_ENABLE

#define KITSUNE_HIP_PREPROCESSOR_FLAGS \
  "${KITSUNE_HIP_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_HIP_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_HIP_COMPILER_FLAGS \
  "${KITSUNE_HIP_DEFAULT_COMPILER_FLAGS} " \
  "${KITSUNE_HIP_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_HIP_LINKER_FLAGS \
  "${KITSUNE_HIP_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_HIP_EXTRA_LINKER_FLAGS}"

#cmakedefine01 KITSUNE_OPENCILK_ENABLE

#define KITSUNE_OPENCILK_PREPROCESSOR_FLAGS \
  "${KITSUNE_OPENCILK_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_OPENCILK_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_OPENCILK_COMPILER_FLAGS \
  "${KITSUNE_OPENCILK_DEFAULT_COMPILER_FLAGS} " \
  "${KITSUNE_OPENCILK_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_OPENCILK_LINKER_FLAGS \
  "${KITSUNE_OPENCILK_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_OPENCILK_EXTRA_LINKER_FLAGS}"

#define KITSUNE_OPENCILK_LIBOPENCILKABI_BC \
  "${KITSUNE_OPENCILK_LIBOPENCILKABI_BC}"

#cmakedefine01 KITSUNE_OPENMP_ENABLE

#define KITSUNE_OPENMP_PREPROCESSOR_FLAGS \
  "${KITSUNE_OPENMP_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_OPENMP_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_OPENMP_COMPILER_FLAGS \
  "${KITSUNE_OPENMP_DEFAULT_COMPILER_FLAGS} " \
  "${KITSUNE_OPENMP_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_OPENMP_LINKER_FLAGS \
  "${KITSUNE_OPENMP_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_OPENMP_EXTRA_LINKER_FLAGS}"

#cmakedefine01 KITSUNE_QTHREADS_ENABLE

#define KITSUNE_QTHREADS_PREPROCESSOR_FLAGS \
  "${KITSUNE_QTHREADS_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_QTHREADS_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_QTHREADS_COMPILER_FLAGS \
  "${KITSUNE_QTHREADS_DEFAULT_COMPILER_FLAGS} " \
  "${KITSUNE_QTHREADS_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_QTHREADS_LINKER_FLAGS \
  "${KITSUNE_QTHREADS_DEFAULT_LINKER_FLAGS} " \
  "${KITSUNE_QTHREADS_EXTRA_LINKER_FLAGS}"

#cmakedefine01 KITSUNE_REALM_ENABLE

#define KITSUNE_REALM_PREPROCESSOR_FLAGS \
  "${KITSUNE_REALM_DEFAULT_PREPROCESSOR_FLAGS} " \
  "${KITSUNE_REALM_EXTRA_PREPROCESSOR_FLAGS}"

#define KITSUNE_REALM_COMPILER_FLAGS \
  "${KITSUNE_REALM_DEFAULT_COMPILER_FLAGS}" \
  "${KITSUNE_REALM_EXTRA_COMPILER_FLAGS}"

#define KITSUNE_REALM_LINKER_FLAGS \
  "${KITSUNE_REALM_DEFAULT_LINKER_FLAGS}" \
  "${KITSUNE_REALM_EXTRA_LINKER_FLAGS}"

#endif
