//===- KitsuneUtils.h - Helper functions for Kitsune -----------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Kitsune-specific utilities. This really could go anywhere, and, arguably,
// TapirUtils.h is probably a better place for these, but most of the utility
// functions there are very specific to tapir tasks and other Tapir-specific
// constructs. Most of the utilities here are intended to help deal with
// Kitsune-specific intrinsics and tapir targets
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_TRANSFORMS_UTILS_KITSUNE_UTILS_H
#define LLVM_TRANSFORMS_UTILS_KITSUNE_UTILS_H

#include "llvm/ADT/StringRef.h"
#include "llvm/Frontend/Tapir/Tapir.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/MemoryBufferRef.h"

#include <array>
#include <map>
#include <memory>

namespace llvm {

class ConstantInt;
class GlobalVariable;
class LLVMContext;
class Module;
class TapirTargetOptions;
class TargetMachine;
class Triple;

using EmbeddedModulesMapTy = std::map<TapirTargetID, std::unique_ptr<Module>>;

/// Get the LLVM type for the instruction mix data. At some point, this should
/// probably be renamed to reference more general kernel metadata.
StructType *getKernelInstMixType(LLVMContext &ctx);

/// Generate a ConstantInt for use in Kitsune-specific intrinsics that take a
/// tapir target id as an argument.
ConstantInt *getConstantInt(LLVMContext &ctxt, TapirTargetID tt);

/// Create a global variable whose initializer will contain the serialized
/// bitcode for the given module. Metadata is added to the global indicating
/// that it contains embedded bitcode generated by the given tapir target.
///
/// @param m The module to be serialized to embedded bitcode
/// @param tt The ID of the tapir target that is creating this embedded bitcode
/// @param hostM The host module into which the global variable will be added
/// @returns The newly created global variable
GlobalVariable *createEmbeddedBC(const Module &m, TapirTargetID tt,
                                 Module &hostM);

/// Parse the initializer of the given global variable which contains serialized
/// LLVM bitcode and return the resulting LLVM module.
std::unique_ptr<Module> parseEmbeddedBC(const GlobalVariable &g);

/// Get the global variable created by a previous call to @ref createEmbeddedBC
/// with the given tapir target if one exists.
GlobalVariable *getEmbeddedBC(TapirTargetID tt, Module &m);

/// Create a global variable whose initializer will contain the serialized
/// bitcode for the given module. All uses of the given global variable will be
/// replaced with the new global. The old global will be erased from its parent
/// module.
///
/// @param m The module to be serialized to embedded bitcode
/// @param g The global variable to replace with the new global
/// @returns The newly created global variable.
GlobalVariable *resetEmbeddedBC(const Module &m, GlobalVariable &g);

/// Deserialize the embedded bitcode generated by the given tapir target and
/// return the module. Return nullptr if there is no embedded bitcode generated
/// by the tapir target.
std::unique_ptr<Module> getEmbeddedModule(TapirTargetID tt, Module &m);

/// Deserialize all the embedded bitcode and return the modules in a map keyed
/// on the tapir target id that created the module.
EmbeddedModulesMapTy getEmbeddedModules(Module &m);

/// Create a global variable whose initializer is an empty array of bytes.
/// Metadata is added to the global indicating that it contains a fat binary to
/// be used by the runtime for the given tapir target.
///
/// @param tt The ID of the tapir target that is creating this embedded bitcode
/// @param m The host module into which the global variable will be created
/// @returns The newly created global variable
GlobalVariable *createEmbeddedFB(TapirTargetID tt, Module &m);

/// Get the global variable created by a previous call to @ref createEmbeddedFB
/// with the given tapir target if one exists.
GlobalVariable *getEmbeddedFB(TapirTargetID tt, Module &m);

/// Create a global variable whose initializer contains the given bytes. The
/// bytes correspond to a fat binary. All uses of the given global variable are
/// replaced with the new global. The old global is erased from the parent
/// module.
///
/// @param buf The buffer from which to create the global variable initializer
/// @param g The global variable to replace with the new global
/// @returns The newly created global variable.
GlobalVariable *resetEmbeddedFB(MemoryBufferRef buf, GlobalVariable &g);

/// Create a global variable whose initializer will eventually contain the
/// metadata for a kernel function. This metadata currently includes counts for
/// various instruction kinds in the function, but could be expanded to other
/// data as well. This global is passed to the kernel launch functions.
GlobalVariable *createKernelMDGlobal(Module &m, StringRef kname);

/// Create a private string with the given initializer if one with this
/// initializer does not already exist in the module. If one does, return that.
/// This is linear in the number of global variables in the module.
///
/// @param m The module in which to create the string
/// @param s The string initializer
/// @param name The name of the global variable that may be created
GlobalVariable *getOrCreateGlobalString(Module &m, StringRef s,
                                        StringRef name = "");

/// Create a target machine to optimize/compile device code generated by the
/// given tapir target. Currently, this is only relevant for the GPU tapir
/// targets. The machine is configured with the options in the
/// TapirTargetOptions object that is provided.
TargetMachine *createTargetMachine(TapirTargetID tt,
                                   const TapirTargetOptions &tto);

/// Get the list of tapir targets that create a global variable containing
/// embedded bitcode.
const std::array<TapirTargetID, 2> &getTargetsGeneratingEmbBC();

/// Check if the given tapir target creates a global variable containing
/// embedded bitcode.
bool generatesEmbBC(TapirTargetID tt);

} // namespace llvm

#endif // LLVM_TRANSFORMS_UTILS_KITSUNE_UTILS_H
