//=- EmbBCVerifier.h - Verify embedded modules -------------------*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utiltiies and passes to verify embedded bitcode.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_TRANSFORMS_EMB_BC_VERIFIER_H
#define KITSUNE_TRANSFORMS_EMB_BC_VERIFIER_H

#include "kitsune/Transforms/EmbBCPass.h"
#include "llvm/IR/PassManager.h"

namespace llvm {

class ModulePass;
class raw_ostream;

/// Verify the embedded bitcode module generated by a tapir target in the given
/// host module. If no embedded bitcode module was found, or if no errors were
/// found in the embedded module, returns false. Otherwise, writes a message
/// describing the error to \ref os (if non-null) and returns true.
bool verifyEmbBC(TTID tt, Module &hostM, raw_ostream *os = nullptr);

/// Verify all embedded bitcode modules found in the given host module.
///
/// If no embedded bitcode modules were found, or if no errors were found in the
/// embedded modules, returns false. Otherwise, writes a message describing the
/// error to \ref os (if non-null) and returns false.
bool verifyAllEmbBC(Module &hostM, raw_ostream *os = nullptr);

/// Check an embedded bitcode module generated by a specific tapir target for
/// validity. When a verification error is detected, a message describing the
/// error is written to stderr and a fatal error is raised. This is simply a
/// pass that wraps the \ref verifyEmbBC function.
class VerifyEmbBCPass : public EmbBCPass<VerifyEmbBCPass> {
public:
  bool run(TTID tt, Module &devM, Module &hostM, ModuleAnalysisManager &hostAM);

  using EmbBCPass<VerifyEmbBCPass>::run;
};

/// Check all embedded bitcode modules in a given host module for validity. When
/// a verification error is detected in any module, a message describing the
/// error is written to stderr and a fatal error is raised. This is simply a
/// pass that wraps the \ref verifyAllEmbBCs function.
class VerifyAllEmbBCPass : public PassInfoMixin<VerifyAllEmbBCPass> {
public:
  PreservedAnalyses run(Module &m, ModuleAnalysisManager &mam);
};

/// Check all embedded bitcode modules in a given host module for validity. When
/// a verification error is detected in any module, a message describing the
/// error is written to stderr and a fatal error is raised. This returns a pass
/// that wraps the \ref verifyAllEmbBCs function. The pass is intended to be
/// used with the legacy pass manager.
ModulePass *createVerifyAllEmbBCLegacyPass();

} // namespace llvm

#endif // KITSUNE_TRANSFORMS_EMB_BC_VERIFIER_H
