//=- DeviceCode.h - Utilities for Kitsune's embedded device code -*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// A context to maintain the state needed to manage embedded device code that
// will eventually be linked and embedded into the final executable.
//
//===----------------------------------------------------------------------===//

#ifndef LLD_ELF_DEVICE_CODE_H
#define LLD_ELF_DEVICE_CODE_H

#include "kitsune/Core/Tapir.h"
#include "lld/Common/ErrorHandler.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"

#include <map>

namespace lld::elf {

struct Ctx;
class DeviceCodeLinker;

/// Context that contains everything needed to link Kitsune's embedded device
/// code.
class DeviceCodeCtx {
public:
  using Path = SmallString<32>;

private:
  /// The "global" constant object created by the linker driver.
  Ctx &ctx;

  /// Path to a temporary working directory in which to link the embedded device
  /// code that was found in the various object files. Unless an option to
  /// persist them has been provided, they will be deleted when the destructor
  /// of this object is run.
  Path tempDir;

  std::map<llvm::TTID, std::unique_ptr<DeviceCodeLinker>> linkers;

private:
  /// Create an empty file in the temporary working directory. Return true if
  /// the temporary directory was created, false otherwise.
  bool createEmptyFile();

  // /// Create a temporary working directory. Return true if the temporary
  // /// directory was created, false otherwise.
  // bool createWorkingDir();

  // /// Get the full path to a file to which to write device code. The returned
  // /// path will be to a non-existent file in the temporary working directory.
  // llvm::StringRef getTempFilePath(llvm::TTID tt, llvm::StringRef ext);

  // /// Save the device code to a file in the temporary working directory. If a
  // /// temporary directory does not exist, one will be created. Returns true
  // if
  // /// device code could be saved, false otherwise.
  // bool saveDeviceCode(llvm::TTID tt, llvm::StringRef code, llvm::StringRef
  // ext);

  // unsigned parseSectionCuda(llvm::ArrayRef<uint8_t> buf);
  // unsigned parseSectionHip(llvm::ArrayRef<uint8_t> buf);

public:
  DeviceCodeCtx(Ctx &ctx);
  DeviceCodeCtx(const DeviceCodeCtx &) = delete;
  DeviceCodeCtx(DeviceCodeCtx &&) = delete;
  ~DeviceCodeCtx();

  DeviceCodeCtx &operator=(const DeviceCodeCtx &) = delete;
  DeviceCodeCtx &operator=(DeviceCodeCtx &&) = delete;

  /// Parse the given buffer which contains the contents of one of Kitsune's
  /// device code sections generated by the given tapir target. The contents
  /// are expected to be some number of serialized object files. These are
  /// saved into a temporary directory. The number of object files that were
  /// found and saved is returned. If any error occurred while parsing, 0 is
  /// returned.
  void parseSection(llvm::TTID tt, llvm::ArrayRef<uint8_t> buf);

  /// Link all the device code seen. This will produce a linked object file for
  /// each tapir target for which at least one embedded device code object was
  /// found. Returns the absolute paths to the linked files.
  void linkAll();
};

} // namespace lld::elf

#endif // LLD_ELF_DEVICE_CODE_H
