//===- pthreads/context.h - Context for the pthreads runtime ----*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Context object for any state required by the Kitsune's opencilk runtime.
//
//===----------------------------------------------------------------------===//

#ifndef KITRT_PTHREADS_CONTEXT_H
#define KITRT_PTHREADS_CONTEXT_H

#include "common/thread.h"

#include <cstdint>

namespace kitrt {

/// The opaque object that is returned by the launch function.
struct PthrLaunchContext;

/// The signature of the function that is run on each thread. The last argument
/// is a pointer to a struct generated by the compiler where all the data needed
/// by the function is bundled together. \p start must be 0, \p end must be the
/// equal to \ref __kitpthr_num_threads().
///
/// This is a duplicate of KitPthrThrdFunc, but if the two ever diverge, we will
/// get a build-time error.
using PthrThrdFunc = void(uint64_t start, uint64_t end, void *args);

/// Kitsune runtime the pthreads tapir target. All global state required by
/// the runtime should be owned by this object.
class PthreadsContext {
public:
  /// The number of threads to use. This should not be used directly in the rest
  /// of the runtime. Use `__kitpthr_num_threads()` to get this value.
  uint32_t numThreads = 1;

public:
  void initialize();
  void finalize();
  uint64_t getNumThreads() const;
  KitThreadID getThreadID() const;
  PthrLaunchContext *launch(PthrThrdFunc *f, uint64_t start, uint64_t end,
                            void *args, [[maybe_unused]] uint32_t argSize);
  void sync(PthrLaunchContext *ctx);
};

} // namespace kitrt

#endif // KITRT_PTHREADS_CONTEXT_H
