//===- kitpthr.cpp - Kitsune runtime targeting POSIX threads (pthreads) ---===//
//
// Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
// All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//  software was produced under U.S. Government contract
//  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//  is operated by Los Alamos National Security, LLC for the
//  U.S. Department of Energy. The U.S. Government has rights to use,
//  reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//  NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//  OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//  If software is modified to produce derivative works, such modified
//  software should be clearly marked, so as not to confuse it with
//  the version available from LANL.
//
//  Additionally, redistribution and use in source and binary forms,
//  with or without modification, are permitted provided that the
//  following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials provided
//      with the distribution.
//
//    * Neither the name of Los Alamos National Security, LLC, Los
//      Alamos National Laboratory, LANL, the U.S. Government, nor the
//      names of its contributors may be used to endorse or promote
//      products derived from this software without specific prior
//      written permission.
//
//  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//  SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//

#include "kitrt.h"

#include <algorithm>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <errno.h>
#include <limits.h>
#include <pthread.h>

#define LABEL "kitpthr"

namespace {

/// The type of the pthread start function.
using pthread_start_t = void *(*)(void *);

/// The function that is run on each thread. The last argument is a pointer to
/// a struct generated by the compiler where all the data needed by the
/// function is bundled together. start and end are the starts and ends of the
/// iteration space that must be split across the threads.
using KitPthrThrdFn = void (*)(int64_t start, int64_t end, int64_t gs,
                               void *args);

/// Metadata for each thread. This is passed to the thread launch function and
/// also contains the arguments to be passed to the "actual" thread function.
struct KitPthrThrdInfo {
  KitPthrThrdFn f;
  int64_t start;
  int64_t end;
  int64_t grainSize;
  void *args;
  pthread_t id;
  pthread_attr_t attr;
};

/// The thread context object. This is created and returned by
/// \ref __kitpthr_launch. This should be passed to __kitpthr_join where it
/// will be deleted.
struct KitPthrContext {
  /// The thread id's that were launched when this context was created.
  KitPthrThrdInfo *thrdInfo = nullptr;

  /// The number of threads that were launched.
  int64_t thrds = 0;

public:
  KitPthrContext() = default;
  KitPthrContext(int64_t thrds) {
    __kitrt_message(LABEL, "New context: %ld threads", thrds);
    this->thrdInfo = new KitPthrThrdInfo[thrds];
    this->thrds = thrds;
  }

  ~KitPthrContext() {
    __kitrt_message(LABEL, "Delete context");
    delete[] thrdInfo;
  }

  KitPthrContext(const KitPthrContext &) = delete;
  KitPthrContext(KitPthrContext &&) = delete;
  KitPthrContext &operator=(const KitPthrContext &) = delete;
};

} // namespace

[[noreturn]] static void kitpthrHandleCreateError(int err) {
  const char *lede = "Could not create thread";
  switch (err) {
  case EINVAL:
    __kitrt_fatal(LABEL, "%s. Invalid attributes", lede);
  case EAGAIN:
    __kitrt_fatal(LABEL, "%s. Insufficient resources", lede);
  case EPERM:
    __kitrt_fatal(LABEL, "%s. Insufficient permissions", lede);
  default:
    __kitrt_fatal(LABEL, "%s. Unknown error", lede);
  }
}

[[noreturn]] static void kitpthrHandleJoinError(int err) {
  const char *lede = "Error joining thread";
  switch (err) {
  case EDEADLK:
    __kitrt_fatal(LABEL, "%s. Deadlock detected", lede);
  case EINVAL:
    __kitrt_fatal(LABEL, "%s. Thread is not joinable", lede);
  case ESRCH:
    __kitrt_fatal(LABEL, "%s. Invalid thread id", lede);
  default:
    __kitrt_fatal(LABEL, "%s. Unknown error", lede);
  }
}

/// The number of threads to use. Ideally, this should be part of a global
/// object that contains all the state needed by the runtime. But that would
/// require reorganization of the runtime. A separate effort is underway that
/// does this, so do this temporarily for now.
///
/// This will be set in the global ctor for this runtime. This should not be
/// used directly in the rest of the runtime. Use `__kitpthr_num_threads()` to
/// get this value.
static unsigned __kitpthr_num_threads_v = 1;

/// Get the number of parallel workers that are available. Generally, this
/// function should be used when this must be queried instead of calling
/// `qthread_num_workers()`.
static unsigned __kitpthr_num_threads() { return __kitpthr_num_threads_v; }

/// Run \p f on the main thread. Block until f completes. Always return nullptr.
/// \p start, \p end and \p args are passed to \p f.
static KitPthrContext *runOnMainThread(KitPthrThrdFn f, int64_t start,
                                       int64_t end, int64_t grainSize,
                                       void *args) {
  __kitrt_warn(LABEL, "Running on main thread");

  f(start, end, grainSize, args);

  return new KitPthrContext;
}

/// The function that is launched by each thread. This simply finds the "actual"
/// function that is to be run in \p thrdInfo and calls it. The arguments to the
/// actual function are also present in \p thrdInfo. Always returns 0.
static void *kitpthrThrdStartFn(KitPthrThrdInfo *thrdInfo) {
  KitPthrThrdFn f = thrdInfo->f;
  int64_t start = thrdInfo->start;
  int64_t end = thrdInfo->end;
  int64_t grainSize = thrdInfo->grainSize;
  void *args = thrdInfo->args;

  f(start, end, grainSize, args);

  return nullptr;
}

/// Launch some number of threads each of which will execute some number of
/// iterations in the space [\ref start, \ref end). Terminates the program with
/// a fatal error if any thread could not be launched. The number of threads to
/// launch is determined by the value of the KIT_NUM_THREADS environment
/// variable, if it is present and set to a valid positive integer, or the
/// number of CPU's on the system if either the environment variable is not set,
/// or if it is set to a positive integer. If the number of CPU's could not be
/// determined, or if only a single CPU is available, no threads are launched.
/// Instead, the \p f is run on the main thread, which will block until \p f
/// completes.
///
/// \param f The function to execute on each thread
/// \param start The start index of the iteration space
/// \param end The value one greater than the last index of the iteration space
/// \param grainSize The grainSize
/// \param args A struct containing data to be passed to \p f
/// \return An opaque thread context object. It is the caller's responsibility
/// to call \ref __kitpthr_join with this context object. If no threads are
/// launched, i.e. \p f is run on the main thread, nullptr will be returned
/// instead. In this case, the caller is not required to call
/// \ref __kitpthr_join.
extern "C" KitPthrContext *__kitpthr_launch(KitPthrThrdFn f, int64_t start,
                                            int64_t end, int64_t grainSize,
                                            void *args) {
  __kitrt_message(LABEL, "Launching multithreaded loop: [%ld, %ld)", start,
                  end);

  // This is the number of threads that *may* be launched. However, there may
  // not be enough for work for all threads, so the actual number of threads
  // that are launched may be smaller than this.
  const unsigned availThrds = __kitpthr_num_threads();
  __kitrt_message(LABEL, "Available threads: %ld", availThrds);

  // If only a single thread is to be used, don't launch any threads. Run f on
  // the main thread and block until it finishes. Return nullptr as the thread
  // context.
  if (availThrds == 1)
    return runOnMainThread(f, start, end, grainSize, args);

  // On some systems, int64_t maps to long while on others it is long long.
  // Adding the literal to the call to std::max results in a compile time error
  // on one or another platform. Setting to a constant avoids the conditional
  // compilation directives that would other wise be needed here.
  constexpr int64_t one = 1;

  // Adding `availThrds - 1` handles the case where the range of iterations is
  // not an integer multiple of `availThrds`.
  const int64_t thrdSpan =
      std::max((end - start + availThrds - 1) / availThrds, one);
  __kitrt_message(LABEL, "Iterations per thread: %ld", thrdSpan);

  // The actual number of threads that are to be launched. Adding `thrdSpan - 1`
  // to `end` nicely deals with the case where the range of iterations is not an
  // integer multiple of thrdSpan. We could have used a conditional statement to
  // handle the two cases separately, but this is a fairly standard way of doing
  // such things.
  const int64_t thrds = (end + thrdSpan - 1 - start) / thrdSpan;
  __kitrt_message(LABEL, "Launching %ld threads", thrds);
  assert(thrds <= availThrds &&
         "Cannot launch more threads than the number that are available");

  KitPthrContext *ctx = new KitPthrContext(thrds);
  for (int64_t i = 0, beg = start; beg < end; beg += thrdSpan, ++i) {
    KitPthrThrdInfo &info = ctx->thrdInfo[i];
    info.f = f;
    info.start = beg;
    info.end = std::min(beg + thrdSpan, end);
    info.grainSize = grainSize;
    info.args = args;

    if (pthread_attr_init(&info.attr))
      __kitrt_fatal(LABEL, "Error initializing thread attributes");

    __kitrt_message(LABEL, "Fork thread %ld: [%ld, %ld)", i, info.start,
                    info.end);
    if (int err = pthread_create(&info.id, &info.attr,
                                 (pthread_start_t)kitpthrThrdStartFn,
                                 &ctx->thrdInfo[i]))
      kitpthrHandleCreateError(err);
  }

  return ctx;
}

/// Join the threads launched by a previous call to \ref __kitpthr_launch.
/// \p ctx is the context returned by that call. \p ctx may be nullptr, in which
/// case, this function does nothing.
extern "C" void __kitpthr_sync(KitPthrContext *ctx) {
  __kitrt_message(LABEL, "Joining %ld threads", ctx->thrds);
  for (size_t i = 0; i < ctx->thrds; ++i) {
    if (int err = pthread_join(ctx->thrdInfo[i].id, nullptr))
      kitpthrHandleJoinError(err);
    if (int err = pthread_attr_destroy(&ctx->thrdInfo[i].attr))
      __kitrt_fatal(LABEL, "Error destroying thread attributes");
    __kitrt_message(LABEL, "Joined thread %ld", i);
  }
  delete ctx;
}

/// The number of partial reductions to perform in parallel.
///
/// \param n The trip count of the parallel loop in containing a reduction
extern "C" int64_t __kitpthr_reduce_num_partials(int64_t n) {
  __kitrt_message(LABEL, "Calculating number of partial reductions");

  // There might be something smarter that can be done once we support a proper
  // reduction tree, but since we only support a reduction tree of depth 1, we
  // just use as many partials as there are CPU's on the system.
  unsigned numPartials = __kitpthr_num_threads();

  __kitrt_message(LABEL, "Number of partial reductions: %d", numPartials);

  return numPartials;
}

/// Initialize kitsune's pthreads runtime. Currently, this only sets some
/// global variables that enable verbose mode. This runtime is not intended to
/// ever maintain any other state.
extern "C" void __kitpthr_initialize(void) {
  // Initialize the components of kitsune's runtime that are shared by the
  // tapir-target-specific components.
  __kitrt_initialize();
  __kitrt_message(LABEL, "Initializing Kitsune pthreads runtime");

  // pthreads does not need to be initialized.
  if (unsigned numThreads = __kitrt_num_threads_from_env())
    __kitpthr_num_threads_v = numThreads;
  else
    __kitpthr_num_threads_v = __kitrt_num_cpus();

  // pthreads does not have to be initialized.

  __kitrt_message(LABEL, "Number of threads = %d", __kitpthr_num_threads());

  __kitrt_message(LABEL, "Initialized Kitsune pthreads runtime");
}

/// Finalize kitsune's pthreads runtime. This is only present for symmetry with
/// \ref __kitpthr_initialize. Since the runtime does not maintain any global
/// state of its own, this does nothing.
extern "C" void __kitpthr_finalize(void) {
  __kitrt_message(LABEL, "Finalizing Kitsune pthreads runtime");

  // pthreads does not need to be finalized.

  __kitrt_message(LABEL, "Finalized Kitsune pthreads runtime");
}
