//===- ArchiveUtils.h - Utilities for static archives ----------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for static archives.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_ARCHIVE_UTILS_H
#define KITSUNE_OBJECT_ARCHIVE_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "kitsune/Object/EmbDeviceCode.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Error.h"

namespace llvm {

class EmbDeviceCodeContext;

namespace object {

class Archive;
class ObjectFile;

using ArchiveMemberObjects = SmallVector<std::unique_ptr<ObjectFile>, 4>;

/// Check if the given archive contains embedded device code generated by the
/// given tapir target. The archive must be valid. See
/// \ref validateEmbDeviceCode.
Expected<bool> hasEmbDeviceCode(const Archive &archive);

/// Get the tapir targets that have generated embedded device code contained in
/// an object file.
Expected<SmallVector<TTID, 0>> getEmbDeviceCodeTTIDs(const Archive &archive);

/// Get the embedded device code from an archive.
Expected<SmallVector<EmbDeviceCode, 0>> getEmbDeviceCode(const Archive &ar);

/// Get the number of children in the archive. This counts all members
/// regardless of their type.
Expected<size_t> getNumMembers(const Archive &archive);

/// Get all the members from the archive that are object files. Not all members
/// are required to be objects. Those that are not will not be returned.
Expected<ArchiveMemberObjects> getMemberObjects(const Archive &archive);

} // namespace object

} // namespace llvm

#endif // KITSUNE_OBJECT_ARCHIVE_UTILS_H
