//===- ArchiveUtils.h - Utilities for static archives ----------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for static archives.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_ARCHIVE_UTILS_H
#define KITSUNE_OBJECT_ARCHIVE_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Error.h"

namespace llvm {

namespace object {

class Archive;
class ObjectFile;

using ArchiveMemberObjects = SmallVector<std::unique_ptr<ObjectFile>, 4>;

/// Check if the given archive contains embedded device code generated by the
/// given tapir target. The archive must be valid. See
/// \ref validateEmbDeviceCode.
Expected<bool> hasEmbDeviceCode(const Archive &archive);

/// Get the tapir targets that have generated embedded device code contained in
/// an object file.
Expected<SmallVector<TTID, 0>> getEmbDeviceCodeTTIDs(const Archive &obj);

/// Get the number of children in the archive. This counts all members
/// regardless of their type.
Expected<size_t> getNumMembers(const Archive &archive);

/// Get all the members from the archive that are object files. Not all members
/// are required to be objects. Those that are not will not be returned.
Expected<ArchiveMemberObjects> getMemberObjects(const Archive &archive);

/// Sanity check the embedded device code in the archive. This will return
/// Error::success if and only if _all_ the following are true:
///
///   1. Every member of the archive is an object file
///
///   2. The embedded device codes generated by a given tapir target are
///      compatible, i.e. they have the same \ref EmbDeviceCode::Id. For
///      instance, all embedded device code generated by the cuda tapir target
///      must target the same cuda architecture, or have the same virtual
///      architecture.
///
/// Not all members of the archive are required to contain embedded device code.
/// If some member contain embedded device code generated by more than one tapir
/// target, another member may contain device code generated by only one, or may
/// not contain any embedded code at all.
///
Error validateEmbDeviceCode(const Archive &archive);

} // namespace object

} // namespace llvm

#endif // KITSUNE_OBJECT_ARCHIVE_UTILS_H
