//===- BinaryUtils.h - Utilities for LLVM's binary objects -----*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for LLVM's binary objects
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_BINARY_UTILS_H
#define KITSUNE_OBJECT_BINARY_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "kitsune/Object/EmbDeviceCode.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"

namespace llvm {

class MemoryBufferRef;

namespace object {

class Binary;

/// Does the given binary object contain embedded device code generated by the
/// given tapir target.
Expected<bool> hasEmbDeviceCode(const Binary &bin);

/// Get the tapir targets that have generated embedded device code contained in
/// a binary file. The file must be an archive, an executable, a relocatable
/// object or a dynamic shared object.
Expected<SmallVector<TTID, 0>> getEmbDeviceCodeTTIDs(const Binary &bin);

/// Is the given binary object a static archive.
bool isArchive(const Binary &bin);
bool isArchive(const MemoryBufferRef &memRef);
bool isArchive(StringRef data);

/// Is the given binary object an executable. This does not check the
/// permissions on the file, just its contents. Dynamic shared objects (DSO's)
/// are not considered executable objects.
bool isExecutable(const Binary &bin);
bool isExecutable(const MemoryBufferRef &memRef);
bool isExecutable(StringRef data);

/// Is the given binary object a relocatable object. Dynamic shared objects
/// (DSO's) are not considered relocatable objects. Use \ref isShared to
/// check if the binary is a shared object.
bool isObject(const Binary &bin);
bool isObject(const MemoryBufferRef &memRef);
bool isObject(StringRef data);

/// Is the given binary object a dynamic shared object (DSO).These correspond to
/// files with an extension of .so (ELF), .dylib (MachO) or .dll (COFF).
bool isShared(const Binary &bin);
bool isShared(const MemoryBufferRef &memRef);
bool isShared(StringRef data);

} // namespace object

} // namespace llvm

#endif // KITSUNE_OBJECT_BINARY_UTILS_H
