//===- EmbDeviceCodeContext.h - Embedded device code context ---*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Context object into which all the embedded device code can be collected.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_EMB_DEVICE_CODE_CONTEXT_H
#define KITSUNE_OBJECT_EMB_DEVICE_CODE_CONTEXT_H

#include "kitsune/Object/EmbDeviceCode.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"

namespace llvm {

class EmbDeviceCodeContext;

namespace object {

class Archive;
class Binary;
class ObjectFile;

} // namespace object

/// Context object for embedded device code. Device code from several object
/// files is collected here. The object files themselves may contain device
/// code generated by more than one tapir target. This object allows the user to
/// filter this code by "source", tapir target that generated it etc. When
/// extracting the embedded device code from a static archive, the embedded
/// device code from all the object files contained within it are collected and
/// combined into a new static archive. This context owns the generated archive.
///
/// This class is intended be used like the LLVMContext instance i.e. a single
/// instance will be created and used throughout an execution. This will
/// generally be used by LLD, but it may also be used in some tools.
class EmbDeviceCodeContext {
private:
  /// The embedded device code of a static archive is itself a static archive
  /// consisting of the device code that was embedded in the members of the
  /// source archive. This "derived" archive is owned by this context.
  SmallVector<std::unique_ptr<MemoryBuffer>, 2> archives;

  /// The absolute paths to the binaries from which device embedded device code
  /// has been added. Essentially, these are all binary objects that have been
  /// passed to the \ref add method. Even if not they did not contain any device
  /// code, they will be added to this set. This ensures that the same binary is
  /// not checked more than once.
  StringSet<> bins;

  /// The device codes that have been added to this context.
  SmallMapVector<TTID, SmallVector<EmbDeviceCode, 8>, 2> devCodes;

private:
  // This is defined in kitsune/lib/Object/ObjectUtils.cpp
  /// Add the device code found in an object file. Returns the number of
  /// embedded device code objects that were added to this context.
  Expected<unsigned> add(const object::ObjectFile &obj);

  // This is defined in kitsune/lib/Object/ArchiveUtils.cpp
  /// Add the device code found in an archive. Returns the number of embedded
  /// device code objects that were added to this context. There will be at most
  /// one object for each tapir target that generated the code. If 0 is
  /// returned, no embedded device code was found.
  ///
  /// NOTE: The embedded device code added to this will be an archive containing
  /// the device code from all members of the archive. The return value of this
  /// function does *not* reflect how many of members \ref archive contained
  /// device code - it only reflects how many distinct tapir targets embedded
  /// device code into at least one member of \ref archive.
  Expected<unsigned> add(const object::Archive &archive);

public:
  EmbDeviceCodeContext() = default;
  EmbDeviceCodeContext(EmbDeviceCodeContext &&) = delete;
  EmbDeviceCodeContext &operator=(EmbDeviceCodeContext &&) = delete;

  /// Get the tapir targets for which embedded device code has been added.
  SmallVector<TTID, 0> getTTIDs() const;

  /// Get all the embedded device code generated by the given tapir target.
  const SmallVectorImpl<EmbDeviceCode> &get(TTID tt) const;

  /// Get the unique device code id common to the embedded code generated by the
  /// tapir target \ref tt. An error is returned if no embedded device code was
  /// found for \ref tt, or if a unique device code id was not found.
  Expected<EmbDeviceCode::Id> getEmbDeviceCodeId(TTID tt) const;

  /// Check if the given binary has already been added to this context.
  bool contains(const object::Binary &bin) const;

  /// Add embedded bitcode from the given binary file. The file must be an
  /// archive or an object file. Returns the number of embedded device code
  /// objects that were added to this context. A return value of 0 will be
  /// returned if
  ///
  ///   - \ref bin did not contain any device code
  ///   - \ref bin has already been added to this context.
  ///
  Expected<unsigned> add(const object::Binary &bin);
};

} // namespace llvm

#endif // KITSUNE_OBJECT_EMB_DEVICE_CODE_CONTEXT_H
