//===- ObjectUtils.h - Utilities for LLVM's object files -------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for LLVM's object files.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_OBJECT_UTILS_H
#define KITSUNE_OBJECT_OBJECT_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/Support/Error.h"

namespace llvm {

namespace object {

class ObjectFile;

/// Check if an object file contains embedded device code generated by a tapir
/// target.
Expected<bool> hasEmbDeviceCode(const ObjectFile &obj, TTID tt);

} // namespace object

} // namespace llvm

#endif // KITSUNE_OBJECT_OBJECT_UTILS_H
