//===- ObjectUtils.h - Utilities for LLVM's object files -------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for LLVM's object files.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_OBJECT_OBJECT_UTILS_H
#define KITSUNE_OBJECT_OBJECT_UTILS_H

#include "kitsune/Core/Tapir.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Object/Binary.h"
#include "llvm/Support/Error.h"

namespace llvm {

class EmbDeviceCodeContext;
class MemoryBufferRef;
class Triple;

namespace object {

class ObjectFile;

/// Create an object file from the given data. This is a simple wrapper around
/// ObjectFile::createObjectFile() that eliminates the need to explicitly create
/// a MemoryBufferRef to pass to ObjectFile::createObjectFile.
Expected<std::unique_ptr<ObjectFile>> createObjectFileFrom(StringRef data);

/// Create an empty object file for the given triple.
Expected<OwningBinary<ObjectFile>> createEmptyObject(StringRef triple,
                                                     StringRef name = "");

/// Add a section to an object. Returns a new object containing all the contents
/// of \ref objFile and the new section. The input object is discarded
/// \param objFile The input object file.
/// \param payload The contents of the new section to be added
/// \param section The name of the section to add
/// \param startSymbol If this is given, a symbol with the given name points to
///                    the start of the newly added section.
Expected<OwningBinary<ObjectFile>>
embedIntoObject(OwningBinary<ObjectFile> objFile,
                std::unique_ptr<MemoryBuffer> payload, StringRef section,
                std::optional<StringRef> startSymbol = std::nullopt);

/// Check if an object file contains embedded device code generated by any tapir
/// target.
Expected<bool> hasEmbDeviceCode(const ObjectFile &obj);

/// Get the tapir targets that have generated embedded device code contained in
/// an object file.
Expected<SmallVector<TTID, 0>> getEmbDeviceCodeTTIDs(const ObjectFile &obj);

/// Get the number of sections in an object file.
Expected<size_t> getNumSections(const ObjectFile &obj);

/// Get the number of symbols in an object file.
Expected<size_t> getNumSymbols(const ObjectFile &obj);

/// Check if the object file contains a section with the given name.
Expected<bool> hasSection(const ObjectFile &obj, StringRef name);

/// Check if the object file contains a symbol with the given name.
Expected<bool> hasSymbol(const ObjectFile &obj, StringRef name);

} // namespace object

} // namespace llvm

#endif // KITSUNE_OBJECT_OBJECT_UTILS_H
