//===- kit-mbc.cpp - Kitsune tool to extract embedded bitcode -------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This tool extracts the embedded bitcode present in an LLVM module generated
// by Kitsune
//
//===----------------------------------------------------------------------===//

#include "kitsune/Core/CommandLineOptions.h"
#include "kitsune/Core/EmbBitcodeUtils.h"
#include "kitsune/Core/GlobalVariableUtils.h"
#include "kitsune/Core/Tapir.h"
#include "kitsune/Support/Error.h"
#include "kitsune/Support/TTUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/SystemUtils.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;
using namespace llvm::sys;

static cl::OptionCategory catKitMBC("Kitsune Options (kit-mbc)");

static cl::opt<bool> clForce("f", cl::desc("Enable binary output on terminals"),
                             cl::cat(catKitMBC));

static cl::opt<std::string> clOutDir(
    "J", cl::init(""),
    cl::desc("The directory in which to extract the modules. The names of the "
             "files will be derived from the input file name and the tapir "
             "targets that generated the embedded modules [NOT IMPLEMENTED]"),
    cl::value_desc("dir"), cl::cat(catKitMBC));

static cl::opt<std::string>
    clOutFile("o", cl::init(""),
              cl::desc("The file to which to write the extracted module"),
              cl::value_desc("file"), cl::cat(catKitMBC));

static cl::opt<bool> clOutputAssembly("S",
                                      cl::desc("Write output as LLVM assembly"),
                                      cl::cat(catKitMBC));

static cl::opt<std::string> clInFile(cl::Positional,
                                     cl::desc("<input bitcode file>"),
                                     cl::init("-"), cl::value_desc("filename"),
                                     cl::cat(catKitMBC));

static void writeModule(Module &m, raw_ostream &os) {
  if (clOutputAssembly)
    os << m;
  else
    WriteBitcodeToFile(m, os);
}

static void setupCommandLineOptions() {
  cl::HideUnrelatedOptions({&catKitMBC, &catKitCommon});
  clSetOptionDescription("tapir",
                         "Extract bitcode generated by this tapir target");
}

int main(int argc, char *argv[]) {
  InitLLVM X(argc, argv);

  setupCommandLineOptions();
  cl::ParseCommandLineOptions(
      argc, argv,
      "Extract embedded bitcode from an LLVM IR module generated by Kitsune\n");

  InitializeAllAsmPrinters();
  InitializeAllAsmParsers();

  LLVMContext ctx;
  SMDiagnostic diag;
  std::unique_ptr<Module> hostM = parseIRFile(clInFile, diag, ctx);
  if (not hostM)
    report_error(diag);

  // If a specific tapir target has been provided, only extract bitcode
  // generated by that target. It is possible for a single tapir target to
  // generate multiple bitcode files.
  std::optional<TTID> tt = std::nullopt;
  if (clTapir.getNumOccurrences())
    tt = clTapir;
  if (tt and not ttUsesEmbBC(*tt))
    report_error(
        sjoin("'", *tt, "' tapir target does not generate embedded bitcode"));

  // First collect the global variables containing embedded bitcode.
  std::vector<GlobalVariable *> gs;
  if (tt) {
    for (GlobalVariable &g : hostM->globals()) {
      if (g.hasAttribute(Attribute::KitBC)) {
        assert(g.hasAttribute(Attribute::KitTT) &&
               "Attribute 'kit_bc' requires 'kit_tt");
        if (getAttrValueAsTTID(g, Attribute::KitTT) == *tt)
          gs.push_back(&g);
      }
    }
  } else {
    for (GlobalVariable &g : hostM->globals()) {
      if (g.hasAttribute(Attribute::KitBC)) {
        assert(g.hasAttribute(Attribute::KitTT) &&
               "Attribute 'kit_bc' requires 'kit_tt");
        if (g.hasAttribute(Attribute::KitTT))
          gs.push_back(&g);
      }
    }
  }

  // Now parse those into modules.
  std::vector<std::unique_ptr<Module>> embs;
  for (GlobalVariable *g : gs) {
    embs.emplace_back(parseEmbBCGlobal(*g));
    if (not embs.back())
      report_error("Could not parse embedded bitcode");
  }

  bool outputToStdout = clOutFile.empty();
  if (embs.empty()) {
    report_warning("no embedded bitcode modules found");
  } else if (not outputToStdout and embs.size() > 1) {
    // We are writing to a file, but we cannot write more than one module to
    // the file. The common case is that there is only one embedded module in
    // the input file, so the user may expect that the resulting file can just
    // be used by the LLVM tools. If there are multiple modules, the output
    // from the terminal can still be redirected to a file.
    report_error(sjoin("cannot write ", embs.size(),
                       " embedded modules to a single output file"));
  } else if (not outputToStdout) {
    // There is only a single embedded bitcode module that is being written to
    // file. Ensure that the file is not deleted after it has been written.
    std::error_code ec;
    fs::OpenFlags flags = clOutputAssembly ? fs::OF_TextWithCRLF : fs::OF_None;
    auto outf = std::make_unique<ToolOutputFile>(clOutFile, ec, flags);
    if (ec)
      report_error(ec);
    outf->keep();
    writeModule(*embs.front(), outf->os());
  } else if (clOutputAssembly or clForce or
             not CheckBitcodeOutputToConsole(outs())) {
    // We are writing to the terminal. Don't write binary output to it unless
    // the user insists on it.
    for (const auto &m : embs)
      writeModule(*m, outs());
  }

  return 0;
}
