//===- ArchiveUtils.cpp - Utilities for static archives -------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities for static archives.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Object/ArchiveUtils.h"
#include "kitsune/Object/BinaryUtils.h"
#include "kitsune/Object/EmbDeviceCode.h"
#include "kitsune/Object/EmbDeviceCodeContext.h"
#include "kitsune/Object/ObjectUtils.h"
#include "kitsune/Support/Error.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/MemoryBuffer.h"

using namespace llvm;
using namespace llvm::object;

Expected<bool> llvm::object::hasEmbDeviceCode(const Archive &archive) {
  Expected<ArchiveMemberObjects> objs = getMemberObjects(archive);
  if (not objs)
    return objs.takeError();

  for (const std::unique_ptr<ObjectFile> &obj : *objs) {
    Expected<bool> hasDeviceCode = hasEmbDeviceCode(*obj);
    if (not hasDeviceCode)
      return hasDeviceCode.takeError();
    else if (*hasDeviceCode)
      return true;
  }
  return false;
}

Expected<SmallVector<TTID, 0>>
llvm::object::getEmbDeviceCodeTTIDs(const Archive &archive) {
  Expected<ArchiveMemberObjects> objs = getMemberObjects(archive);
  if (not objs)
    return objs.takeError();

  SmallSetVector<TTID, 2> tts;
  for (const std::unique_ptr<ObjectFile> &obj : *objs) {
    Expected<SmallVector<TTID, 0>> objTTs = getEmbDeviceCodeTTIDs(*obj);
    if (not objTTs)
      return objTTs.takeError();
    for (TTID tt : *objTTs)
      tts.insert(tt);
  }
  return tts.takeVector();
}

Expected<size_t> llvm::object::getNumMembers(const Archive &archive) {
  size_t count = 0;
  Error err = Error::success();
  for (const Archive::Child &[[gnu::unused]] child : archive.children(err)) {
    if (err)
      return err;
    ++count;
  }
  if (err)
    return err;
  return count;
}

Expected<ArchiveMemberObjects>
llvm::object::getMemberObjects(const Archive &archive) {
  ArchiveMemberObjects objFiles;
  Error err = Error::success();
  for (const Archive::Child &child : archive.children(err)) {
    if (err)
      return err;

    Expected<MemoryBufferRef> memBufOrErr = child.getMemoryBufferRef();
    if (not memBufOrErr)
      return memBufOrErr.takeError();
    const MemoryBufferRef &memBuf = *memBufOrErr;

    Expected<std::unique_ptr<ObjectFile>> objFileOrErr =
        ObjectFile::createObjectFile(memBuf);
    if (not objFileOrErr)
      return objFileOrErr.takeError();
    std::unique_ptr<ObjectFile> objFile = std::move(*objFileOrErr);

    if (isObject(*objFile))
      objFiles.emplace_back(std::move(objFile));
  }
  if (err)
    return err;
  return objFiles;
}

Expected<unsigned> EmbDeviceCodeContext::add(const Archive &archive) {
  Expected<ArchiveMemberObjects> objFilesOrErr = getMemberObjects(archive);
  if (not objFilesOrErr)
    return objFilesOrErr.takeError();
  const ArchiveMemberObjects &objFiles = *objFilesOrErr;

  EmbDeviceCodeContext archiveCtx;
  for (const std::unique_ptr<ObjectFile> &objFile : objFiles) {
    Expected<unsigned> r = archiveCtx.add(*objFile);
    if (not r)
      return r;
  }

  unsigned added = 0;
  for (TTID tt : archiveCtx.getTTIDs()) {
    // Sanity check the embedded device code objects that were found. All
    // embedded device code objects generated by a given tapir target must have
    // the same binary format and target.
    Expected<EmbDeviceCode::Id> idOrErr = archiveCtx.getEmbDeviceCodeId(tt);
    if (not idOrErr)
      return idOrErr.takeError();
    EmbDeviceCode::Id id = *idOrErr;

    SmallVector<NewArchiveMember, 4> newMembers;
    for (const EmbDeviceCode &devCode : archiveCtx.get(tt)) {
      StringRef name = devCode.getName();
      StringRef code = devCode.getCode();
      NewArchiveMember &member = newMembers.emplace_back();
      member.Buf = MemoryBuffer::getMemBuffer(code, name,
                                              /*RequiresNullTerminator=*/false);
      member.MemberName = name;
    }

    Expected<std::unique_ptr<MemoryBuffer>> newArchiveOrErr =
        writeArchiveToBuffer(newMembers, SymtabWritingMode::NormalSymtab,
                             Archive::getDefaultKind(), /*Deterministic=*/false,
                             /*Thin=*/false);
    if (not newArchiveOrErr)
      return newArchiveOrErr.takeError();
    std::unique_ptr<MemoryBuffer> newArchive = std::move(*newArchiveOrErr);

    StringRef newArchiveCode = newArchive->getBuffer();
    StringRef oldArchiveName = archive.getFileName();
    MemoryBufferRef newMemBuf(newArchiveCode, oldArchiveName);

    Expected<EmbDeviceCode> devCodeOrErr = EmbDeviceCode::create(id, newMemBuf);
    if (not devCodeOrErr)
      return devCodeOrErr.takeError();
    const EmbDeviceCode &devCode = *devCodeOrErr;

    devCodes[tt].push_back(devCode);
    archives.emplace_back(std::move(newArchive));
    ++added;
  }
  if (added)
    bins.insert(archive.getFileName());
  return added;
}
