//===- fatbin_globals.cpp - Global variables for hip's fat binaries -------===//
//
//  Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
//  All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//   software was produced under U.S. Government contract
//   DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//   is operated by Los Alamos National Security, LLC for the
//   U.S. Department of Energy. The U.S. Government has rights to use,
//   reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//   NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//   OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//   If software is modified to produce derivative works, such modified
//   software should be clearly marked, so as not to confuse it with
//   the version available from LANL.
//
//   Additionally, redistribution and use in source and binary forms,
//   with or without modification, are permitted provided that the
//   following conditions are met:
//
//  Redistributions of source code must retain the above copyright
//  notice, this list of conditions and the following disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials provided
//       with the distribution.
//
//     * Neither the name of Los Alamos National Security, LLC, Los
//       Alamos National Laboratory, LANL, the U.S. Government, nor the
//       names of its contributors may be used to endorse or promote
//       products derived from this software without specific prior
//       written permission.
//
//   THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
//   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
//   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
//   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//   POSSIBILITY OF SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//
//
// EXPERIMENTAL: This is an experimental implementation where some of the code
// that used to be generated by the compiler is kept here instead. This is in
// support of the attempt at enabling true cross-translation unit support in
// Kitsune. This has been written at a time when the runtime design is in major
// flux, so everything here is basically hacked together and should eventually
// be moved into the new setup.
//
//===----------------------------------------------------------------------===//

#include <cstdint>
#include <cstdio>
#include <cstdlib>

extern "C" {

void *__hipRegisterFatBinary(void *fatbin);
void __hipUnregisterFatBinary(void *fatbinHandle);
void __hipRegisterVar(void *fatbinHandle, void *hostAddr, const char *hostName,
                      const char *deviceName, int ext, size_t size, int isConst,
                      int global);

/// The bundle object that will contain a pointer to the singleton fat binary
/// required by Kitsune's hip runtime.
struct HipBundle {
  uint32_t magic;   /// Magic number for this bundle
  uint32_t version; /// The version of (presumably) the object format
  void *fatbin;     /// Pointer to the raw fatbin data
  void *unused;     /// This is currently unused and always set to nullptr
};

/// The magic number for the hip bundle.
static constexpr int magic = 0x48495046;

/// The object version. This is currently 1. It is not clear when, or if, this
/// will ever change.
static constexpr int version = 1;

/// The actual fat binary will be generated by Kitsune's linker. The size is
/// obviously not known here, so we just use a byte. We could just as easily use
/// a different type because we are actually only interested in the address of
/// the __kithip_fatbin symbol. The compiler is guaranteed to emit a variable
/// with this name, so when this library is linked into the code being compiled,
/// the symbol will become available.
__attribute__((section(".hip_fatbin"))) uint8_t __kithip_fatbin;

/// The singleton bundle object that the hip runtime and tools expect. This is
/// intentionally visible externally.

__attribute__((section(".hipFatBinSegment"))) HipBundle __kithip_bundle;

/// The global variable that contains an opaque pointer to the registered
/// fat binary. This is returned by the call to __hipRegisterFatBinary. It is
/// eventually passed to __hipUnregisterFatBinary.
///
/// Eventually, this should become part of the singleton kithip runtime object
/// so it needn't be global.
static void *__kithip_handle = nullptr;

static void __kithip_unregister_fatbin(void) {
  __hipUnregisterFatBinary(__kithip_handle);
}

/// This is called from the ctor's generated by Kitsune.
void __kithip_register_fatbin(void) {
  if (__kithip_handle)
    return;

  __kithip_bundle.magic = magic;
  __kithip_bundle.version = version;
  __kithip_bundle.fatbin = &__kithip_fatbin;
  __kithip_bundle.unused = nullptr;

  __kithip_handle = __hipRegisterFatBinary(&__kithip_bundle);

  // This is only present to allow __hipUnregisterFatBinary to be called.
  // Eventually, this should be folded into the singleton kithip runtime object.
  // In that case, we will be guaranteed that the object's destructor will run,
  // so this will be unnecessary.
  std::atexit(__kithip_unregister_fatbin);
}

/// This is called from the ctor's generated by Kitsune. This has fewer
/// parameters than hip's register function because we use this in a very
/// limited manner. For instance, we know that the names of the global variables
/// are guaranteed to be identical in the host and device. Other comments are
/// inline within the function.
void __kithip_register_var(void *var, const char *name, size_t size) {
  // FIXME?: Why is this always set to zero? The API is asking if this is
  // "external". Is this asking if it has external linkage? Or is it asking
  // if this is externally defined (as in C's extern)? In either case, why
  // are we always passing 0 here? Is this just the "safer" course, or is it
  // that we just haven't yet encountered a situation where this should be
  // non-zero? Or does hip require this to be zero currently because it is
  // they who have not implemented something?
  int ext = 0;

  // Only non-constant globals need to be registered.
  int constant = 0;

  __hipRegisterVar(__kithip_handle, /* Handle to the registered fat binary */
                   var,             /* The shadow variable in host code */
                   name,            /* The name of the global in the host */
                   name,            /* The name of the global in the device */
                   ext,             /* Is this global external */
                   size,            /* The size, in bytes, of the global */
                   constant,        /* Is the global constant */
                   0 /* Per the documentation, this must always be 0 */);
}

} // extern "C"
