//- CodeGenFatBinaries.h - Compile embedded bitcode to device code -*- C++ -*-//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into device code.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_CODEGEN_CODEGEN_FAT_BINARIES_H
#define KITSUNE_CODEGEN_CODEGEN_FAT_BINARIES_H

#include "kitsune/Core/TTOptions.h"
#include "llvm/IR/PassManager.h"

namespace llvm {

class ModulePass;

/// \ingroup kitsune
/// Compiles embedded in a module to device code. Updates the initializers of
/// the global variables that are to contain the device code. These will already
/// be present in the module. Remove the globals containing the embedded
/// bitcode.
class CodeGenFatBinariesPass : public PassInfoMixin<CodeGenFatBinariesPass> {
protected:
  const TTOptions &tto;

public:
  CodeGenFatBinariesPass(const TTOptions &tto) : tto(tto) {}

  PreservedAnalyses run(Module &m, ModuleAnalysisManager &am);
};

/// \ingroup kitsune
/// Create a legacy pass to compile embedded bitcode in a module to device code.
/// This must always be called with a TTOptions object. The only reason a
/// default is provided is so this can be called from LinkAllPasses.h.
ModulePass *
createCodeGenFatBinariesLegacyPass(const TTOptions &tto = TTOptions());

} // namespace llvm

#endif // KITSUNE_CODEGEN_CODEGEN_FAT_BINARIES_H
