//===- EmbDeviceCodeUtils.cpp - Utilities for embedded device code --------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities to work with embedded device code generated by Kitsune.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Core/EmbDeviceCodeUtils.h"
#include "kitsune/Support/StringUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Error.h"

using namespace llvm;

std::optional<TTID> llvm::getTTIDForSection(StringRef section) {
  return StringSwitch<std::optional<TTID>>(section)
      .Case(KITSUNE_CUDA_CODE_SECTION, TTID::Cuda)
      .Case(KITSUNE_HIP_CODE_SECTION, TTID::Hip)
      .Default(std::nullopt);
}

std::optional<StringRef> llvm::getSectionForTTID(TTID tt) {
  switch (tt) {
  case TTID::Cuda:
    return KITSUNE_CUDA_CODE_SECTION;
  case TTID::Hip:
    return KITSUNE_HIP_CODE_SECTION;
  default:
    return std::nullopt;
  }
}

StringLiteral llvm::getSingletonFBName(TTID tt) {
  switch (tt) {
  case TTID::Cuda:
    return KITSUNE_CUDA_FB_NAME;
  case TTID::Hip:
    return KITSUNE_HIP_FB_NAME;
  default:
    llvm_unreachable("getFatbinName: TTID not handled");
  }
}

StringLiteral llvm::getSingletonFBSection(TTID tt) {
  switch (tt) {
  case TTID::Cuda:
    return KITSUNE_CUDA_FB_SECTION;
  case TTID::Hip:
    return KITSUNE_HIP_FB_SECTION;
  default:
    llvm_unreachable("getFatbinSection: TTID not handled");
  }
}

GlobalVariable *llvm::createSingletonFBGlobal(TTID tt, Module &hostM) {
  assert(!getSingletonFBGlobal(tt, hostM) &&
         "Singleton fat binary global already exists");

  LLVMContext &ctx = hostM.getContext();
  Type *i8 = Type::getInt8Ty(ctx);
  Type *type = ArrayType::get(i8, 0);
  StringLiteral name = getSingletonFBName(tt);
  GlobalValue::LinkageTypes linkage = GlobalValue::ExternalLinkage;

  GlobalVariable *g = new GlobalVariable(
      hostM, type, /*isConstant=*/true, linkage, /*Initializer=*/nullptr, name);
  g->addAttribute(Attribute::KitFB);
  g->addAttribute(Attribute::getWithTTID(ctx, tt));
  g->setSection(getSingletonFBSection(tt));

  return g;
}

GlobalVariable *llvm::getSingletonFBGlobal(TTID tt, Module &m) {
  return m.getGlobalVariable(getSingletonFBName(tt));
}
