//===- SingletonUtils.cpp - Utilities for Kitsune's singletons ------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities to work with object files generated by Kitsune. These typically
// have specially named symbols and sections. The utilities here provide a way
// to work with them independent of the underlying object file format (ELF,
// MachO) etc.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Core/SingletonUtils.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Error.h"

using namespace llvm;

StringLiteral llvm::getFatbinName(TTID tt) {
  switch (tt) {
  case TTID::Cuda:
    return cudaFatbinName;
  case TTID::Hip:
    return hipFatbinName;
  default:
    llvm_unreachable("getFatbinName: TTID not handled");
  }
}

StringLiteral llvm::getFatbinSection(TTID tt) {
  switch (tt) {
  case TTID::Cuda:
    return cudaFatbinSection;
  case TTID::Hip:
    return hipFatbinSection;
  default:
    llvm_unreachable("getFatbinSection: TTID not handled");
  }
}

GlobalVariable *llvm::createSingletonFBGlobal(TTID tt, Module &hostM) {
  assert(!getSingletonFBGlobal(tt, hostM) &&
         "Singleton fat binary global already exists");

  LLVMContext &ctx = hostM.getContext();
  Type *i8 = Type::getInt8Ty(ctx);
  Type *type = ArrayType::get(i8, 0);
  StringLiteral name = getFatbinName(tt);
  GlobalValue::LinkageTypes linkage = GlobalValue::ExternalLinkage;

  GlobalVariable *g = new GlobalVariable(
      hostM, type, /*isConstant=*/true, linkage, /*Initializer=*/nullptr, name);
  g->addAttribute(Attribute::KitFB);
  g->addAttribute(Attribute::getWithTTID(ctx, tt));
  g->setSection(getFatbinSection(tt));

  return g;
}

GlobalVariable *llvm::getSingletonFBGlobal(TTID tt, Module &m) {
  return m.getGlobalVariable(getFatbinName(tt));
}
