; REQUIRES: kitsune-hip
;
; Check that the Kitsune-specific intriniscs that may appear in an embedded
; module are lowered correctly when said module has been generated by the
; 'hip' tapir target.
;
; This test intentionally includes tests calls to intrinsics that are not
; lowered. Kitsune currently lowers these to calls to a function in a
; libdevice bitcode file. This will have to be done in the middle-end while
; the emb-lower-intrinsics is a codegen pass.
;
; RUN: %kit-enc --tapir=hip %s \
; RUN:      | opt --tapir=hip -passes='emb-lower-intrinsics' \
; RUN:      | %kit-mbc --tapir=hip -S \
; RUN:      | FileCheck %s
;
; CHECK: entry:
; CHECK-NEXT: %tid.x = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT: %tid.y = call i32 @llvm.amdgcn.workitem.id.y()
; CHECK-NEXT: %tid.z = call i32 @llvm.amdgcn.workitem.id.z()
; CHECK-NEXT: %bid.x = call i32 @llvm.amdgcn.workgroup.id.x()
; CHECK-NEXT: %bid.y = call i32 @llvm.amdgcn.workgroup.id.y()
; CHECK-NEXT: %bid.z = call i32 @llvm.amdgcn.workgroup.id.z()
; CHECK-NEXT: br label %unchanged
; CHECK-EMPTY:
; CHECK-NEXT: unchanged:
; CHECK-NEXT: %bsz.x = call i32 @llvm.kit.gpu.block.size.x()
; CHECK-NEXT: %bsz.y = call i32 @llvm.kit.gpu.block.size.y()
; CHECK-NEXT: %bsz.z = call i32 @llvm.kit.gpu.block.size.z()
; CHECK-NEXT: %gsz.x = call i32 @llvm.kit.gpu.grid.size.x()
; CHECK-NEXT: %gsz.y = call i32 @llvm.kit.gpu.grid.size.y()
; CHECK-NEXT: %gsz.z = call i32 @llvm.kit.gpu.grid.size.z()
; CHECK-NEXT: br label %uses
; CHECK-EMPTY:
; CHECK-NEXT: uses:
; CHECK-NEXT: call void @ext(i32 %tid.x)
; CHECK-NEXT: call void @ext(i32 %tid.y)
; CHECK-NEXT: call void @ext(i32 %tid.z)
; CHECK-NEXT: call void @ext(i32 %bid.x)
; CHECK-NEXT: call void @ext(i32 %bid.y)
; CHECK-NEXT: call void @ext(i32 %bid.z)
; CHECK-NEXT: call void @ext(i32 %bsz.x)
; CHECK-NEXT: call void @ext(i32 %bsz.y)
; CHECK-NEXT: call void @ext(i32 %bsz.z)
; CHECK-NEXT: call void @ext(i32 %gsz.x)
; CHECK-NEXT: call void @ext(i32 %gsz.y)
; CHECK-NEXT: call void @ext(i32 %gsz.z)
; CHECK-NEXT: br label %exit
; CHECK-EMPTY:
; CHECK-NEXT: exit:
; CHECK-NEXT: ret void

declare void @ext(i32)

define void @f() {
entry:
  %tid.x = call i32 @llvm.kit.gpu.thread.id.x();
  %tid.y = call i32 @llvm.kit.gpu.thread.id.y();
  %tid.z = call i32 @llvm.kit.gpu.thread.id.z();
  %bid.x = call i32 @llvm.kit.gpu.block.id.x();
  %bid.y = call i32 @llvm.kit.gpu.block.id.y();
  %bid.z = call i32 @llvm.kit.gpu.block.id.z();
  br label %unchanged

unchanged:
  %bsz.x = call i32 @llvm.kit.gpu.block.size.x();
  %bsz.y = call i32 @llvm.kit.gpu.block.size.y();
  %bsz.z = call i32 @llvm.kit.gpu.block.size.z();
  %gsz.x = call i32 @llvm.kit.gpu.grid.size.x();
  %gsz.y = call i32 @llvm.kit.gpu.grid.size.y();
  %gsz.z = call i32 @llvm.kit.gpu.grid.size.z();
  br label %uses

uses:
  call void @ext(i32 %tid.x)
  call void @ext(i32 %tid.y)
  call void @ext(i32 %tid.z)
  call void @ext(i32 %bid.x)
  call void @ext(i32 %bid.y)
  call void @ext(i32 %bid.z)
  call void @ext(i32 %bsz.x)
  call void @ext(i32 %bsz.y)
  call void @ext(i32 %bsz.z)
  call void @ext(i32 %gsz.x)
  call void @ext(i32 %gsz.y)
  call void @ext(i32 %gsz.z)
  br label %exit

exit:
  ret void
}
