; REQUIRES: kitsune-cuda
;
; Check that the Kitsune-specific intriniscs that may appear in an embedded
; module are lowered correctly when said module has been generated by the
; 'cuda' tapir target.
;
; RUN: %kit-enc --tapir=cuda %s \
; RUN:      | opt --tapir=cuda -passes='emb-lower-intrinsics' \
; RUN:      | %kit-mbc --tapir=cuda -S \
; RUN:      | FileCheck %s
;
; CHECK: [[ENTRY:.+]]:
; CHECK-NEXT: %[[TIDX:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT: %[[TIDY:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.y()
; CHECK-NEXT: %[[TIDZ:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.z()
; CHECK-NEXT: %[[BIDX:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT: %[[BIDY:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.y()
; CHECK-NEXT: %[[BIDZ:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.z()
; CHECK-NEXT: %[[BSZX:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT: %[[BSZY:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.y()
; CHECK-NEXT: %[[BSZZ:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.z()
; CHECK-NEXT: %[[GSZX:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x()
; CHECK-NEXT: %[[GSZY:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.y()
; CHECK-NEXT: %[[GSZZ:.+]] = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.z()
; CHECK-NEXT: br label %[[USES:.+]]
; CHECK-EMPTY:
; CHECK-NEXT: [[USES]]:
; CHECK-NEXT: call void @ext(i32 %[[TIDX]])
; CHECK-NEXT: call void @ext(i32 %[[TIDY]])
; CHECK-NEXT: call void @ext(i32 %[[TIDZ]])
; CHECK-NEXT: call void @ext(i32 %[[BIDX]])
; CHECK-NEXT: call void @ext(i32 %[[BIDY]])
; CHECK-NEXT: call void @ext(i32 %[[BIDZ]])
; CHECK-NEXT: call void @ext(i32 %[[BSZX]])
; CHECK-NEXT: call void @ext(i32 %[[BSZY]])
; CHECK-NEXT: call void @ext(i32 %[[BSZZ]])
; CHECK-NEXT: call void @ext(i32 %[[GSZX]])
; CHECK-NEXT: call void @ext(i32 %[[GSZY]])
; CHECK-NEXT: call void @ext(i32 %[[GSZZ]])
; CHECK-NEXT: br label %[[EXIT:.+]]
; CHECK-EMPTY:
; CHECK-NEXT: [[EXIT]]:
; CHECK-NEXT: ret void

declare void @ext(i32)

define void @f() {
entry:
  %tid.x = call i32 @llvm.kit.gpu.thread.id.x(i32 2)
  %tid.y = call i32 @llvm.kit.gpu.thread.id.y(i32 2)
  %tid.z = call i32 @llvm.kit.gpu.thread.id.z(i32 2)
  %bid.x = call i32 @llvm.kit.gpu.block.id.x(i32 2)
  %bid.y = call i32 @llvm.kit.gpu.block.id.y(i32 2)
  %bid.z = call i32 @llvm.kit.gpu.block.id.z(i32 2)
  %bsz.x = call i32 @llvm.kit.gpu.block.size.x(i32 2)
  %bsz.y = call i32 @llvm.kit.gpu.block.size.y(i32 2)
  %bsz.z = call i32 @llvm.kit.gpu.block.size.z(i32 2)
  %gsz.x = call i32 @llvm.kit.gpu.grid.size.x(i32 2)
  %gsz.y = call i32 @llvm.kit.gpu.grid.size.y(i32 2)
  %gsz.z = call i32 @llvm.kit.gpu.grid.size.z(i32 2)
  br label %uses

uses:
  call void @ext(i32 %tid.x)
  call void @ext(i32 %tid.y)
  call void @ext(i32 %tid.z)
  call void @ext(i32 %bid.x)
  call void @ext(i32 %bid.y)
  call void @ext(i32 %bid.z)
  call void @ext(i32 %bsz.x)
  call void @ext(i32 %bsz.y)
  call void @ext(i32 %bsz.z)
  call void @ext(i32 %gsz.x)
  call void @ext(i32 %gsz.y)
  call void @ext(i32 %gsz.z)
  br label %exit

exit:
  ret void
}
