; REQUIRES: kitsune-cuda
;
; Check that the Kitsune-specific intriniscs that may appear in an embedded
; module are lowered correctly when said module has been generated by the
; 'cuda' tapir target.
;
; RUN: %kit-enc --tapir=cuda %s \
; RUN:      | opt --tapir=cuda -passes='emb-lower-intrinsics' \
; RUN:      | %kit-mbc --tapir=cuda -S \
; RUN:      | FileCheck %s
;
; CHECK: entry:
; CHECK-NEXT: %tid.x = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT: %tid.y = call i32 @llvm.nvvm.read.ptx.sreg.tid.y()
; CHECK-NEXT: %tid.z = call i32 @llvm.nvvm.read.ptx.sreg.tid.z()
; CHECK-NEXT: %bid.x = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT: %bid.y = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.y()
; CHECK-NEXT: %bid.z = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.z()
; CHECK-NEXT: %bsz.x = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT: %bsz.y = call i32 @llvm.nvvm.read.ptx.sreg.ntid.y()
; CHECK-NEXT: %bsz.z = call i32 @llvm.nvvm.read.ptx.sreg.ntid.z()
; CHECK-NEXT: %gsz.x = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x()
; CHECK-NEXT: %gsz.y = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.y()
; CHECK-NEXT: %gsz.z = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.z()
; CHECK-NEXT: br label %uses
; CHECK-EMPTY:
; CHECK-NEXT: uses:
; CHECK-NEXT: call void @ext(i32 %tid.x)
; CHECK-NEXT: call void @ext(i32 %tid.y)
; CHECK-NEXT: call void @ext(i32 %tid.z)
; CHECK-NEXT: call void @ext(i32 %bid.x)
; CHECK-NEXT: call void @ext(i32 %bid.y)
; CHECK-NEXT: call void @ext(i32 %bid.z)
; CHECK-NEXT: call void @ext(i32 %bsz.x)
; CHECK-NEXT: call void @ext(i32 %bsz.y)
; CHECK-NEXT: call void @ext(i32 %bsz.z)
; CHECK-NEXT: call void @ext(i32 %gsz.x)
; CHECK-NEXT: call void @ext(i32 %gsz.y)
; CHECK-NEXT: call void @ext(i32 %gsz.z)
; CHECK-NEXT: call void @ext(i32 32)
; CHECK-NEXT: br label %exit
; CHECK-EMPTY:
; CHECK-NEXT: exit:
; CHECK-NEXT: ret void

declare void @ext(i32)

define void @f() {
entry:
  %tid.x = call i32 @llvm.kit.gpu.thread.id.x(i32 2)
  %tid.y = call i32 @llvm.kit.gpu.thread.id.y(i32 2)
  %tid.z = call i32 @llvm.kit.gpu.thread.id.z(i32 2)
  %bid.x = call i32 @llvm.kit.gpu.block.id.x(i32 2)
  %bid.y = call i32 @llvm.kit.gpu.block.id.y(i32 2)
  %bid.z = call i32 @llvm.kit.gpu.block.id.z(i32 2)
  %bsz.x = call i32 @llvm.kit.gpu.block.size.x(i32 2)
  %bsz.y = call i32 @llvm.kit.gpu.block.size.y(i32 2)
  %bsz.z = call i32 @llvm.kit.gpu.block.size.z(i32 2)
  %gsz.x = call i32 @llvm.kit.gpu.grid.size.x(i32 2)
  %gsz.y = call i32 @llvm.kit.gpu.grid.size.y(i32 2)
  %gsz.z = call i32 @llvm.kit.gpu.grid.size.z(i32 2)
  %warpSize = call i32 @llvm.kit.gpu.warp.size(i32 2)
  br label %uses

uses:
  call void @ext(i32 %tid.x)
  call void @ext(i32 %tid.y)
  call void @ext(i32 %tid.z)
  call void @ext(i32 %bid.x)
  call void @ext(i32 %bid.y)
  call void @ext(i32 %bid.z)
  call void @ext(i32 %bsz.x)
  call void @ext(i32 %bsz.y)
  call void @ext(i32 %bsz.z)
  call void @ext(i32 %gsz.x)
  call void @ext(i32 %gsz.y)
  call void @ext(i32 %gsz.z)
  call void @ext(i32 %warpSize)
  br label %exit

exit:
  ret void
}
