//=- DeviceCodeLinker.h - Simple linker for embedded device code -*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Linker for embedded device code.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_LINKER_DEVICE_CODE_LINKER_H
#define KITSUNE_LINKER_DEVICE_CODE_LINKER_H

#include "kitsune/Core/Tapir.h"
#include "kitsune/Object/EmbDeviceCodeContext.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Object/Binary.h"
#include "llvm/Support/Error.h"

namespace llvm {

namespace object {
class Archive;
class MemoryBuffer;
class ObjectFile;
} // namespace object

class DeviceCodeLinker;

/// The result of linking embedded device code. The result will be an object
/// file with the linked device code embedded within it in a specific section.
/// The specific section depends on whether linking produced a fat binary or
/// a static archive.
class LinkedDeviceCode {
private:
  SmallVector<std::unique_ptr<MemoryBuffer>, 2> linked;

private:
  LinkedDeviceCode() = default;

  /// Add a memory buffer containing an linked device code. This may be a static
  /// archive or a fat binary.
  void add(std::unique_ptr<MemoryBuffer> archive);

public:
  iterator begin() const { return iterator(linked.begin()); }
  iterator end() const { return iterator(linked.end()); }

  friend class DeviceCodeLinker;
};

/// Link embedded device code. This is intended to be used in LLD or other
/// kitsune-specific utilities. This is mainly intended to be a "helper" class
/// to manage the object files (which may be relocatable object files, static
/// archives or shared libraries) that are provided to tools such as kit-linkdc
/// or lld. The actual linking is likely to be carried out by an external
/// utility such as nvlink.
class DeviceCodeLinker {
private:
using NewArchiveMembers = SmallVector<object::NewArchiveMember, 8>

    private : EmbDeviceCodeContext ctx;

private:
  /// Construct a fat binary from the embedded device code generated by the cuda
  /// tapir target.
  ///
  /// TODO: Write more documentation about the behavior of this function.
  Result linkNVFatBinary();

  /// Construct a fat binary from the embedded device code generated by the hip
  /// tapir target.
  ///
  /// TODO: Write more documentation about the behavior of this function.
  Result linkAMDGPUFatBinary();

  Error addArchive(const EmbDeviceCode &devCode, NewArchiveMembers &members);
  Error addObject(const EmbDeviceCode &devCode, NewArchiveMembers &members);
  Error add(const EmbDeviceCode &devCode, NewArchiveMembers &members);
  Error add(MemoryBufferRef memBuf, NewArchiveMembers &members);

public:
  /// Add a buffer that may contain embedded device code. The buffer must be a
  /// relocatable object file or a static archive.
  Expected<unsigned> add(MemoryBufferRef memBuf);

  /// Link the embedded device code found in the object files that have been
  /// seen so far. Zero or more values will be returned - each containing the
  /// result of linking embedded device code generated by a specific tapir
  /// target. Each of the values will be a static archive.
  ///
  /// This does not behave in the same way as an actual linker. Roughly, this
  /// is implemented as follows:
  ///
  ///   Every input file is processed exactly once, even if it is added to the
  ///   linker more than once.
  ///
  ///     - If the input is an object file, the embedded device code is
  ///       extracted as an object file.
  ///
  ///     - If the input is a shared object, the embedded bitcode will be a
  ///       static archive. This static archive will be extracted and treated
  ///       as if it were explicitly added to the linker.
  ///
  ///     - If the input is a static archive, all members of the archive must be
  ///       device code object files. All of these will be extracted.
  ///
  ///   While extracting the object files, we ensure that the extracted files
  ///   have unique file names. Once all the inputs have been processed, the
  ///   extracted object files are combined into a single static archive.
  ///
  Expected<LinkedDeviceCode> linkStatic();

  /// Link the embedded device code found in the object files that have been
  /// seen so far and construct a fat binary for the device. Zero or more values
  /// will be returned - each containing the result of linking embedded device
  /// code generated by a specific tapir target.
  ///
  /// This will usually call an external utility to perform the actual link
  /// - for instance when linking device code generated by the cuda tapir
  /// target, nvlink performs the actual link. These external tools may have
  /// some limitations, so the behavior of this function is actually dependent
  /// on the capabilities of the external linker being used. See the
  /// documentation of the link*FatBinary functions for device-specific linking
  /// behavior. Currently, only linkNVFatBinary and linkAMDFatBinary have been
  /// implemented.
  Expected<LinkedDeviceCode> linkFatBinary();
};

} // namespace llvm

#endif // KITSUNE_LINKER_DEVICE_CODE_LINKER_H
