//=- DeviceCodeLinker.h - Simple linker for embedded device code -*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Linker for embedded device code.
//
//===----------------------------------------------------------------------===//

#ifndef KITSUNE_LINKER_DEVICE_CODE_LINKER_H
#define KITSUNE_LINKER_DEVICE_CODE_LINKER_H

#include "kitsune/Core/Tapir.h"
#include "kitsune/Object/EmbDeviceCodeContext.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/Object/Binary.h"
#include "llvm/Support/Error.h"
#include "llvm/TargetParser/Host.h"

namespace llvm {

class DeviceCodeLinker;

// /// The result of linking embedded device code. The result will be several
// host
// /// object files, each with the linked device code embedded within it in a
// /// specific section. The section in which the linked code is embedded
// depends
// /// on whether linking produced a fat binary or a static archive.
// class LinkedDeviceCode {
// private:
//   SmallVector<object::OwningBinary<object::ObjectFile>, 2> linked;

// public:
//   using iterator = typename decltype(linked)::const_iterator;

// private:
//   LinkedDeviceCode() = default;

//   /// Add a memory buffer containing an linked device code. This may be a
//   static
//   /// archive or a fat binary.
//   void add(object::OwningBinary<object::ObjectFile> archive);

// public:
//   iterator begin() const { return linked.begin(); }
//   iterator end() const { return linked.end(); }
//   size_t size() const { return linked.size(); }
//   bool empty() const { return linked.empty(); }

//   friend class DeviceCodeLinker;
// };

/// Link embedded device code. This is intended to be used in LLD or other
/// kitsune-specific utilities. This is mainly intended to be a "helper" class
/// to manage the object files (which may be relocatable object files, static
/// archives or shared libraries) that are provided to tools such as kit-linkdc
/// or lld. The actual linking is likely to be carried out by an external
/// utility such as nvlink.
class DeviceCodeLinker {
public:
  enum Mode {
    // Link the embedded device code into a static archive.
    Static,

    // Link the embedded device code into a fat binary.
    FatBin,
  };

private:
  EmbDeviceCodeContext ctx;

private:
  /// Construct a fat binary from the embedded device code generated by the cuda
  /// tapir target.
  ///
  /// TODO: Write more documentation about the behavior of this function.
  Expected<object::OwningBinary<object::ObjectFile>> linkNVFatBinary();

  /// Construct a fat binary from the embedded device code generated by the hip
  /// tapir target.
  ///
  /// TODO: Write more documentation about the behavior of this function.
  Expected<object::OwningBinary<object::ObjectFile>> linkAMDGPUFatBinary();

  /// Link the embedded device code found in the binary files that have been
  /// seen so far. The result object will contain zero or more objects, each
  /// of which contains the linked result embedded within it.
  ///
  /// This does not behave in the same way as an actual linker. Roughly, this
  /// is implemented as follows:
  ///
  ///   Every input file is processed exactly once, even if it is added to the
  ///   linker more than once.
  ///
  ///   Any input static archives are not treated lazily. Rather, they are
  ///   treated as if --whole-archive were passed to the linker i.e. all of the
  ///   contents of the archive will be copied over into the result.
  ///
  Expected<object::OwningBinary<object::ObjectFile>>
  linkStatic(StringRef triple);

  /// Link the embedded device code found in the object files that have been
  /// seen so far and construct a fat binary for the device. Zero or more values
  /// will be returned - each containing the result of linking embedded device
  /// code generated by a specific tapir target.
  ///
  /// This will usually call an external utility to perform the actual link
  /// - for instance when linking device code generated by the cuda tapir
  /// target, nvlink performs the actual link. These external tools may have
  /// some limitations, so the behavior of this function is actually dependent
  /// on the capabilities of the external linker being used. See the
  /// documentation of the link*FatBinary functions for device-specific linking
  /// behavior. Currently, only linkNVFatBinary and linkAMDFatBinary have been
  /// implemented.
  Expected<object::OwningBinary<object::ObjectFile>>
  linkFatBinary(StringRef triple);

public:
  /// Add a buffer that may contain embedded device code. The buffer must be a
  /// relocatable object file or a static archive.
  Expected<unsigned> add(MemoryBufferRef memBuf);

  /// Linked the embedded device code seen so far. \ref triple is the host
  /// triple.
  Expected<object::OwningBinary<object::ObjectFile>>
  link(Mode mode, StringRef triple = sys::getDefaultTargetTriple());
};

} // namespace llvm

#endif // KITSUNE_LINKER_DEVICE_CODE_LINKER_H
