//==- CodeGenFatBinaries.cpp - Generate fat binaries from embedded bitcode -==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into fat binaries.
//
//===----------------------------------------------------------------------===//

#include "llvm/CodeGen/CodeGenFatBinaries.h"
#include "CodeGenFatBinariesImpl.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/TapirTargetAnalysis.h"
#include "llvm/Frontend/Tapir/TapirTargetOptions.h"
#include "llvm/IR/KitsuneMetadata.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Transforms/Utils/KitsuneUtils.h"

using namespace llvm;

#define DEBUG_TYPE "codegen-fat-binaries"

static cl::opt<bool>
    clKeepFiles("cgfb-keep-files", cl::init(false), cl::Hidden,
                cl::desc("Do not delete intermediate files created during "
                         "generation of the fat binaries"));

namespace {

/// Implementation class to compile the embedded bitcode to fat binaries.
class CodeGenFatBinaries {
private:
  /// A pair of global variables, one containing the embedded bitcode, the other
  /// containing the fat binary.
  struct GlobalsBCFB {
    GlobalVariable *bc = nullptr;
    GlobalVariable *fb = nullptr;
  };

  using MaybeGlobalsBCFB = std::optional<GlobalsBCFB>;

private:
  const TapirTargetOptions &ttOpts;

private:
  /// Get a pair of global variables - the first is the one containing the
  /// embedded bitcode generated by the given tapir target, the second is the
  /// one containing the fat binary, also generated by the same tapir target.
  /// There should be exactly one global variable of each kind in the module.
  MaybeGlobalsBCFB getGlobalsBCFB(Module &m, TapirTargetID tt) const {
    GlobalsBCFB res;
    for (GlobalVariable &g : m.globals()) {
      if (hasKitsuneBCMD(g, tt))
        res.bc = &g;
      else if (hasKitsuneFBMD(g, tt))
        res.fb = &g;
    }

    if (res.bc and res.fb)
      return res;
    else if (!res.bc and !res.fb)
      return std::nullopt;

    llvm_unreachable("Global variables with embedded bitcode and fat binary "
                     "must both exist or neither must");
  }

public:
  CodeGenFatBinaries(const TapirTargetOptions &ttOpts) : ttOpts(ttOpts) {}

  bool run(Module &m) {
    bool changed = false;

    if (MaybeGlobalsBCFB r = getGlobalsBCFB(m, TapirTargetID::Cuda)) {
      detail::cgFatBinaryCuda(*r->fb, *r->bc, ttOpts, clKeepFiles);
      r->bc->eraseFromParent();
      changed |= true;
    }

    if (MaybeGlobalsBCFB r = getGlobalsBCFB(m, TapirTargetID::Hip)) {
      detail::cgFatBinaryHip(*r->fb, *r->bc, ttOpts, clKeepFiles);
      r->bc->eraseFromParent();
      changed |= true;
    }

    return changed;
  }
};

} // namespace

void llvm::detail::embedFatBinary(ToolOutputFile &fatbinFile,
                                  GlobalVariable &g) {
  ErrorOr<std::unique_ptr<MemoryBuffer>> bufOrErr =
      MemoryBuffer::getFile(fatbinFile.getFilename());
  if (std::error_code ec = bufOrErr.getError()) {
    report_fatal_error(StringRef(llvm::join_items(
        " ", "failed to load fat binary image:", ec.message())));
  }

  std::unique_ptr<MemoryBuffer> fb = std::move(bufOrErr.get());
  resetEmbeddedFB(*fb, g);
}

/// Legacy pass to compile the embedded bitcode to fat binaries.
class CodeGenFatBinariesLegacyPass : public ModulePass {
public:
  CodeGenFatBinariesLegacyPass() : ModulePass(ID) {
    initializeCodeGenFatBinariesLegacyPassPass(
        *PassRegistry::getPassRegistry());
  }

  StringRef getPassName() const override {
    return "Generate Kitsune fat binaries";
  }

  void getAnalysisUsage(AnalysisUsage &au) const override {
    au.addRequired<TapirTargetAnalysisWrapperPass>();
  }

  bool runOnModule(Module &m) override;

public:
  static char ID;
};

char CodeGenFatBinariesLegacyPass::ID = 0;
INITIALIZE_PASS_BEGIN(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                      "Compile Kitsune fat binaries", false, false)
INITIALIZE_PASS_DEPENDENCY(TapirTargetAnalysisWrapperPass)
INITIALIZE_PASS_END(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                    "Compile Kitsune fat binaries", false, false)

ModulePass *llvm::createCodeGenFatBinariesLegacyPass() {
  return new CodeGenFatBinariesLegacyPass();
}

bool CodeGenFatBinariesLegacyPass::runOnModule(Module &m) {
  TapirTargetInfo tgi =
      getAnalysis<TapirTargetAnalysisWrapperPass>().getResult();
  if (not tgi.hasID())
    return false;

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  bool changed = CodeGenFatBinaries(ttOpts).run(m);

  return changed;
}

PreservedAnalyses CodeGenFatBinariesPass::run(Module &m,
                                              ModuleAnalysisManager &mam) {
  // If a primary tapir target ID has not been set, then tapir lowering was not
  // enabled and there is nothing to be done.
  const TapirTargetInfo &tgi = mam.getResult<TapirTargetAnalysis>(m);
  if (not tgi.hasID())
    return PreservedAnalyses::all();

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  CodeGenFatBinaries(ttOpts).run(m);

  // This does not invalidate any analyses, even if any fat binaries were
  // generated since only global variables will have been modified.
  return PreservedAnalyses::all();
}
