//==- CodeGenKitsuneFatBinary.cpp - Generate fat binaries from GPU bitcode -==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into fat binaries.
//
//===----------------------------------------------------------------------===//

#include "llvm/CodeGen/CodeGenKitsuneFatBinaries.h"
#include "kitsune/Config/config.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/TapirTargetAnalysis.h"
#include "llvm/Frontend/Tapir/OptLevelUtils.h"
#include "llvm/Frontend/Tapir/TapirTargetOptions.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/KitsuneMetadata.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/KitsuneUtils.h"

using namespace llvm;

#define DEBUG_TYPE "codegen-fat-binaries"

// Override the optimization level used by ptxas when generating GPU code. If
// this is not explicitly set, it will use the optimization level set in the
// tapir target options, which is usually whatever was passed to the frontend.
static cl::opt<int> clPtxasOptLevel(
    "cuabi-ptxas-opt-level", cl::init(-1), cl::Hidden,
    cl::desc("Set the optimization level for ptxas. Must be 0, 1, 2 or 3"));

static cl::opt<bool>
    clKeepFiles("cuabi-keep-files", cl::init(false), cl::Hidden,
                cl::desc("Do not delete intermediate files created during "
                         "generation of the fat binaries"));

namespace {

static void embedFatBinary(ToolOutputFile &fatbinFile, GlobalVariable &g) {
  // Allocate a buffer to store the fat binary image in. We will then codegen
  // it into the host-side module.
  ErrorOr<std::unique_ptr<MemoryBuffer>> bufOrErr =
      MemoryBuffer::getFile(fatbinFile.getFilename());
  if (std::error_code ec = bufOrErr.getError()) {
    report_fatal_error(StringRef(llvm::join_items(
        " ", "failed to load fat binary image:", ec.message())));
  }

  std::unique_ptr<MemoryBuffer> fb = std::move(bufOrErr.get());
  resetEmbeddedFB(*fb, g);
}

/// Helper class to generate code for NVIDIA GPU's from embedded bitcode.
class CodeGenCudaFB {
private:
  const TapirTargetOptions &ttOpts;

private:
  std::unique_ptr<ToolOutputFile> generatePTX(Module &km) {
    LLVM_DEBUG(dbgs() << "\t- generating PTX...\n");

    // Take the intermediate form code in the kernel module and generate a PTX
    // file. The PTX file will be named the same as the original input source
    // module (M) with the extension changed to PTX.
    SmallString<1024> ptxFilename;
    std::string model =
        llvm::join_items("_", "kitcu", "%%-%%-%%", km.getName());
    sys::fs::createUniquePath(model.c_str(), ptxFilename, true);
    sys::path::replace_extension(ptxFilename, ".ptx");
    LLVM_DEBUG(dbgs() << "\t- PTX file: '" << ptxFilename << "'.\n");

    std::error_code ec;
    std::unique_ptr<ToolOutputFile> ptxFile = std::make_unique<ToolOutputFile>(
        ptxFilename, ec, sys::fs::OpenFlags::OF_None);
    ptxFile->keep();

    TargetOptions targetOpts;
    targetOpts.AllowFPOpFusion = ttOpts.getFPOpFusionMode();

    // TODO: Do we really need a large code model here?
    CodeModel::Model codeModel = CodeModel::Large;
    Reloc::Model relocModel = Reloc::PIC_;
    CodeGenOptLevel optLevel = mapToCodeGenOptLevel(ttOpts.getOptLevel());

    // The build system should have ensured that the NVPTX target is available.
    std::string err;
    Triple triple(km.getTargetTriple());
    const Target *target = TargetRegistry::lookupTarget("", triple, err);
    assert(target && "Unable to find registered PTX target");

    TargetMachine *tm =
        target->createTargetMachine(km.getTargetTriple(), ttOpts.getCudaArch(),
                                    ttOpts.getCudaTargetFeatures(), targetOpts,
                                    relocModel, codeModel, optLevel);

    // Setup the passes and request that the output goes to the specified PTX
    // file.
    legacy::PassManager passMgr;
    if (tm->addPassesToEmitFile(passMgr, ptxFile->os(),
                                /*DwoOut=*/nullptr,
                                CodeGenFileType::AssemblyFile,
                                /*DisableVerify=*/false)) {
      report_fatal_error("PTX generation failed");
    }
    passMgr.run(km);

    LLVM_DEBUG(dbgs() << "PTX generation complete.\n\n");
    return ptxFile;
  }

  std::unique_ptr<ToolOutputFile> assemblePTX(ToolOutputFile &ptxFile) {
    std::string ptxFilename = ptxFile.getFilename().str();
    LLVM_DEBUG(dbgs() << "\t- assembling PTX file '" << ptxFilename << "'.\n");

    StringRef ptxas = KITSUNE_CUDA_PTXAS;
    SmallString<255> asmFilename(ptxFilename);
    sys::path::replace_extension(asmFilename, ".s");

    std::error_code ec;
    std::unique_ptr<ToolOutputFile> asmFile = std::make_unique<ToolOutputFile>(
        asmFilename, ec, sys::fs::OpenFlags::OF_None);

    // Build the command line for ptxas...  There are some target specific
    // options that we support to configure some specifics here.  See the 'opt'
    // entries near the top of this file. These can be passed to the transform
    // via '-mllvm <cuabi-option>'.
    std::vector<StringRef> args;
    args.push_back(ptxas);

    // TODO: Do we need/want to add support for generating relocatable code?

    // The gpu architecture (e.g., sm_86)
    args.push_back("--gpu-name");
    args.push_back(ttOpts.getCudaArch());

    // Warn if we spill registers and provide feedback on kernel stats.
    args.push_back("--warn-on-spills");

    if (ttOpts.getTapirVerbose())
      args.push_back("--verbose");

    // If the ptxas optimization level has not been explicitly overridden, use
    // the optimization level set by the frontend.
    int ptxasOptLevel = clPtxasOptLevel;
    if (ptxasOptLevel == -1)
      ptxasOptLevel = ttOpts.getOptLevel().getSpeedupLevel();

    std::string optLevel = std::to_string(ptxasOptLevel);
    args.push_back("--opt-level");
    args.push_back(optLevel);

    std::string scodeFilename = asmFile->getFilename().str();
    args.push_back("--output-file");
    args.push_back(scodeFilename);

    args.push_back(ptxFilename);

    // // Build argv for exec'ing ptxas...
    // SmallVector<const char *, 128> PTXASArgv;
    // PTXASArgv.append(args.begin(), args.end());
    // PTXASArgv.push_back(nullptr);

    // if (ttOpts.getTapirVerbose())
    //   tapir::renderCommandLine(args, errs());
    LLVM_DEBUG({
      dbgs() << "\t- ptxas command line:\n";
      unsigned i = 0;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });

    std::string errMsg;
    if (sys::ExecuteAndWait(/*Program=*/ptxas,
                            /*Args=*/args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*(0 => unlimited) SecondsToWait=*/0,
                            /*(0 => unlimited) MemoryLimit=*/0,
                            /*ErrMsg=*/&errMsg))
      report_fatal_error(
          StringRef(llvm::join_items(" ", "'ptxas' failure:", errMsg)));

    asmFile->keep();
    return asmFile;
  }

  std::unique_ptr<ToolOutputFile> createFatBinary(ToolOutputFile &asmFile) {
    SmallString<255> fatbinFilename(asmFile.getFilename());
    sys::path::replace_extension(fatbinFilename, ".cufatbin");
    LLVM_DEBUG(dbgs() << "\t- generatng fatbinary image file '"
                      << fatbinFilename << "'.\n");

    std::error_code ec;
    std::unique_ptr<ToolOutputFile> fatbinFile =
        std::make_unique<ToolOutputFile>(fatbinFilename, ec,
                                         sys::fs::OpenFlags::OF_None);

    StringRef fatbin = KITSUNE_CUDA_FATBINARY;
    std::vector<StringRef> args;
    args.push_back(fatbin);
    args.push_back("--64");
    args.push_back("--create");
    args.push_back(fatbinFilename);

    std::string imgArgs =
        llvm::join_items("", "--image=profile=", ttOpts.getCudaArch(),
                         ",file=", asmFile.getFilename());
    args.push_back(imgArgs);

    // FIXME: This code looks like it is broken.
    // std::list<std::string> PTXFilesArgList;
    // if (EmbedPTXInFatbinaries) {
    //   StringRef varch = ttOpts.getCudaVirtArch();
    //   if (varch == "unknown")
    //     report_fatal_error("cuabi: no virtual target for given gpuarch '" +
    //                        TTO.getCudaArch() + "'!");

    //   std::string PTXFixedArgStr =
    //       ("--image=profile=" + VArchStr + ",file=").str();
    //   for (auto &PTXFile : ModulePTXFileList) {
    //     std::string arg = PTXFixedArgStr + PTXFile;
    //     std::list<std::string>::const_iterator it;
    //     it = PTXFilesArgList.emplace(PTXFilesArgList.end(), std::move(arg));
    //     args.push_back(it->c_str());
    //   }
    // }

    // args.push_back(nullptr);

    // SmallVector<const char *, 128> FatbinaryArgv;
    // FatbinaryArgv.append(args.begin(), args.end());
    // std::vector<StringRef> FatbinaryArgs =
    //     toStringRefArray(FatbinaryArgv.data());

    // if (TTO.getTapirVerbose())
    //   tapir::renderCommandLine(FatbinaryArgs, errs());
    LLVM_DEBUG({
      dbgs() << "\tfatbinary command line:\n";
      unsigned i = 0;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });

    std::string errMsg;
    if (sys::ExecuteAndWait(/*Program=*/fatbin,
                            /*Args=*/args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*(0 => unlimited) SecondsToWait=*/0,
                            /*(0 => unlimited) MemoryLimit=*/0,
                            /*ErrMsg=*/&errMsg)) {
      // TODO: Need to check what sort of actual state 'fatbinary' returns to
      // the environment -- currently assuming it matches standard practices
      report_fatal_error(
          StringRef(llvm::join_items(" ", "'fatbinary' failure:", errMsg)));
    }

    // if (EmbedPTXInFatbinaries) {
    //   std::list<std::string>::iterator it = PTXFilesArgList.begin();
    //   while (it != PTXFilesArgList.end()) {
    //     PTXFilesArgList.erase(it++);
    //   }
    // }

    // TODO: Not sure we need to force 'keep' here as we return the output file
    // but will keep it here for now just to play it safe.
    fatbinFile->keep();
    return fatbinFile;
  }

public:
  CodeGenCudaFB(const TapirTargetOptions &ttOpts) : ttOpts(ttOpts) {}

  bool run(GlobalVariable &gbc, GlobalVariable &gfb) {
    std::unique_ptr<Module> km = parseEmbeddedBC(gbc);

    std::unique_ptr<ToolOutputFile> ptxFile = generatePTX(*km);
    std::unique_ptr<ToolOutputFile> asmFile = assemblePTX(*ptxFile);
    std::unique_ptr<ToolOutputFile> fatbinFile = createFatBinary(*asmFile);
    embedFatBinary(*fatbinFile, gfb);

    if (not clKeepFiles) {
      sys::fs::remove(ptxFile->getFilename());
      sys::fs::remove(asmFile->getFilename());
      sys::fs::remove(fatbinFile->getFilename());
    }
    return true;
  }
};

/// Helper class to generate code for NVIDIA GPU's from embedded bitcode.
class CodeGenHipFB {
private:
  const TapirTargetOptions &ttOpts;

public:
  CodeGenHipFB(const TapirTargetOptions &ttOpts) : ttOpts(ttOpts) {}

  bool run(GlobalVariable &gbc, GlobalVariable &gfb) {
    // TODO: Implement this.
    std::unique_ptr<Module> km = parseEmbeddedBC(gbc);

    std::unique_ptr<ToolOutputFile> fbFile = nullptr;
    embedFatBinary(*fbFile, gfb);

    llvm_unreachable("Not implemented");
    // if (not clKeepFiles) {
    //   // sys::fs::remove(ptxFile->getFilename());
    //   // sys::fs::remove(asmFile->getFilename());
    //   sys::fs::remove(fbFile->getFilename());
    // }
    return false;
  }
};

/// Implementation class to compile the embedded bitcode to fat binaries.
class CodeGenFatBinaries {
private:
  /// A pair of global variables, one containing the embedded bitcode, the other
  /// containing the fat binary.
  struct GlobalsBCFB {
    GlobalVariable *bc = nullptr;
    GlobalVariable *fb = nullptr;
  };

  using MaybeGlobalsBCFB = std::optional<GlobalsBCFB>;

private:
  const TapirTargetOptions &ttOpts;

private:
  /// Get a pair of global variables - the first is the one containing the
  /// embedded bitcode generated by the given tapir target, the second is the
  /// one containing the fat binary, also generated by the same tapir target.
  /// There should be exactly one global variable of each kind in the module.
  MaybeGlobalsBCFB getGlobalsBCFB(Module &m, TapirTargetID tt) const {
    GlobalsBCFB res;
    for (GlobalVariable &g : m.globals()) {
      if (hasKitsuneBCMD(g, tt))
        res.bc = &g;
      else if (hasKitsuneFBMD(g, tt))
        res.fb = &g;
    }

    if (res.bc and res.fb)
      return res;
    else if (!res.bc and !res.fb)
      return std::nullopt;

    llvm_unreachable("Global variables with embedded bitcode and fat binary "
                     "must both exist or neither must");
  }

public:
  CodeGenFatBinaries(const TapirTargetOptions &ttOpts) : ttOpts(ttOpts) {}

  bool run(Module &m) {
    bool changed = false;

    if (MaybeGlobalsBCFB r = getGlobalsBCFB(m, TapirTargetID::Cuda))
      changed |= CodeGenCudaFB(ttOpts).run(*r->bc, *r->fb);

    if (MaybeGlobalsBCFB r = getGlobalsBCFB(m, TapirTargetID::Hip))
      changed |= CodeGenHipFB(ttOpts).run(*r->bc, *r->fb);

    return changed;
  }
};

} // namespace

/// Legacy pass to compile the embedded bitcode to fat binaries.
class CodeGenKitsuneFatBinariesLegacyPass : public ModulePass {
public:
  CodeGenKitsuneFatBinariesLegacyPass() : ModulePass(ID) {
    initializeCodeGenKitsuneFatBinariesLegacyPassPass(
        *PassRegistry::getPassRegistry());
  }

  StringRef getPassName() const override {
    return "Generate Kitsune fat binaries";
  }

  void getAnalysisUsage(AnalysisUsage &au) const override {
    au.addRequired<TapirTargetAnalysisWrapperPass>();
  }

  bool runOnModule(Module &m) override;

public:
  static char ID;
};

char CodeGenKitsuneFatBinariesLegacyPass::ID = 0;
INITIALIZE_PASS_BEGIN(CodeGenKitsuneFatBinariesLegacyPass, DEBUG_TYPE,
                      "Compile Kitsune fat binaries", false, false)
INITIALIZE_PASS_DEPENDENCY(TapirTargetAnalysisWrapperPass)
INITIALIZE_PASS_END(CodeGenKitsuneFatBinariesLegacyPass, DEBUG_TYPE,
                    "Compile Kitsune fat binaries", false, false)

ModulePass *llvm::createCodeGenKitsuneFatBinariesLegacyPass() {
  return new CodeGenKitsuneFatBinariesLegacyPass();
}

bool CodeGenKitsuneFatBinariesLegacyPass::runOnModule(Module &m) {
  TapirTargetInfo tgi =
      getAnalysis<TapirTargetAnalysisWrapperPass>().getResult();
  if (not tgi.hasID())
    return false;

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  bool changed = CodeGenFatBinaries(ttOpts).run(m);

  return changed;
}

PreservedAnalyses
CodeGenKitsuneFatBinariesPass::run(Module &m, ModuleAnalysisManager &mam) {
  // If a primary tapir target ID has not been set, then tapir lowering was not
  // enabled and there is nothing to be done.
  const TapirTargetInfo &tgi = mam.getResult<TapirTargetAnalysis>(m);
  if (not tgi.hasID())
    return PreservedAnalyses::all();

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  CodeGenFatBinaries(ttOpts).run(m);

  // This does not invalidate any analyses, even if any fat binaries were
  // generated since only global variables will have been modified.
  return PreservedAnalyses::all();
}
