//===- OptimizeEmbBC.cpp - Optimize embedded bitcode -----------*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Run the standard sequence of optimization passes on the embedded bitcode.
//
//===----------------------------------------------------------------------===//

#include "llvm/Transforms/Kitsune/OptimizeEmbBC.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/TapirTargetAnalysis.h"
#include "llvm/Frontend/Tapir/OptLevelUtils.h"
#include "llvm/Frontend/Tapir/TapirTargetOptions.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/KitsuneMetadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Tapir/LoweringUtils.h"
#include "llvm/Transforms/Utils/KitsuneUtils.h"

#include <vector>

#define DEBUG_TYPE "optimize-emb-bc"

using namespace llvm;

// Set a specific optimization level for the embedded bitcode. If this has not
// been set explicitly, the optimization level from the tapir target options
// will be used. This is typically set by the frontend.
//
// This is primarily useful for exploring various details of levels between
// those operating on the Tapir IR and those after the transformation to
// GPU-friendly LLVM IR.
static cl::opt<int>
    clOptLevel("emb-opt-level", cl::init(-1), cl::Hidden,
               cl::desc("Specify the embedded bitcode kernel optimization "
                        "level. Must be 0, 1, 2 or 3"));

namespace {

/// Optimize the embedded bitcode. This runs the standard sequence of
/// optimization passes on it.
class OptimizeBC {
private:
  const TapirTargetOptions &ttOpts;

private:
  /// The tapir targets may generate multiple kernel modules that must be
  /// combined into a single module per GPU architecture. This will combine
  /// these into a single module and serialize it to a single embedded bitcode
  /// chunk. The individual bitcode modules that were combined will be removed.
  bool combineBitcode(Module &) {
    // This is currently not implemented because the tapir targets generate a
    // single kernel module containing everything that will eventually be
    // compiled to GPU code.
    return false;
  }

  /// Run the standard sequence of optimization passes, based on the
  /// optimization level, on the embedded bitcode module.
  bool optimize(Module &embM, const PipelineTuningOptions &pto,
                OptimizationLevel optLevel) {
    // The analysis managers must be declared in this order so that they are
    // destroyed in the correct order due to inter-analysis-manager references
    LoopAnalysisManager lam;
    FunctionAnalysisManager fam;
    CGSCCAnalysisManager cgam;
    ModuleAnalysisManager mam;

    PassBuilder pb(nullptr, pto);
    pb.registerModuleAnalyses(mam);
    pb.registerCGSCCAnalyses(cgam);
    pb.registerFunctionAnalyses(fam);
    pb.registerLoopAnalyses(lam);
    pb.crossRegisterProxies(lam, fam, cgam, mam);

    LLVM_DEBUG(dbgs() << "\t\t* module: " << embM.getName() << "\n");

    ModulePassManager mpm = pb.buildPerModuleDefaultPipeline(optLevel);
    mpm.addPass(VerifierPass());
    mpm.run(embM, mam);

    LLVM_DEBUG(dbgs() << "\t\tpasses complete.\n");

    LLVM_DEBUG(
        saveModuleToFile(&embM, join_items("", embM.getName(), ".kmod.final")));
    return true;
  }

  /// Optimize the embedded bitcode generated by the cuda tapir target.
  bool optimizeCuda(Module &embM, OptimizationLevel optLevel) {
    unsigned speedupLevel = optLevel.getSpeedupLevel();
    PipelineTuningOptions pto;
    pto.LoopUnrolling = speedupLevel > 2;
    pto.LoopInterleaving = speedupLevel > 2;
    pto.LoopStripmine = speedupLevel > 2;
    pto.LoopVectorization = false;
    pto.SLPVectorization = false;

    return optimize(embM, pto, optLevel);
  }

  /// Optimize the embedded bitcode generated by the hip tapir target.
  bool optimizeHip(Module &embM, OptimizationLevel optLevel) {
    unsigned speedupLevel = optLevel.getSpeedupLevel();
    PipelineTuningOptions pto;
    pto.LoopUnrolling = speedupLevel > 2;
    pto.LoopInterleaving = speedupLevel > 2;
    pto.LoopStripmine = speedupLevel > 2;
    pto.LoopVectorization = false;
    pto.SLPVectorization = false;

    return optimize(embM, pto, optLevel);
  }

public:
  OptimizeBC(const TapirTargetOptions &ttOpts) : ttOpts(ttOpts) {}

  bool run(Module &m) {
    bool changed = false;

    // If the tapir targets generated multiple embedded bitcode modules, combine
    // them into one per architecture.
    changed |= combineBitcode(m);

    // If the optimization level has been overridden on the command line,
    // prefer that, otherwise, use the optimization level from the tapir target
    // options.
    OptimizationLevel optLevel = ttOpts.getOptLevel();
    if (clOptLevel != -1)
      optLevel = mapToOptimizationLevel(clOptLevel);

    // If the speedup level is 0, no optimization passes are run.
    if (not optLevel.getSpeedupLevel())
      return changed;

    // Collect the global variables containing embedded bitcode. We have to do
    // this in two phases because when resetting the embedded bitcode
    // post-optimization, the globals will be removed and replaced with a new
    // global.
    std::vector<GlobalVariable *> gs;
    for (GlobalVariable &g : m.globals())
      if (hasKitsuneBCMD(g))
        gs.push_back(&g);

    for (GlobalVariable *g : gs) {
      std::unique_ptr<Module> embM = parseEmbeddedBC(*g);
      if (hasKitsuneBCMD(*g, TapirTargetID::Cuda))
        changed |= optimizeCuda(*embM, optLevel);
      else if (hasKitsuneBCMD(*g, TapirTargetID::Hip))
        changed |= optimizeHip(*embM, optLevel);
      else
        llvm_unreachable("Unexpected tapir target on embedded bitcode");
      resetEmbeddedBC(*embM, *g);
    }

    return changed;
  }
};

} // namespace

namespace llvm {

PreservedAnalyses OptimizeEmbBCPass::run(Module &m,
                                         ModuleAnalysisManager &mam) {
  // If no primary tapir target has been set, there will be nothing to do, so
  // bail out immediately.
  const TapirTargetInfo &tgi = mam.getResult<TapirTargetAnalysis>(m);
  if (not tgi.hasID())
    return PreservedAnalyses::all();

  const TapirTargetOptions &tto = tgi.getOptions();
  OptimizeBC(tto).run(m);

  // This will preserve all analyses because the only thing that will have
  // changed are the types and initializers of one or more global variables.
  return PreservedAnalyses::all();
}

} // namespace llvm
