//===- kitqthr.cpp - Kitsune runtime targeting qthreads -------------------===//
//
// Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
// All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//  software was produced under U.S. Government contract
//  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//  is operated by Los Alamos National Security, LLC for the
//  U.S. Department of Energy. The U.S. Government has rights to use,
//  reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//  NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//  OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//  If software is modified to produce derivative works, such modified
//  software should be clearly marked, so as not to confuse it with
//  the version available from LANL.
//
//  Additionally, redistribution and use in source and binary forms,
//  with or without modification, are permitted provided that the
//  following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials provided
//      with the distribution.
//
//    * Neither the name of Los Alamos National Security, LLC, Los
//      Alamos National Laboratory, LANL, the U.S. Government, nor the
//      names of its contributors may be used to endorse or promote
//      products derived from this software without specific prior
//      written permission.
//
//  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//  SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//

#include "kitrt.h"

#include <qthread.h>
#include <qthread/qloop.h>

#include <algorithm>
#include <cstdarg>
#include <cstdint>
#include <cstdio>

/// TODO: Move this to a different file because this could be used as a common
/// utility function to display varying levels of status messages from other
/// runtimes as well.
static void log(const char *label, const char *category, const char *msg,
                va_list args) {
  // TODO: It would be nice if we could colorize the label.
  if (label)
    fprintf(stderr, "%s: ", label);
  if (category)
    fprintf(stderr, "%s: ", category);
  vfprintf(stderr, msg, args);
  fprintf(stderr, "\n");
}

/// Print an error message to stderr and terminate the process with an exit
/// code. \param msg may be a printf-compatible format string. In that case,
/// any optional arguments must be of the appropriate types.
[[noreturn]] static void fatal(const char *msg, ...) {
  va_list args;
  va_start(args, msg);
  log("kitqthr", "ERROR", msg, args);
  va_end(args);

  std::exit(EXIT_FAILURE);
}

/// Print a warning message to stderr. \param msg may be a printf-compatible
/// format string. In that case, any optional arguments must be of the
/// appropriate types.
static void warn(const char *msg, ...) {
  va_list args;
  va_start(args, msg);
  log("kitqthr", "WARNING", msg, args);
  va_end(args);
}

/// Display an informational message if verbose mode has been enabled.
/// \param msg may be a printf-compatible format string. In this case, any
/// optional arguments must be of the appropriate type.
static void message(const char *msg, ...) {
  if (__kitrt_verbose_mode()) {
    va_list args;
    va_start(args, msg);
    log("kitqthr", nullptr, msg, args);
    va_end(args);
  }
}

/// The function that is run on each thread. The last argument is a pointer to
/// a struct generated by the compiler where all the data needed by the
/// function is bundled together. start and end are the starts and ends of the
/// iteration space that must be split across the threads.
using KitQthrThrdFn = void (*)(const unsigned long start,
                               const unsigned long end, void *args);

/// Launch some number of threads each of which will execute some number of
/// iterations in the space [\ref start, \ref end). Terminates the program with
/// a fatal error if any thread could not be launched. This blocks until all
/// threads have completed.
///
/// \param f The function to execute on each thread
/// \param start The start index of the iteration space
/// \param end The value one greater than the last index of the iteration space
/// \param grainSize The grainSize
/// \param args A struct containing data to be passed to \param f
extern "C" void __kitqthr_launch(KitQthrThrdFn f, int64_t start, int64_t end,
                                 int64_t grainSize, void *args) {
  message("Launching");
  message("Iteration range: [%ld, %ld)", start, end);

  // TODO: In some cases, it may be beneficial to use qt_loop_balance() here
  // instead of qt_loop_balance_simple. We should run some tests to see if this
  // is ever the case.
  qt_loop_balance_simple(start, end, f, args);
}

/// Initialize kitsune's qthreads runtime as well as the actual qthreads
/// runtime.
extern "C" void __kitqthr_initialize(void) {
  // Initialize the components of kitsune's runtime that are shared by the
  // tapir-target-specific components.
  __kitrt_initialize();
  message("Initializing kitqthr runtime");

  qthread_initialize();

  message("Number of shepherds = %d", qthread_num_shepherds());
  message("Number of workers = %d", qthread_num_workers());
  message("Initialized runtime");
}

/// Finalize kitsune's qthreads runtime, as well as qthreads runtime.
extern "C" void __kitqthr_finalize(void) {
  message("Finalizing kitqthr runtime");

  qthread_finalize();

  message("Finalized runtime");
}
