//===- kitqthr.cpp - Kitsune runtime targeting qthreads -------------------===//
//
// Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
// All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//  software was produced under U.S. Government contract
//  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//  is operated by Los Alamos National Security, LLC for the
//  U.S. Department of Energy. The U.S. Government has rights to use,
//  reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//  NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//  OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//  If software is modified to produce derivative works, such modified
//  software should be clearly marked, so as not to confuse it with
//  the version available from LANL.
//
//  Additionally, redistribution and use in source and binary forms,
//  with or without modification, are permitted provided that the
//  following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials provided
//      with the distribution.
//
//    * Neither the name of Los Alamos National Security, LLC, Los
//      Alamos National Laboratory, LANL, the U.S. Government, nor the
//      names of its contributors may be used to endorse or promote
//      products derived from this software without specific prior
//      written permission.
//
//  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//  SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//

#include "kitrt.h"

#include <qthread.h>
#include <qthread/barrier.h>

#include <cstdint>
#include <cstdlib>
#include <vector>

#define LABEL "kitqthr"

namespace {

/// The function that is run on each thread. The last argument is a pointer to
/// a struct generated by the compiler where all the data needed by the
/// function is bundled together. start and end are iterations to be run on the
/// thread.
using KitQthrThrdFn = void (*)(uint64_t start, uint64_t end, void *args);

/// The arguments is passed to the thread launch function. This contains the
/// arguments to be passed to the "actual" thread function. It also contains the
/// barrier that must be entered once the actual thread function has finished
/// executing.
struct KitQthrThrdArgs {
  KitQthrThrdFn f;
  uint64_t start;
  uint64_t end;
  void *args;
  qt_barrier_t *barrier;
};

} // namespace

/// Get the number of parallel workers that are available. Generally, this
/// function should be used when this must be queried instead of calling
/// `qthread_num_workers()`.
static unsigned __kitqthr_num_threads() { return qthread_num_workers(); }

/// The function that is launched by each thread. This simply finds the "actual"
/// function that is to be run in \p thrdArgs and calls it. The arguments to the
/// actual function are also present in \p thrdArgs. Always returns 0.
static unsigned long kitqthrThrdLaunchFn(KitQthrThrdArgs *thrdArgs) {
  KitQthrThrdFn f = thrdArgs->f;
  int64_t start = thrdArgs->start;
  int64_t end = thrdArgs->end;
  void *args = thrdArgs->args;
  qt_barrier_t *barrier = thrdArgs->barrier;

  f(start, end, args);
  qt_barrier_enter(barrier);

  return 0;
}

/// Launch some number of threads each of which will execute some number of
/// iterations in the space [\ref start, \ref end). Terminates the program with
/// a fatal error if any thread could not be launched. This blocks until all
/// threads have completed.
///
/// \param f The function to execute on each thread
/// \param start The start index of the iteration space
/// \param end The value one greater than the last index of the iteration space
/// \param grainSize The grainSize
/// \param args A struct containing data to be passed to \p f
extern "C" void __kitqthr_launch(KitQthrThrdFn f, int64_t start, int64_t end,
                                 int64_t grainSize, void *args) {
  __kitrt_message(LABEL, "Launching multithreaded loop: [%ld, %ld)", start,
                  end);

  // This is the number of threads that *may* be launched. However, there may
  // not be enough for work for all threads, so the actual number of threads
  // that are launched may be smaller than this.
  const unsigned availThrds = __kitqthr_num_threads();
  __kitrt_message(LABEL, "Available threads: %d", availThrds);

  // On some systems, int64_t maps to long while on others it is long long.
  // Adding the literal to the call to std::max results in a compile time error
  // on one or another platform. Setting to a constant avoids the conditional
  // compilation directives that would other wise be needed here.
  constexpr int64_t one = 1;

  // Adding `availThrds - 1` handles the case where the range of iterations is
  // not an integer multiple of `availThrds`.
  const int64_t thrdSpan =
      std::max((end - start + availThrds - 1) / availThrds, one);
  __kitrt_message(LABEL, "Iterations per thread: %ld", thrdSpan);

  // The actual number of threads that are to be launched. Adding `thrdSpan - 1`
  // to `end` nicely deals with the case where the range of iterations is not an
  // integer multiple of thrdSpan. We could have used a conditional statement to
  // handle the two cases separately, but this is a fairly standard way of doing
  // such things.
  const int64_t numThrds = (end - start + thrdSpan - 1) / thrdSpan;
  __kitrt_message(LABEL, "Launching %ld threads", numThrds);
  assert(numThrds <= availThrds &&
         "Cannot launch more threads than the number that are available");

  // We need the main thread to block until all spawned threads finish. This is
  // implemented by setting up the barrier to block until it is entered by all
  // `n` spawned threads, as well as the main thread.
  qt_barrier_t *barrier = qt_barrier_create(numThrds + 1, REGION_BARRIER);
  if (!barrier)
    __kitrt_fatal(LABEL, "Could not create barrier");

  std::vector<KitQthrThrdArgs> thrds(numThrds);
  for (int64_t i = 0, beg = start; beg < end; beg += thrdSpan, ++i) {
    KitQthrThrdArgs &thrdArgs = thrds[i];
    thrdArgs.f = f;
    thrdArgs.start = beg;
    thrdArgs.end = std::min(beg + thrdSpan, end);
    thrdArgs.args = args;
    thrdArgs.barrier = barrier;

    __kitrt_message(LABEL, "Fork thread %d: [%ld, %ld)", i, thrdArgs.start,
                    thrdArgs.end);
    if (qthread_fork((qthread_f)kitqthrThrdLaunchFn, &thrdArgs, nullptr))
      __kitrt_fatal(LABEL, "Could not fork thread");
  }

  // The main thread must also enter the barrier. Once the main thread has
  // entered, it will block until all spawned threads enter before continuing.
  qt_barrier_enter(barrier);
  qt_barrier_destroy(barrier);

  __kitrt_message(LABEL, "Finished multithreaded loop");
}

/// The number of partial reductions to perform in parallel.
///
/// \param n The trip count of the parallel loop in containing a reduction
extern "C" int64_t __kitqthr_reduce_num_partials(int64_t n) {
  __kitrt_message(LABEL, "Calculating number of partial reductions");

  // There might be something smarter that can be done once we support a proper
  // reduction tree, but since we only support a reduction tree of depth 1, this
  // will do.
  unsigned numPartials = __kitqthr_num_threads();

  __kitrt_message(LABEL, "Number of partial reductions: %d", numPartials);

  return numPartials;
}

/// Initialize kitsune's qthreads runtime as well as the actual qthreads
/// runtime.
extern "C" void __kitqthr_initialize(void) {
  // Initialize the components of kitsune's runtime that are shared by the
  // tapir-target-specific components.
  __kitrt_initialize();
  __kitrt_message(LABEL, "Initializing Kitsune runtime (qthreads)");

  if (__kitrt_num_threads_from_env()) {
    // It seems that, by default, one shepherd is used, so if we are setting
    // the number of workers, force the number of shepherds as well.
    const char *s = getenv(__kitrt_envname_num_threads);
    __kitrt_message(LABEL, "Setting QT_NUM_SHEPHERDS=1");
    __kitrt_set_env("QT_NUM_SHEPHERDS", "1");
    __kitrt_message(LABEL, "Setting QT_NUM_WORKERS_PER_SHEPHERD=%s", s);
    __kitrt_set_env("QT_NUM_WORKERS_PER_SHEPHERD", s);
  }

  __kitrt_message(LABEL, "Initializing Qthreads runtime");
  if (qthread_initialize())
    __kitrt_fatal(LABEL, "Could not initialize Qthreads runtime");
  __kitrt_message(LABEL, "Initialized Qthreads runtime");

  __kitrt_message(LABEL, "Number of shepherds = %d", qthread_num_shepherds());
  __kitrt_message(LABEL, "Number of workers = %d", qthread_num_workers());

  __kitrt_message(LABEL, "Initialized Kitsune runtime (qthreads)");
}

/// Finalize kitsune's qthreads runtime, as well as qthreads runtime.
extern "C" void __kitqthr_finalize(void) {
  __kitrt_message(LABEL, "Finalizing Kitsune runtime (qthreads)");

  __kitrt_message(LABEL, "Finalizing Qthreads runtime");
  qthread_finalize();
  __kitrt_message(LABEL, "Finalized Qthreads runtime");

  __kitrt_message(LABEL, "Finalized Kitsune runtime (qthreads)");

  // Finalize the components of Kitsune's runtime that are shared by the
  // tapir-target-specific components.
  __kitrt_finalize();
}
