//===- kitqthr.h - Runtime for Kitsune's qthreads tapir target --*- C++ -*-===//
//
// Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
// All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//  software was produced under U.S. Government contract
//  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//  is operated by Los Alamos National Security, LLC for the
//  U.S. Department of Energy. The U.S. Government has rights to use,
//  reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//  NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//  OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//  If software is modified to produce derivative works, such modified
//  software should be clearly marked, so as not to confuse it with
//  the version available from LANL.
//
//  Additionally, redistribution and use in source and binary forms,
//  with or without modification, are permitted provided that the
//  following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials provided
//      with the distribution.
//
//    * Neither the name of Los Alamos National Security, LLC, Los
//      Alamos National Laboratory, LANL, the U.S. Government, nor the
//      names of its contributors may be used to endorse or promote
//      products derived from this software without specific prior
//      written permission.
//
//  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//  SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//
//
// This targets Qthreads.
//
// NOTE: This is an internal header and not really intended for public
// consumption. The main reason for this is to make the lit tests a bit more
// convenient to write.
//
//===----------------------------------------------------------------------===//

#ifndef KITRT_QTHREADS_KITQTHR_H
#define KITRT_QTHREADS_KITQTHR_H

#include "common/thread.h"
#include "global/singleton.h"

#include <cstdint>

#ifdef __cplusplus
#define EXTERN_C extern "C"
#else // !__cplusplus
#define EXTERN_C
#endif // !__cplusplus

namespace kitrt {

/// The signature of the function that is run on each thread. The last argument
/// is a pointer to a struct generated by the compiler where all the data needed
/// by the function is bundled together. \p start must be 0, \p end must be the
/// equal to \ref __kitqthr_num_threads().
using KitQthrThrdFunc = void(uint64_t start, uint64_t end, void *args);

/// Kitsune runtime the qthreads tapir target. All global state required by the
/// runtime should be owned by this object.
class KitQthrContext : public KitContextMixin<KitQthrContext> {
public:
  void initialize();
  void finalize();
  uint64_t getNumThreads() const;
  KitThreadID getThreadID() const;
  void launch(KitQthrThrdFunc f, uint64_t start, uint64_t end, void *args,
              [[maybe_unused]] uint32_t argSize);

public:
  static constexpr const char *name() { return "qthreads"; }
};

} // namespace kitrt

/// Launch some number of threads each of which will execute some number of
/// iterations in the space [\p start, \p end). This blocks until all threads
/// have completed. The compiler will transform all tapir loops so they are of
/// the following form:
///
///     unsigned numThreads = __kitqthr_num_threads();
///     size_t itersPerThread = (numThreads + n - 1) / numThreads
///     forall (unsigned t = 0; t < numThrds; ++t) {
///       size_t start = t * itersPerThread;
///       size_t end = std::min(start + itersPerThread, n);
///       for (size_t i = start; i < end; ++i)
///         ...
///     }
///
/// This function, therefore, will launch exactly `end - start` threads, each of
/// which will execute exactly one iteration. In the future, `end - start` may
/// be less than the number of threads available.
///
/// NOTE: At this time, \p argSize is not used because this function blocks
/// until all threads have finished executing. In the future, if we change this
/// to be non-blocking, \p args will be copied before this returns, at which
/// point, \p argSize will be used.
///
/// \param f The function to execute on each thread
/// \param start The start index of the iteration space
/// \param end The value one greater than the last index of the iteration space
/// \param args A struct containing data to be passed to \p f
/// \param argSize The size of the struct pointed to by \p args.
EXTERN_C void __kitqthr_launch(kitrt::KitQthrThrdFunc *f, uint64_t start,
                               uint64_t end, void *args, uint32_t argSize);

/// Get the number of parallel workers that are available.
EXTERN_C uint64_t __kitqthr_num_workers(void);

/// Get the ID of the worker from which this is called.
EXTERN_C KitThreadID __kitqthr_worker_id(void);

#undef EXTERN_C
#endif // KITRT_QTHREADS_KITQTHR_H
