//=- KitsuneMetadata.h - Helper functions for Kitsune metadata ---*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Helper functions to add and query Kitsune-specific metadata. For now, these
// are a quick way to add specific metadata without registering everything using
// LLVM's standard metadata mechanisms.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_IR_KITSUNE_METADATA_H
#define LLVM_IR_KITSUNE_METADATA_H

#include "llvm/ADT/StringRef.h"
#include "llvm/Frontend/Tapir/Tapir.h"

#include <optional>

namespace llvm {

class GlobalVariable;

// TODO: At some point, we may want to make these first-class attributes that
// are part of the various Attribute enums.

/// Attribute indicating that a function in an embedded module is one obtained
/// by outlining a tapir loop. For the GPU-centric tapir targets, this indicates
/// that the function will be launched as a GPU kernel.
constexpr const char *KITSUNE_ATTR_OUTLINED_FROM_TAPIR_LOOP =
    "kitsune.outlined.from.tapir.loop";

/// Set metadata on a global variable to indicate that it contains serialized
/// LLVM bitcode generated by the given tapir target.
void setKitsuneBCMD(GlobalVariable &g, TapirTargetID tt);

/// Set metadata on a global variable to indicate that it contains a
/// serialized fat binary to be used by the runtime for the given tapir target.
void setKitsuneFBMD(GlobalVariable &g, TapirTargetID tt);

/// Set metadata on a global variable to indicate that it contains metadata for
/// a kernel function. The value of the metadata node is the name of the kernel
/// function.
void setKitsuneKernelMDMD(GlobalVariable &g, StringRef kname);

/// Check if the given global variable contains embedded bitcode generated by
/// any tapir target.
bool hasKitsuneBCMD(const GlobalVariable &g);

/// Check if the given global variable contains embedded bitcode generated by
/// the given tapir target.
bool hasKitsuneBCMD(const GlobalVariable &g, TapirTargetID tt);

/// Check if the given global variable contains a serialized fat binary
/// generated by any tapir target.
bool hasKitsuneFBMD(const GlobalVariable &g);

/// Check if the given global variable contains a serialized fat binary
/// generated by the given tapir target.
bool hasKitsuneFBMD(const GlobalVariable &g, TapirTargetID tt);

/// Check if the global variable is one that contains metadata about a kernel
/// function.
bool hasKitsuneKernelMDMD(const GlobalVariable &g);

/// Check if the given global variable contains embedded bitcode. If it does,
/// return the tapir target that generated it.
std::optional<TapirTargetID> getKitsuneBCMD(const GlobalVariable &g);

/// Check if the given global variable contains a fat binary. If it does, return
/// the tapir target that generated it.
std::optional<TapirTargetID> getKitsuneFBMD(const GlobalVariable &g);

/// Check if the given global variable contains metadata for a kernel function.
/// If it does, return the name of the kernel function for which it has this
/// data.
std::optional<StringRef> getKitsuneKernelMDMD(const GlobalVariable &g);

} // namespace llvm

#endif // LLVM_IR_KITSUNE_METADATA_H
