//=- KitsuneMetadata.h - Helper functions for Kitsune metadata ---*- C++ -*--=//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Helper functions to add and query Kitsune-specific metadata. For now, these
// are a quick way to add specific metadata without registering everything using
// LLVM's standard metadata mechanisms.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_IR_KITSUNE_METADATA_H
#define LLVM_IR_KITSUNE_METADATA_H

#include "llvm/Frontend/Tapir/Tapir.h"

#include <optional>

namespace llvm {

class GlobalVariable;

/// Set metadata on a global variable to indicate that it contains serialized
/// LLVM bitcode generated by the given tapir target.
void setKitsuneBCMD(GlobalVariable &g, TapirTargetID tt);

/// Set metadata on a global variable to indicate that it contains a
/// serialized fat binary to be used by the runtime for the given tapir target.
void setKitsuneFBMD(GlobalVariable &g, TapirTargetID tt);

/// Check if the given global variable contains embedded bitcode generated by
/// any tapir target.
bool hasKitsuneBCMD(const GlobalVariable &g);

/// Check if the given global variable contains embedded bitcode generated by
/// the given tapir target.
bool hasKitsuneBCMD(const GlobalVariable &g, TapirTargetID tt);

/// Check if the given global variable contains a serialized fat binary
/// generated by any tapir target.
bool hasKitsuneFBMD(const GlobalVariable &g);

/// Check if the given global variable contains a serialized fat binary
/// generated by the given tapir target.
bool hasKitsuneFBMD(const GlobalVariable &g, TapirTargetID tt);

/// Check if the given global variable contains embedded bitcode or a fat
/// binary. If it does, return the tapir target that generated it.
std::optional<TapirTargetID> getKitsuneTTMD(const GlobalVariable &g);

} // namespace llvm

#endif // LLVM_IR_KITSUNE_METADATA_H
