//===- CGFBCuda.cpp - Generate embedded device code for NVIDIA GPUs -------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the cuda tapir target into
// embedded device code. The device code may be SASS or PTX.
//
//===----------------------------------------------------------------------===//

#include "CGFBImpl.h"
#include "kitsune/Config/config.h"
#include "kitsune/Core/EmbBitcodeUtils.h"
#include "kitsune/Core/EmbDeviceCodeUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "kitsune/Core/TargetUtils.h"
#include "kitsune/Object/EmbDeviceCode.h"
#include "kitsune/Support/Error.h"
#include "kitsune/Support/OptznLevelUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"

using namespace llvm;

namespace {

/// Helper class to generate code for NVIDIA GPU's from embedded bitcode.
class CGFBCuda {
private:
  const TapirTargetOptions &tto;
  const detail::CGFBOptions &cgfbOpts;

private:
  void embedDeviceCode(ToolOutputFile &deviceCode, Module &hostM, bool isPTX) {
    ErrorOr<std::unique_ptr<MemoryBuffer>> buf =
        MemoryBuffer::getFile(deviceCode.getFilename());
    if (std::error_code ec = buf.getError())
      report_internal_error("error loading nvidia device code. ", ec);

    LLVMContext &ctx = hostM.getContext();
    Type *i8 = Type::getInt8Ty(ctx);
    Type *i64 = Type::getInt64Ty(ctx);

    Constant *init =
        ConstantDataArray::getString(ctx, buf->getBuffer(), /*AddNull=*/false);
    GlobalValue::LinkageTypes linkage = GlobalValue::PrivateLinkage;

    GlobalVariable *payload =
        new GlobalVariable(hostM, type, /*isConstant=*/true, linkage, init);
    payload->setAlignment(MaybeAlign(8));
    payload->addAttribute(Attribute::getWithTTID(ctx, TTID::Cuda));
    payload->setSection(KITSUNE_CUDA_CODE_SECTION);
    payload->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
  }

  /// Translate the device module from LLVM-IR to PTX. This creates an
  /// intermediate PTX file.
  std::unique_ptr<ToolOutputFile> genPTX(Module &km) {
    LLVM_DEBUG(dbgs() << "\t- generating ptx...\n");

    SmallString<255> ptxFileName;
    std::string model = join_items("-", "kitcu", "%%%%%%%%", km.getName());
    sys::fs::createUniquePath(model.c_str(), ptxFileName, true);
    sys::path::replace_extension(ptxFileName, ".ptx");
    LLVM_DEBUG(dbgs() << "\t- ptx file: '" << ptxFileName << "'.\n");

    std::error_code ec;
    auto ptxFile = std::make_unique<ToolOutputFile>(
        ptxFileName, ec, sys::fs::OpenFlags::OF_None);
    if (ec)
      report_internal_error("could not create ptx file: ", ec);

    // The build system should have ensured that the NVPTX target is available.
    TargetMachine *tm =
        createTargetMachine(TTID::Cuda, tto, cgfbOpts.cgOptLevel);
    assert(tm && "Could not create NVPTX target machine");
    if (cgfbOpts.debugTargetMachine)
      detail::debugTargetMachine(*tm, errs());
    if (cgfbOpts.debugTargetOptions)
      dump(tm->Options, errs());
    if (cgfbOpts.debugMCTargetOptions)
      dump(tm->Options.MCOptions, errs());

    // Setup the passes and request that the output goes to the specified PTX
    // file.
    legacy::PassManager passMgr;
    if (tm->addPassesToEmitFile(passMgr, ptxFile->os(),
                                /*DwoOut=*/nullptr,
                                CodeGenFileType::AssemblyFile,
                                /*DisableVerify=*/false))
      report_internal_error("error generating PTX: ", ec);
    passMgr.run(km);

    LLVM_DEBUG(dbgs() << "PTX generation complete.\n\n");
    return ptxFile;
  }

  std::unique_ptr<ToolOutputFile> genMachineCode(ToolOutputFile &ptxFile) {
    LLVM_DEBUG(dbgs() << "\t- generating machine code...\n");

    SmallString<255> mcFileName(ptxFile.getFilename());
    sys::path::replace_extension(mcFileName, ".cubin");
    LLVM_DEBUG(dbgs() << "\t- machine code file: '" << mcFileName << "'.\n");

    std::error_code ec;
    auto mcFile = std::make_unique<ToolOutputFile>(mcFileName, ec,
                                                   sys::fs::OpenFlags::OF_None);
    if (ec)
      report_internal_error("could not create device code file: ", ec);

    // Build the command line for ptxas.
    std::vector<StringRef> args;

    StringRef ptxas = KITSUNE_CUDA_PTXAS;
    args.push_back(ptxas);

    args.push_back("--compile-only");
    args.push_back("--gpu-name");
    args.push_back(tto.getCudaArch());

    if (cgfbOpts.ptxasPIC) {
      args.push_back("--position-independent-code");
      args.push_back("true");
    }

    // TODO: We should probably warn on spills only in verbose mode.
    // Warn if we spill registers and provide feedback on kernel stats.
    args.push_back("--warn-on-spills");
    if (tto.getTapirVerbose())
      args.push_back("--verbose");

    std::string optLevel =
        std::to_string(getSpeedupLevel(cgfbOpts.ptxasOptLevel));
    args.push_back("--opt-level");
    args.push_back(optLevel);

    args.push_back("--output-file");
    args.push_back(mcFileName);

    // Input file
    args.push_back(ptxFile.getFilename());

    LLVM_DEBUG({
      dbgs() << "\t- ptxas command line:\n";
      dbgs() << "\t\t" << ptxas << "\n";
      unsigned i = 1;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });
    if (cgfbOpts.debugCommandLines)
      errs() << join(args, " ") << "\n";

    std::string errMsg;
    if (sys::ExecuteAndWait(ptxas, args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*SecondsToWait=*/0, /* 0 => unlimited */
                            /*MemoryLimit=*/0,   /* 0 => unlimited */
                            &errMsg)) {
      if (errMsg.empty())
        report_internal_error("error generating nvidia device code");
      else
        report_internal_error("error generating nvidia device code: ", errMsg);
    }

    LLVM_DEBUG(dbgs() << "machine code file generation complete.\n\n");
    return mcFile;
  }

public:
  CGFBCuda(const TapirTargetOptions &tto, const detail::CGFBOptions &cgfbOpts)
      : tto(tto), cgfbOpts(cgfbOpts) {}

  bool run(Module &hostM, Module &devM) {
    std::unique_ptr<ToolOutputFile> mcFile = nullptr;
    std::unique_ptr<ToolOutputFile> ptxFile = genPTX(devM);
    if (cgfbOpts.embedPTX) {
      embedDeviceCode(*mcFile, hostM, true);
    } else {
      mcFile = genMachineCode(*ptxFile);
      embedDeviceCode(*mcFile, hostM, false);
    }

    if (cgfbOpts.keepFiles) {
      ptxFile->keep();
      if (mcFile)
        mcFile->keep();
    }
    return true;
  }
};

} // namespace

bool llvm::detail::cgfbCuda(Module &hostM, Module &devM,
                            const TapirTargetOptions &tto,
                            const detail::CGFBOptions &cgfbOpts) {
  return CGFBCuda(tto, cgfbOpts).run(hostM, devM);
}
