//===- CGFBCuda.cpp - Generate fat binaries for NVIDIA GPUs ---------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the cuda tapir target into fat
// binaries.
//
//===----------------------------------------------------------------------===//

#include "CGFBImpl.h"
#include "kitsune/Config/config.h"
#include "kitsune/Core/EmbUtils.h"
#include "kitsune/Core/SingletonUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "kitsune/Core/TargetUtils.h"
#include "kitsune/Support/OptznLevelUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"

using namespace llvm;

static unsigned parseCudaArch(StringRef arch) {
  auto fail = [](StringRef arch) -> void {
    report_fatal_error("Unexpected cuda architecture: " + arch);
  };

  // The architecture is expected to be of the form sm_NNNN where NNNN is some
  // integer. Anything deviation from this should have been caught in the
  // frontend. If using opt directly to run this pass, such checks are
  // skipped, so we might yet end up with an invalid architecture. The parse
  // function will return 0 if any unexpected character was found. Fail
  // catastrophically if that happens.
  unsigned res = 0;
  if (arch.starts_with("sm_")) {
    for (unsigned i = 3; i < arch.size(); ++i) {
      if (std::isdigit(arch[i]))
        res = res * 10 + (int(arch[i]) - int('0'));
      else
        fail(arch);
    }
  }

  if (res == 0)
    fail(arch);
  return res;
}

namespace {

/// Helper class to generate code for NVIDIA GPU's from embedded bitcode.
class CGFBCuda {
private:
  const TapirTargetOptions &tto;
  const detail::CGFBOptions &cgfbOpts;

private:
  void embedAsmFile(ToolOutputFile &asmFile, Module &hostM) {
    ErrorOr<std::unique_ptr<MemoryBuffer>> bufOrErr =
        MemoryBuffer::getFile(asmFile.getFilename());
    if (std::error_code ec = bufOrErr.getError()) {
      report_fatal_error(StringRef(llvm::join_items(
          " ", "failed to load assembled file image:", ec.message())));
    }

    const MemoryBuffer &buf = **bufOrErr;
    LLVMContext &ctx = hostM.getContext();
    size_t size = buf.getBufferSize();
    StringRef data = buf.getBuffer();

    // The embedded code is saved in a struct of the form
    //
    //   struct {
    //     uint64_t size;  // The size in bytes of the code
    //     uint32_t isPtx; // A boolean where 1 indicates that the code is PTX,
    //                     // SASS otherwise
    //     uint32_t arch;  // The architecture. If the cuda architecture is
    //                     // "sm_86", this will be 86.
    //     byte code[];    // The actual code.
    //   };
    //
    Type *i8 = Type::getInt8Ty(ctx);
    Type *i32 = Type::getInt32Ty(ctx);
    Type *i64 = Type::getInt64Ty(ctx);
    Type *bufTy = ArrayType::get(i8, size);
    StructType *type = StructType::get(i64, i32, i32, bufTy);
    GlobalValue::LinkageTypes linkage = GlobalValue::PrivateLinkage;

    Constant *csz = ConstantInt::get(i64, size);
    Constant *cptx = ConstantInt::get(i32, cgfbOpts.embedPTX);
    Constant *carch = ConstantInt::get(i32, parseCudaArch(tto.getCudaArch()));
    Constant *cbuf = ConstantDataArray::getString(ctx, data, /*AddNull=*/false);
    Constant *init = ConstantStruct::get(type, {csz, cptx, carch, cbuf});

    GlobalVariable *payload =
        new GlobalVariable(hostM, type, /*isConstant=*/true, linkage, init);
    payload->setAlignment(MaybeAlign(8));
    payload->addAttribute(Attribute::getWithTTID(ctx, TTID::Cuda));
    payload->setSection(cudaDeviceCodeSection);
    payload->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
  }

  std::unique_ptr<ToolOutputFile> generatePTX(Module &km) {
    LLVM_DEBUG(dbgs() << "\t- generating ptx...\n");

    // Translate the device module from LLVM-IR to PTX. This creates an
    // intermediate PTX file.
    SmallString<1024> ptxFilename;
    std::string model = join_items("-", "kitcu", "%%%%%%%%", km.getName());
    sys::fs::createUniquePath(model.c_str(), ptxFilename, true);
    sys::path::replace_extension(ptxFilename, ".ptx");
    LLVM_DEBUG(dbgs() << "\t- ptx file: '" << ptxFilename << "'.\n");

    std::error_code ec;
    auto ptxFile = std::make_unique<ToolOutputFile>(
        ptxFilename, ec, sys::fs::OpenFlags::OF_None);
    if (ec)
      report_fatal_error(Twine("Could not create ptx file: ") + ec.message());

    // The build system should have ensured that the NVPTX target is available.
    TargetMachine *tm =
        createTargetMachine(TTID::Cuda, tto, cgfbOpts.cgOptLevel);
    assert(tm && "Could not create NVPTX target machine");
    if (cgfbOpts.debugTargetMachine)
      detail::debugTargetMachine(*tm, errs());
    if (cgfbOpts.debugTargetOptions)
      dump(tm->Options, errs());
    if (cgfbOpts.debugMCTargetOptions)
      dump(tm->Options.MCOptions, errs());

    // Setup the passes and request that the output goes to the specified PTX
    // file.
    legacy::PassManager passMgr;
    if (tm->addPassesToEmitFile(passMgr, ptxFile->os(),
                                /*DwoOut=*/nullptr,
                                CodeGenFileType::AssemblyFile,
                                /*DisableVerify=*/false))
      report_fatal_error(Twine("PTX generation failed: ") + ec.message());
    passMgr.run(km);

    LLVM_DEBUG(dbgs() << "PTX generation complete.\n\n");
    return ptxFile;
  }

  std::unique_ptr<ToolOutputFile> assemblePTX(ToolOutputFile &ptxFile) {
    LLVM_DEBUG(dbgs() << "\t- generating asm...\n");

    std::string ptxFilename = ptxFile.getFilename().str();
    SmallString<255> asmFilename(ptxFilename);
    sys::path::replace_extension(asmFilename, ".s");
    LLVM_DEBUG(dbgs() << "\t- asm file: '" << ptxFilename << "'.\n");

    std::error_code ec;
    auto asmFile = std::make_unique<ToolOutputFile>(
        asmFilename, ec, sys::fs::OpenFlags::OF_None);
    if (ec)
      report_fatal_error(Twine("Could not create asm file: ") + ec.message());

    // Build the command line for ptxas.
    std::vector<StringRef> args;

    StringRef ptxas = KITSUNE_CUDA_PTXAS;
    args.push_back(ptxas);

    // TODO: Do we need/want to add support for generating relocatable code? It
    // may be useful to allow deferring symbol resolution to link time. That
    // may be necessary if we ever support separate compilation with device
    // functions spread across translation units. That would entail adding
    // the --compile option here.

    // The gpu architecture (e.g., sm_86)
    args.push_back("--gpu-name");
    args.push_back(tto.getCudaArch());

    // Warn if we spill registers and provide feedback on kernel stats.
    args.push_back("--warn-on-spills");

    if (tto.getTapirVerbose())
      args.push_back("--verbose");

    std::string optLevel =
        std::to_string(getSpeedupLevel(cgfbOpts.ptxasOptLevel));
    args.push_back("--opt-level");
    args.push_back(optLevel);

    std::string scodeFilename = asmFile->getFilename().str();
    args.push_back("--output-file");
    args.push_back(scodeFilename);

    args.push_back(ptxFilename);

    LLVM_DEBUG({
      dbgs() << "\t- ptxas command line:\n";
      dbgs() << "\t\t" << ptxas << "\n";
      unsigned i = 1;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });
    if (cgfbOpts.debugCommandLines)
      errs() << join(args, " ") << "\n";

    std::string errMsg;
    if (sys::ExecuteAndWait(ptxas, args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*SecondsToWait=*/0, /* 0 => unlimited */
                            /*MemoryLimit=*/0,   /* 0 => unlimited */
                            &errMsg))
      report_fatal_error(Twine("'ptxas' failed: ") + errMsg);

    LLVM_DEBUG(dbgs() << "asm file generation complete.\n\n");
    return asmFile;
  }

  std::unique_ptr<ToolOutputFile> createFatBinary(ToolOutputFile &asmFile) {
    LLVM_DEBUG(dbgs() << "\t- generating fatbin...\n");

    SmallString<255> fatbinFilename(asmFile.getFilename());
    sys::path::replace_extension(fatbinFilename, ".cufatbin");
    LLVM_DEBUG(dbgs() << "\t- fatbin file '" << fatbinFilename << "'.\n");

    std::error_code ec;
    auto fatbinFile = std::make_unique<ToolOutputFile>(
        fatbinFilename, ec, sys::fs::OpenFlags::OF_None);

    StringRef fatbin = KITSUNE_CUDA_FATBINARY;
    std::vector<StringRef> args;
    args.push_back(fatbin);
    args.push_back("--64");
    args.push_back("--create");
    args.push_back(fatbinFilename);

    std::string imgArgs = join_items("", "--image=profile=", tto.getCudaArch(),
                                     ",file=", asmFile.getFilename());
    args.push_back(imgArgs);

    // FIXME: This code looks like it is broken.
    // std::list<std::string> PTXFilesArgList;
    // if (EmbedPTXInFatbinaries) {
    //   StringRef varch = ttOpts.getCudaVirtArch();
    //   if (varch == "unknown")
    //     report_fatal_error("cuabi: no virtual target for given gpuarch '" +
    //                        TTO.getCudaArch() + "'!");

    //   std::string PTXFixedArgStr =
    //       ("--image=profile=" + VArchStr + ",file=").str();
    //   for (auto &PTXFile : ModulePTXFileList) {
    //     std::string arg = PTXFixedArgStr + PTXFile;
    //     std::list<std::string>::const_iterator it;
    //     it = PTXFilesArgList.emplace(PTXFilesArgList.end(), std::move(arg));
    //     args.push_back(it->c_str());
    //   }
    // }

    LLVM_DEBUG({
      dbgs() << "\tfatbinary command line:\n";
      unsigned i = 0;
      for (StringRef arg : args)
        dbgs() << "\t\t" << i++ << ": " << arg << "\n";
      dbgs() << "\n\n";
    });
    if (cgfbOpts.debugCommandLines)
      errs() << join(args, " ") << "\n";

    std::string errMsg;
    if (sys::ExecuteAndWait(/*Program=*/fatbin,
                            /*Args=*/args,
                            /*Env=*/std::nullopt,
                            /*Redirects=*/{},
                            /*(0 => unlimited) SecondsToWait=*/0,
                            /*(0 => unlimited) MemoryLimit=*/0,
                            /*ErrMsg=*/&errMsg))
      // TODO: Need to check what sort of actual state 'fatbinary' returns to
      // the environment -- currently assuming it matches standard practices
      report_fatal_error(Twine("fatbinary failed: ") + errMsg);

    return fatbinFile;
  }

public:
  CGFBCuda(const TapirTargetOptions &tto, const detail::CGFBOptions &cgfbOpts)
      : tto(tto), cgfbOpts(cgfbOpts) {}

  bool run(Module &hostM, Module &devM) {
    std::unique_ptr<ToolOutputFile> ptxFile = generatePTX(devM);
    std::unique_ptr<ToolOutputFile> asmFile = assemblePTX(*ptxFile);
    embedAsmFile(*asmFile, hostM);

    if (cgfbOpts.keepFiles) {
      ptxFile->keep();
      asmFile->keep();
    }
    return true;
  }
};

} // namespace

bool llvm::detail::cgfbCuda(Module &hostM, Module &devM,
                            const TapirTargetOptions &tto,
                            const detail::CGFBOptions &cgfbOpts) {
  return CGFBCuda(tto, cgfbOpts).run(hostM, devM);
}
