//==- CodeGenFatBinaries.cpp - Generate fat binaries from embedded bitcode -==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into fat binaries.
//
//===----------------------------------------------------------------------===//

#include "kitsune/CodeGen/CodeGenFatBinaries.h"
#include "CGFBImpl.h"
#include "kitsune/Analysis/TapirTargetAnalysis.h"
#include "kitsune/Core/CommandLineOptions.h"
#include "kitsune/Core/EmbUtils.h"
#include "kitsune/Core/GlobalVariableUtils.h"
#include "kitsune/Core/SingletonUtils.h"
#include "kitsune/Core/TapirTargetOptions.h"
#include "kitsune/Support/OptznLevelUtils.h"
#include "kitsune/Support/TTUtils.h"
#include "kitsune/Support/ToString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"

using namespace llvm;

static cl::opt<bool>
    clKeepFiles("cgfb-keep-files", cl::init(false), cl::Hidden,
                cl::desc("Do not delete intermediate files created during "
                         "generation of the fat binaries"),
                cl::cat(cl::catKitClDevOpts));

// Override the optimization used by the target machine. If this is not
// explicitly set, it will use the optimization level set in the
// TapirTargetOptions.
static cl::opt<CodeGenOptLevel> clCGOptLevel(
    cl::init(CodeGenOptLevel::Default), cl::Hidden,
    cl::values(clEnumValN(CodeGenOptLevel::None, "cgfb-O0", ""),
               clEnumValN(CodeGenOptLevel::Less, "cgfb-O1", ""),
               clEnumValN(CodeGenOptLevel::Default, "cgfb-O2", ""),
               clEnumValN(CodeGenOptLevel::Aggressive, "cgfb-O3", "")),
    cl::cat(cl::catKitClDevOpts));

// The default mode of the transformation is to embed a single fat binary
// image for the selected target architecture. With this flag set, the PTX
// form of the code will also be embedded into the fat binary. static
cl::opt<bool> clEmbedPTX(
    "cgfb-embed-ptx", cl::init(false), cl::Hidden,
    cl::desc("Embed PTX code in the fat binaries generated for the cuda tapir "
             "target (NOT YET IMPLEMENTED)"));

// Override the optimization level used by ptxas when generating GPU code.
// If this is not explicitly set, it will use the optimization level set in
// the TapirTargetOptions, which is usually whatever was passed to the
// frontend.
static cl::opt<OptznLevel> clPtxasOptLevel(
    cl::init(OptznLevel::O3), cl::Hidden,
    cl::values(clEnumValN(OptznLevel::O0, "cgfb-ptxas-O0", "Pass O0 to ptxas"),
               clEnumValN(OptznLevel::O1, "cgfb-ptxas-O1", "Pass O1 to ptxas"),
               clEnumValN(OptznLevel::O2, "cgfb-ptxas-O2", "Pass O2 to ptxas"),
               clEnumValN(OptznLevel::O3, "cgfb-ptxas-O3", "Pass O3 to ptxas")),
    cl::desc("Override the optimization level passed to ptxas"),
    cl::cat(cl::catKitClDevOpts));

// @{

// These options are mainly used by the tests, but could be useful for
// debugging.

static cl::opt<bool> clDebugCommandLines(
    "cgfb-###", cl::init(false), cl::Hidden,
    cl::desc("Print command lines invoking external tools to stderr"),
    cl::cat(cl::catKitClDevOpts));

static cl::opt<bool>
    clDebugMCTargetOptions("cgfb-debug-mc-target-options", cl::init(false),
                           cl::Hidden,
                           cl::desc("Print machine target options to stderr"),
                           cl::cat(cl::catKitClDevOpts));

static cl::opt<bool> clDebugTargetMachine(
    "cgfb-debug-target-machine", cl::init(false), cl::Hidden,
    cl::desc("Print some properties of the target machine to stderr"),
    cl::cat(cl::catKitClDevOpts));

static cl::opt<bool>
    clDebugTargetOptions("cgfb-debug-target-options", cl::init(false),
                         cl::Hidden, cl::desc("Print target options to stderr"),
                         cl::cat(cl::catKitClDevOpts));

// @}

void llvm::detail::debugTargetMachine(const TargetMachine &tm,
                                      raw_ostream &os) {
  const Target &tgt = tm.getTarget();
  os << "Target Machine:\n";
  os << "  Name: " << tgt.getName() << "\n";
  os << "  Description: " << tgt.getShortDescription() << "\n";
  os << "  Backend: " << tgt.getBackendName() << "\n";
  os << "  Triple: " << tm.getTargetTriple().str() << "\n";
  os << "  CPU: " << tm.getTargetCPU() << "\n";
  os << "  Features: " << tm.getTargetFeatureString() << "\n";
  os << "  Code model: " << tm.getCodeModel() << "\n";
  os << "  Relocation model: " << tm.getRelocationModel() << "\n";
  os << "  Optimization level: " << tm.getOptLevel() << "\n";
}

namespace {

/// Implementation class to compile the embedded bitcode to fat binaries.
class CodeGenFatBinaries {
private:
  const TapirTargetOptions &tto;
  detail::CGFBOptions cgfbOpts;

private:
  void initializeCGFBOptions(const Module &m) {
    cgfbOpts.cgOptLevel = createCodeGenOptLevelFrom(tto.getOptznLevel());
    if (clCGOptLevel.getNumOccurrences())
      cgfbOpts.cgOptLevel = clCGOptLevel;

    // ptxas does not support "optimized debugging". This is where one provides
    // both -O<N> and -g to ptxas, where <N> is greater than 0. If the module
    // contains debug information, always set the ptxas optimization level to
    // 0, otherwise ptxas will crash. If using the clang/flang frontends, a
    // warning message to this effect should have been printed.
    //
    // If the ptxas optimization level is overridden using the developer option,
    // that takes precedence. Since that is a developer option, and normally
    // hidden, it is reasonable to assume that the developer used it
    // intentionally. If that results in ptxas crashing, then so be it.
    //
    // FIXME: Ideally, this should have been prevented "at the source" i.e.
    // compiling with -g and -O<N> for <N> greater than 0 should be disallowed
    // in the frontend. Currently, any use of --tapir=cuda requires
    // optimizations. There are several ways around this issue, but until we
    // decide on an approach, we will just override the optimization level here.
    cgfbOpts.ptxasOptLevel = tto.getOptznLevel();
    if (clPtxasOptLevel.getNumOccurrences())
      cgfbOpts.ptxasOptLevel = clPtxasOptLevel;
    else if (m.getNamedMetadata("llvm.dbg.cu"))
      cgfbOpts.ptxasOptLevel = OptznLevel::O0;

    cgfbOpts.embedPTX = clEmbedPTX;
    cgfbOpts.keepFiles = clKeepFiles;
    cgfbOpts.debugCommandLines = clDebugCommandLines;
    cgfbOpts.debugMCTargetOptions = clDebugMCTargetOptions;
    cgfbOpts.debugTargetMachine = clDebugTargetMachine;
    cgfbOpts.debugTargetOptions = clDebugTargetOptions;

    // Embedding PTX has not been tested, so far now, fail catastrophically.
    // The documentation does say that it not yet implemented, so the user
    // should not expect things to work smoothly. Plus, it is better than
    // silently ignoring the option.
    if (cgfbOpts.embedPTX)
      report_fatal_error("NOT YET IMPLEMENTED: -cgfb-embed-ptx");
  }

public:
  CodeGenFatBinaries(const TapirTargetOptions &tto) : tto(tto) {}

  bool run(Module &m) {
    bool changed = false;

    initializeCGFBOptions(m);
    for (TTID tt : ttsUsingEmbBC) {
      if (GlobalVariable *bc = getEmbBCGlobal(tt, m)) {
        std::unique_ptr<Module> devM = parseEmbBCGlobal(*bc);
        switch (tt) {
        case TTID::Cuda:
          changed |= detail::cgfbCuda(m, *devM, tto, cgfbOpts);
          break;
        case TTID::Hip:
          changed |= detail::cgfbHip(m, *devM, tto, cgfbOpts);
          break;
        default:
          llvm_unreachable("CodeGenFatBinaries::run: TTID not handled");
        }
        bc->eraseFromParent();
      }
    }

    return changed;
  }
};

/// Legacy pass to compile the embedded bitcode to fat binaries.
class CodeGenFatBinariesLegacyPass : public ModulePass {
public:
  CodeGenFatBinariesLegacyPass() : ModulePass(ID) {
    initializeCodeGenFatBinariesLegacyPassPass(
        *PassRegistry::getPassRegistry());
  }

  StringRef getPassName() const override {
    return "Generate Kitsune fat binaries";
  }

  void getAnalysisUsage(AnalysisUsage &au) const override {
    au.addRequired<TapirTargetAnalysisWrapperPass>();
  }

  bool runOnModule(Module &m) override {
    TapirTargetInfo tgi =
        getAnalysis<TapirTargetAnalysisWrapperPass>().getResult();
    if (not tgi.hasTTID())
      return false;

    const TapirTargetOptions &ttOpts = tgi.getOptions();
    return CodeGenFatBinaries(ttOpts).run(m);
  }

public:
  static char ID;
};

} // namespace

char CodeGenFatBinariesLegacyPass::ID = 0;
INITIALIZE_PASS_BEGIN(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                      "Compile Kitsune fat binaries", false, false)
INITIALIZE_PASS_DEPENDENCY(TapirTargetAnalysisWrapperPass)
INITIALIZE_PASS_END(CodeGenFatBinariesLegacyPass, DEBUG_TYPE,
                    "Compile Kitsune fat binaries", false, false)

ModulePass *llvm::createCodeGenFatBinariesLegacyPass() {
  return new CodeGenFatBinariesLegacyPass();
}

PreservedAnalyses CodeGenFatBinariesPass::run(Module &m,
                                              ModuleAnalysisManager &mam) {
  // If a primary tapir target ID has not been set, then tapir lowering was not
  // enabled and there is nothing to be done.
  const TapirTargetInfo &tgi = mam.getResult<TapirTargetAnalysis>(m);
  if (not tgi.hasTTID())
    return PreservedAnalyses::all();

  const TapirTargetOptions &ttOpts = tgi.getOptions();
  CodeGenFatBinaries(ttOpts).run(m);

  // This does not invalidate any analyses, even if any fat binaries were
  // generated since only global variables will have been modified.
  return PreservedAnalyses::all();
}
