// REQUIRES: kitsune-papi, nvidia-gpu
//
// The cuda tapir target must not initialize PAPI since we do not use PAPI to
// profile NVIDIA GPU code generated by Kitsune.
//
// RUN: %exe | FileCheck %s
//
// CHECK: Before __kitcuda_initialize: 0
// CHECK: After __kitcuda_initialize: 0
// CHECK: Before __kitcuda_finalize: 0
// CHECK: After __kitcuda_finalize: 0

#include "papi.h"

#include <stdio.h>

// cuda/kitcuda.h is not safe to be included in C source files. That header
// should be modified, but that might be a non-trivial change, so for now, this
// is easier.
void __kitcuda_initialize(void);
void __kitcuda_finalize(void);

__attribute__((constructor)) static void ctor(void) {
  printf("Before __kitcuda_initialize: %d\n", PAPI_is_initialized());
  __kitcuda_initialize();
  printf("After __kitcuda_initialize: %d\n", PAPI_is_initialized());
}

__attribute__((destructor)) static void dtor(void) {
  printf("Before __kitcuda_finalize: %d\n", PAPI_is_initialized());
  __kitcuda_finalize();
  printf("After __kitcuda_finalize: %d\n", PAPI_is_initialized());
}

int main(int argc, char *argv[]) { return 0; }
