// REQUIRES: kitsune-papi, nvidia-gpu
//
// The cuda tapir target must not initialize PAPI since we do not use PAPI to
// profile NVIDIA GPU code generated by Kitsune.
//
// RUN: %exe | FileCheck %s
//
// CHECK: Before initialize: false
// CHECK: After initialize: false

#include "TestHelpers.h"

#include "papi.h"

#include <stdio.h>

const KitRTInitOptions initOpts{RT_PAPI | RT_CUDA};

__attribute__((constructor)) static void ctor(void) {
  printf("Before initialize: %s\n", BOOLSTR(PAPI_is_initialized()));
  __kitrt_initialize(&initOpts);
  printf("After initialize: %s\n", BOOLSTR(PAPI_is_initialized()));
}

__attribute__((destructor)) static void dtor(void) {
  __kitrt_finalize(&initOpts);
}

int main(int argc, char *argv[]) { return 0; }
