//===- DeviceCodeLinker.cpp - Simple linker for embedded device code ------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Linker for embedded device code.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Linker/DeviceCodeLinker.h"

using namespace llvm;
using namespace llvm::object;

DeviceCodeLinker::DeviceCodeLinker(TTID tt) : tt(tt) {}

Error DeviceCodeLinker::add(const Binary &bin) {
  StringRef fileName = bin.getFileName();
  if (binFiles.contains(fileName))
    return Error::success();

  Expected<EmbDeviceCode> devCode = EmbDeviceCode::parse(bin, tt);
  if (not devCode)
    return devCode.takeError();

  bins.insert({&bin, *devCode});
  binFiles.insert(fileName);

  return Error::success();
}

Expected<DeviceCodeLinker::Result> linkStatic(bool all) {
  for (TTID tt : tts) {
    assert(devCodes.size() && "Cannot have empty device code array");

    // Sanity check the embedded device code objects that were found. All
    // embedded device code objects generated by a given tapir target must have
    // the same binary format and target.
    SmallVector<EmbDeviceCode, 8> devCodes;
    EmbDeviceCode::Id id = devCodes[0].getId();
    for (const EmbDeviceCode &devCode : devCodes) {
      if (devCode.getId() != id)
        return createStringError("Inconsistent formats and targets for "
                                 "embedded device code in archive");
      devCodes.push_back(codes.get(tt));
    }

    // Now construct a new archive containing all the embedded device code.
    SmallVector<NewArchiveMember, 4> newMembers;
    for (const EmbDeviceCode &devCode : devCodes) {
      if (devCode.isStatic()) {

      } else if (devCode.isObject()) {
        StringRef name = devCode.getName();
        StringRef code = devCode.getCode();
        NewArchiveMember &member = newMembers.emplace_back();

        member.Buf =
            MemoryBuffer::getMemBuffer(code, name,
                                       /*RequiresNullTerminator=*/false);
        member.MemberName = name;
      } else {
        report_internal_error("Unexpected format of embedded device code");
      }
    }

    Expected<std::unique_ptr<MemoryBuffer>> newArchiveOrErr =
        writeArchiveToBuffer(newMembers, SymtabWritingMode::NormalSymtab,
                             Archive::getDefaultKind(), /*Deterministic=*/false,
                             /*Thin=*/false);
    if (not newArchiveOrErr)
      return newArchiveOrErr.takeError();

    const MemoryBuffer &newArchive = **newArchiveOrErr;
    StringRef newArchiveCode = newArchive.getBuffer();
    StringRef oldArchiveName = archive.getFileName();

    archives.emplace_back(std::move(*newArchiveOrErr));
    codes.emplace_back(id, newArchiveCode, oldArchiveName);
  }
}
