// REQUIRES: kitsune-papi, amd-gpu
//
// The hip tapir target must not initialize PAPI since we do not use PAPI to
// profile NVIDIA GPU code generated by Kitsune.
//
// RUN: %exe | FileCheck %s
//
// CHECK: Before __kithip_initialize: 0
// CHECK: After __kithip_initialize: 0
// CHECK: Before __kithip_finalize: 0
// CHECK: After __kithip_finalize: 0

#include "papi.h"

#include <stdio.h>

// hip/kithip.h pulls in the hip headers. Since we don't need any of that, just
// declare what we need.
extern "C" void __kithip_initialize(void);
extern "C" void __kithip_finalize(void);

__attribute__((constructor)) static void ctor(void) {
  printf("Before __kithip_initialize: %d\n", PAPI_is_initialized());
  __kithip_initialize();
  printf("After __kithip_initialize: %d\n", PAPI_is_initialized());
}

__attribute__((destructor)) static void dtor(void) {
  printf("Before __kithip_finalize: %d\n", PAPI_is_initialized());
  __kithip_finalize();
  printf("After __kithip_finalize: %d\n", PAPI_is_initialized());
}

int main(int argc, char *argv[]) { return 0; }
