//===- openmp/context.h - Context for the openmp runtime --------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Context object for any state required by the Kitsune's openmp runtime.
//
//===----------------------------------------------------------------------===//

#ifndef KITRT_OPENMP_CONTEXT_H
#define KITRT_OPENMP_CONTEXT_H

#include "common/thread.h"

#include <cstdint>

namespace kitrt {

/// The signature of the function that is run on each thread. The last argument
/// is a pointer to a struct generated by the compiler where all the data needed
/// by the function is bundled together. \p start must be 0, \p end must be the
/// equal to \ref __kitomp_num_threads().
///
/// This is a duplicate of KitOMPThrdFunc, but if the two ever diverge, we will
/// get a build-time error.
using OMPThrdFunc = void(uint64_t start, uint64_t end, void *args);

/// Kitsune runtime the opencilk tapir target. All global state required by the
/// runtime should be owned by this object.
class OpenMPContext {
public:
  void initialize();
  void finalize();
  uint64_t getNumThreads() const;
  KitThreadID getThreadID() const;
  void launch(OMPThrdFunc *f, uint64_t start, uint64_t end, void *args,
              [[maybe_unused]] uint32_t argSize);
};

} // namespace kitrt

#endif // KITRT_OPENMP_CONTEXT_H
