//==-- CodeGenKitsuneFatBinary.h - Generate fat binaries from GPU bitcode --==//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Compiles the embedded bitcode generated by the GPU-centric tapir targets
// into fat binaries.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CODEGEN_KITSUNE_FAT_BINARY_H
#define LLVM_CODEGEN_KITSUNE_FAT_BINARY_H

#include "llvm/IR/PassManager.h"

namespace llvm {

class Module;
class ModulePass;

/// Compiles any embedded bitcode generated by the GPU-centric tapir targets to
/// a fat binary. Updates the initializer of the fat binary global variable that
/// will be present in the module and removes the embedded bitcode.
class CodeGenKitsuneFatBinariesPass
    : public PassInfoMixin<CodeGenKitsuneFatBinariesPass> {
public:
  PreservedAnalyses run(Module &m, ModuleAnalysisManager &am);
};

ModulePass *createCodeGenKitsuneFatBinariesLegacyPass();

} // namespace llvm

#endif // LLVM_CODEGEN_KITSUNE_FAT_BINARY_H
