#
# Copyright (c) 2021 Triad National Security, LLC. All rights reserved.
#
# This file is part of the kitsune project. It is released under the LLVM
# license.
#

cmake_minimum_required(VERSION 3.20.0)
project(kitrt C CXX)

# ----------------------------------- NOTES -----------------------------------
#
# This file cannot use any LLVM_* or CLANG_* or KITSUNE_* variables because this
# project is built as an external project and does not have access to variables
# set in the main LLVM project. Everything needed here, including any
# configure-time options must be passed explicitly via the ExternalProject_Add
# command in the top-level kitsune/CMakeLists.txt file.
#
# -----------------------------------------------------------------------------

# Since this is built as an external project, we have to explicitly find
# libLLVM. This is guaranteed to have been built, but we need to be careful that
# we don't pick up anything from the system.
#
# NOTE: We have removed the dependence on libLLVM for now, but we keep this
# here for now. There is a lot of unused code in the runtime, most of which
# should probably be deleted but is still kept around in case we decide to
# resurrect something. If we do, some of it might require libLLVM.
find_library(LIB_LLVM REQUIRED
  NAMES
  LLVM
  LLVM-${LLVM_VERSION_MAJOR}
  LLVM-${LLVM_VERSION_MAJOR}.${LLVM_VERSION_MINOR}
  PATHS ${LLVM_LIBRARY_OUTPUT_INTDIR}
  NO_DEFAULT_PATH)

# ${KITRT} is passed in by cmake when the runtime is configured.
set(KITRT_OBJLIB ${KITRT}_objlib)

add_library(${KITRT_OBJLIB} OBJECT
  kitrt.cpp
  kittimer.cpp
  memory.cpp
  memory_map.cpp)

# These runtimes are always enabled since their corresponding tapir targets are
# always built.
target_sources(${KITRT_OBJLIB} PUBLIC
  openmp/kitomp.cpp
  pthreads/kitpthr.cpp)

# Here, ${LLVM_MAIN_INCLUDE_DIR} points to llvm/include in the source directory.
# ${LLVM_INCLUDE_DIR} points to include/ in the directory where cmake was run
# when building all of Kitsune (not just the runtime). This is where the files
# generated by LLVM's tablegen are added. clang's tablegen adds files elsewhere
# but we don't need to use those directly in any of our runtimes.
# ${KITSUNE_SOURCE_DIR} points to kitsune/ in the top-level source directory.
# This is the same as ${CMAKE_CURRENT_SOURCE_DIR}/../include.
# ${KITSUNE_BINARY_DIR} is the subdirectory of the top-level build directory
# where Kitsune is built.
target_include_directories(${KITRT_OBJLIB} PUBLIC
  ${LLVM_MAIN_INCLUDE_DIR}
  ${LLVM_INCLUDE_DIR}
  ${KITSUNE_SOURCE_DIR}/include
  ${KITSUNE_BINARY_DIR}/include
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${KITSUNE_OPENMP_INCDIRS})

target_link_libraries(${KITRT_OBJLIB} PUBLIC
  ${KITSUNE_COMMON_LIBS}
  ${KITSUNE_OPENMP_LIBS})

if (LLVM_ENABLE_ASSERTIONS)
  # The runtime is built with Kitsune, so it is safe to use options here that
  # are known to Kitsune.
  target_compile_options(${KITRT_OBJLIB} PUBLIC
    -UNDEBUG)
endif()

if (KITSUNE_PAPI_ENABLED)
  target_sources(${KITRT_OBJLIB} PUBLIC
    kitpapi.cpp)

  target_compile_definitions(${KITRT_OBJLIB} PUBLIC
    KITRT_PAPI_ENABLED)

  target_include_directories(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_PAPI_INCDIRS})

  target_link_libraries(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_PAPI_LIBS})
endif ()

if (KITSUNE_CUDA_ENABLED)
  target_sources(${KITRT_OBJLIB} PUBLIC
    cuda/kitcuda.cpp
    cuda/dylib_support.cpp
    cuda/launching.cpp
    cuda/memory.cpp
    cuda/streams.cpp)

  # FIXME: The only use of KITRT_CUDA_ENABLED seem to be some runtime
  # initialization code that is probably obsolete.
  target_compile_definitions(${KITRT_OBJLIB} PUBLIC
    KITRT_CUDA_ENABLED ${KITSUNE_CUDA_DEFNS})

  target_include_directories(${KITRT_OBJLIB} SYSTEM PUBLIC
    ${KITSUNE_CUDA_INCDIRS})

  target_include_directories(${KITRT_OBJLIB} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/cuda)

  target_link_libraries(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_CUDA_LIBS})
endif()

if (KITSUNE_HIP_ENABLED)
  target_sources(${KITRT_OBJLIB} PUBLIC
    hip/kithip.cpp
    hip/dylib_support.cpp
    hip/launching.cpp
    hip/memory.cpp
    hip/streams.cpp)

  target_compile_definitions(${KITRT_OBJLIB} PUBLIC
    # FIXME: The only use of KITRT_HIP_ENABLED seem to be some runtime
    # initialization code that is probably obsolete.
    KITRT_HIP_ENABLED

    # FIXME: It looks like __HIP_PLATFORM_AMD__ is defined in the kitsune
    # runtime headers for hip. This is probably unnecessary. Alternatively, we
    # could remove it from those headers and only include it here if is required
    # to be defined before any hip headers are included.
    __HIP_PLATFORM_AMD__)

  target_include_directories(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_HIP_INCDIRS})

  target_link_libraries(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_HIP_LIBS})
endif()

if (KITSUNE_OPENCILK_ENABLED)
  target_sources(${KITRT_OBJLIB} PUBLIC
    opencilk/kitocilk.cpp)

  target_link_libraries(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_OPENCILK_LIBS})
endif ()

if (KITSUNE_QTHREADS_ENABLED)
  target_sources(${KITRT_OBJLIB} PUBLIC
    qthreads/kitqthr.cpp)

  target_include_directories(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_QTHREADS_INCDIRS})

  target_link_libraries(${KITRT_OBJLIB} PUBLIC
    ${KITSUNE_QTHREADS_LIBS})
endif ()

add_library(${KITRT_STATIC} STATIC
  $<TARGET_OBJECTS:${KITRT_OBJLIB}>)

add_library(${KITRT} SHARED
  $<TARGET_OBJECTS:${KITRT_OBJLIB}>)

get_target_property(KITRT_LINK_LIBRARIES ${KITRT_OBJLIB} LINK_LIBRARIES)
foreach (LIB IN LISTS KITRT_LINK_LIBRARIES)
  target_link_libraries(${KITRT} PUBLIC ${LIB})
endforeach()

# If we ever need to depend on libLLVM.so, add a path relative to $ORIGIN here.
# It should be `\$ORIGIN/../../../`
set(RPATH_RELATIVE_TO_ORIGIN
  "\$ORIGIN/"
  "\$ORIGIN/${LLVM_DEFAULT_TARGET_TRIPLE}/")
set_property(TARGET ${KITRT} APPEND
  PROPERTY BUILD_RPATH "${RPATH_RELATIVE_TO_ORIGIN}")
set_property(TARGET ${KITRT} APPEND
  PROPERTY INSTALL_RPATH "${RPATH_RELATIVE_TO_ORIGIN}")
