//===- kitrt.h - The main interface for Kitsune's runtime ------*- C++ -*--===//
//
// Copyright (c) 2021, Los Alamos National Security, LLC.
// All rights reserved.
//
//  Copyright 2021. Los Alamos National Security, LLC. This software was
//  produced under U.S. Government contract DE-AC52-06NA25396 for Los
//  Alamos National Laboratory (LANL), which is operated by Los Alamos
//  National Security, LLC for the U.S. Department of Energy. The
//  U.S. Government has rights to use, reproduce, and distribute this
//  software.  NEITHER THE GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY,
//  LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY
//  FOR THE USE OF THIS SOFTWARE.  If software is modified to produce
//  derivative works, such modified software should be clearly marked,
//  so as not to confuse it with the version available from LANL.
//
//  Additionally, redistribution and use in source and binary forms,
//  with or without modification, are permitted provided that the
//  following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials provided
//      with the distribution.
//
//    * Neither the name of Los Alamos National Security, LLC, Los
//      Alamos National Laboratory, LANL, the U.S. Government, nor the
//      names of its contributors may be used to endorse or promote
//      products derived from this software without specific prior
//      written permission.
//
//  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
//  SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//
//
// The main interface for Kitsune's runtime. This includes the functions to
// initialize and finalize the runtime, as well as some functions that are
// shared by the various tapir-target-specific runtimes.
//
// The other component runtimes expose other functions, but those are only
// intended to be used after the corresponding runtimes have been initialized.
//
//===----------------------------------------------------------------------===//

#ifndef __KITRT_H__
#define __KITRT_H__

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef struct KitRTInitOptions KitRTInitOptions;

/// Initialize the Kitsune's runtime. This is typically called from a global
/// constructor generated by Kitsune. This function is not thread-safe and
/// should never be called from a multi-threaded context. It is safe to call
/// this function multiple times with a different set of initialization options
/// as long as the sets do not contradict one another.
void __kitrt_initialize(const KitRTInitOptions *initOpts);

/// Finalize Kitsune's runtime. This is typically called from a global
/// destructor generated by Kitsune. This function is not thread-safe and should
/// never be called from a multi-threaded context. It is safe to call this
/// function multiple times.
void __kitrt_finalize(const KitRTInitOptions *initOpts);

/// Check if Kitsune's runtime has been initialized.
bool __kitrt_initialized(void);

/// Allocate \p bytes on the heap. This simply calls malloc to allocate the
/// memory, but keeps track of it within this runtime.
void *__kitrt_default_mem_alloc(uint64_t bytes);

/// Free a pointer previously allocated by \ref __kitrt_default_mem_free.
void __kitrt_default_mem_free(void *ptr);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif // __KITRT_H__
