; Fat binaries generated by multiple tapir targets are allowed in a single
; module, but there can be no more than 1 of each. A corresponding embedded
; bitcode file is not required.
;
; This should contain one fat binary for each tapir target that is known to
; generate embedded bitcode.
;
; RUN: llvm-as %s -o /dev/null

@fb = constant [0 x i8] zeroinitializer #0
@.fb = constant [0 x i8] zeroinitializer #1

attributes #0 = { kit_fb kit_tt(2) }
attributes #1 = { kit_fb kit_tt(4) }
