; Embedded device code globals generated by multiple tapir targets are allowed
; in a single module. A corresponding embedded bitcode file is not required.
;
; NOTE: This should contain one fat binary for each tapir target that is known
; to generate embedded bitcode. When adding a new target that generates a
; device code
;
; RUN: llvm-as %s -o /dev/null 2>&1 \
; RUN:     | FileCheck %s --allow-empty
;
; CHECK-NOT: {{.+}}

@fb = constant [0 x i8] zeroinitializer, !kit.gv.device.code !0
@.fb = constant [0 x i8] zeroinitializer, !kit.gv.device.code !1

!0 = !{i32 2}
!1 = !{i32 4}
