; Embedded bitcode generated by multiple tapir targets are allowed in a single
; module, but there can be no more than 1 of each.
;
; This should contain one fat binary for each tapir target that is known to
; generate embedded bitcode.
;
; RUN: MBC_2=`%kit-enc --tapir=cuda %s \
; RUN:     | grep "c\"BC" \
; RUN:     | sed 's/.kit.emb//g' \
; RUN:     | sed 's/@.bc/@.bc.2/g'`
; RUN:
; RUN: MBC_4=`%kit-enc --tapir=hip %s \
; RUN:     | grep "c\"BC" \
; RUN:     | sed 's/.kit.emb//g' \
; RUN:     | sed 's/@.bc/@.bc.4/g' \
; RUN:     | sed 's/\!0/\!1/g'`
; RUN:
; RUN: printf "%%s\n%%s\n%%s\n%%s\n\n%%s\n%%s" \
; RUN:         "${MBC_2}" \
; RUN:         "${MBC_4}" \
; RUN:         "@fb.2 = constant [0 x i8] zeroinitializer, !kit.gv.device.code !0" \
; RUN:         "@fb.4 = constant [0 x i8] zeroinitializer, !kit.gv.device.code !1" \
; RUN:         "!0 = !{i32 2}" \
; RUN:         "!1 = !{i32 4}" \
; RUN:     | llvm-as -o /dev/null
