// Check that the correct tapir.loop.target metadata is added to the tapir
// loops created by lowering kokkos::parallel_for
//
// -----------------------------------------------------------------------------\
// If the tapir target is not 'none', the tapir loops must have a loop.target
// metadata whose value is the integer representation of the tapir target.
//
// RUN: %kitxx -DUSEF --kokkos --kokkos-no-init %sysroot --tapir=serial -O1 \
// RUN:     -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix SERIAL
//
// SERIAL: !{!"tapir.loop.target", i32 1}
// SERIAL-NOT: "tapir.loop.target"
//
// -----------------------------------------------------------------------------
// If the tapir target is 'none', the loop must not have any loop.target
// metadata.
//
// RUN: %kitxx -DUSEF --kokkos --kokkos-no-init %sysroot --tapir=none -O1 \
// RUN:     -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix NONE
//
// NONE-NOT: "tapir.loop.target"
//
// -----------------------------------------------------------------------------
// If a loop has a tapir target attribute, it must override the value of the
// loop.target metadata must be the value of the attribute. The tapir target
// passed on the command line is ignored, even if the specified tapir target
// is 'none'.
//
// FIXME: The tests below actually trigger an assertion in LoopSpawningTI
// because it does not allow the loop.target metadata value to be different
// from the primary tapir target. This is because multi-target support in the
// middle end is not yet implemented properly.
//
// In these tests, we descend into the middle-end pass pipeline even though what
// we actually want is the IR immediately after it has been generated by clang.
// Since we cannot use -O0 with most tapir targets, the workaround is to print
// the IR before the first module pass in the pipeline. However, this doesn't
// stop us from descending into the pipeline, eventually trigering the
// assertion.
//
// At some point, a frontend option will be provided to emit llvm early and
// terminate at which point, an assertion will not be triggered and the
// `not` in the test below can be removed.
//
// RUN: not %kitxx -DUSEG --kokkos --kokkos-no-init %sysroot --tapir=serial \
// RUN:     -O1 -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix ATTR
//
// RUN: %kitxx -DUSEG --kokkos --kokkos-no-init %sysroot --tapir=none -O1 \
// RUN:     -c -emit-llvm -o /dev/null %s \
// RUN:     -mllvm -print-before=annotation2metadata 2>&1 \
// RUN:     | FileCheck %s -check-prefix ATTR
//
// ATTR: !{!"tapir.loop.target", i32 2}
// ATTR-NOT: "tapir.loop.target"

#include <Kokkos_Core.hpp>

#ifdef USEF
extern "C" void f(int *a, int scale, size_t n) {
  // clang-format off
  Kokkos::parallel_for(n, KOKKOS_LAMBDA(const int i) {
    a[i] *= scale;
  });
  // clang-format on
}
#endif // USEF

#ifdef USEG
extern "C" void g(int *a, int scale, size_t n) {
  // clang-format off
  [[tapir::target("cuda")]]
  Kokkos::parallel_for(n, KOKKOS_LAMBDA(const int i) {
    a[i] *= scale;
  });
  // clang-format on
}
#endif // USEG
