; Embedded bitcode generated by multiple tapir targets are allowed in a single
; module, but there can be no more than 1 of each.
;
; RUN: llvm-as %s -o /dev/null

@fb1 = constant [0 x i8] zeroinitializer, !kitsune.fb !0
@fb2 = constant [0 x i8] zeroinitializer, !kitsune.fb !1
@fb3 = constant [0 x i8] zeroinitializer, !kitsune.fb !2
@0 = constant [0 x i8] zeroinitializer, !kitsune.bc !0
@g1 = constant [0 x i8] zeroinitializer, !kitsune.bc !1
@.g2 = constant [0 x i8] zeroinitializer, !kitsune.bc !2

!0 = !{i8 2}
!1 = !{i8 3}
!2 = !{i8 4}
