; Fat binaries generated by multiple tapir targets are allowed in a single
; module, but there can be no more than 1 of each. A corresponding embedded
; bitcode file is not strictly necessary.
;
; RUN: llvm-as %s -o /dev/null

@0 = constant [0 x i8] zeroinitializer, !kitsune.fb !0
@g1 = constant [0 x i8] zeroinitializer, !kitsune.fb !1
@.g2 = constant [0 x i8] zeroinitializer, !kitsune.fb !2

!0 = !{i8 2}
!1 = !{i8 3}
!2 = !{i8 4}
