//===- fatbin_globals.cpp - Global variables for cuda's fat binaries ------===//
//
//  Copyright (c) 2021, 2023 Los Alamos National Security, LLC.
//  All rights reserved.
//
//  Copyright 2021, 2023. Los Alamos National Security, LLC. This
//   software was produced under U.S. Government contract
//   DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), which
//   is operated by Los Alamos National Security, LLC for the
//   U.S. Department of Energy. The U.S. Government has rights to use,
//   reproduce, and distribute this software.  NEITHER THE GOVERNMENT
//   NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS
//   OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
//   If software is modified to produce derivative works, such modified
//   software should be clearly marked, so as not to confuse it with
//   the version available from LANL.
//
//   Additionally, redistribution and use in source and binary forms,
//   with or without modification, are permitted provided that the
//   following conditions are met:
//
//  Redistributions of source code must retain the above copyright
//  notice, this list of conditions and the following disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials provided
//       with the distribution.
//
//     * Neither the name of Los Alamos National Security, LLC, Los
//       Alamos National Laboratory, LANL, the U.S. Government, nor the
//       names of its contributors may be used to endorse or promote
//       products derived from this software without specific prior
//       written permission.
//
//   THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
//   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
//   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
//   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
//   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//   POSSIBILITY OF SUCH DAMAGE.
//
//===----------------------------------------------------------------------===//
//
// EXPERIMENTAL: This is an experimental implementation where some of the code
// that used to be generated by the compiler is kept here instead. This is in
// support of the attempt at enabling true cross-translation unit support in
// Kitsune. This has been written at a time when the runtime design is in major
// flux, so everything here is basically hacked together and should eventually
// be moved into the new setup.
//
//===----------------------------------------------------------------------===//

#include <kitsune/Config/config.h>

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>

// Register a fat binary. The pointer is to the linked NVIDIA GPU code i.e. the
// address of __nv_fatbin.
extern "C" void *__cudaRegisterFatBinary(void *fatbin);

// Mark the end of the process of registering a fat binary. The argument is the
// handled returned by a call to __cudaRegisterFatBinary.
extern "C" void __cudaRegisterFatBinaryEnd(void *handle);

// Unregister a fat binary. The pointer is the value returned by
// __cudaRegisterFatBinary.
extern "C" void __cudaUnregisterFatBinary(void *handle);

// Register a global variable. The global is not allocated in managed memory.
extern "C" void __cudaRegisterVar(
    void *handle,           /* The value returned by __cudaRegisterFatBinary */
    void *hostAddr,         /* Address of the global on the host */
    const char *hostName,   /* The name of the global on the host */
    const char *deviceName, /* The name of the global on the device */
    int ext,                /* Is this global external. This is always 0 */
    size_t size,            /* The size of the global variable in bytes */
    int isConst,            /* Is this global constant */
    int global /* Per the documentation, this is always 0 */);

// Clean up Kitsune's cuda runtime.
extern "C" void __kitcuda_destroy(void);

namespace {

/// The bundle object that will contain a pointer to the singleton fat binary.
/// This struct is a replicate of that in cuda's header file -
/// fatbinary_section.h.
///
///    struct fatbinC_Wrapper_t {
///      int magic;
///      int version;
///      const unsigned long long *data;
///      void *filename_or_fatbins;
///    };
///
/// * Per the header, the magic number is 0x466243B1
///
/// * FATBINC_VERSION is 1 and FATBINC_LINK_VERSION is 2 (more below)
///
/// * The last struct member varies between versions. In the case of version 1
///   it can be a offline filename and for version 2 it is an array of
///   pre-linked fatbins.
///
struct CudaBundle {
  uint32_t magic;           /// Magic number for this bundle
  uint32_t version;         /// The version of (presumably) the object format
  void *fatbin;             /// Pointer to the raw fatbin data
  void *filename_or_fatbin; ///
};

} // namespace

/// An external reference to the fat binary object. This is passed to Kitsune's
/// kernel launch, and other intrinsics. The actual pointee as well as the
/// symbol itself is generated by the linker. The size of the variable is,
/// obviously, not known until link time.
///
/// This is declared weak because Kitsune's runtime is always linked into
/// applications compiled with Kitsune, even if they do not use the cuda tapir
/// target. In such cases, the linker will not generate this symbol.
[[gnu::section(KITSUNE_CUDA_FB_SECTION), gnu::weak]]
extern std::byte __nv_fatbin[];

/// The singleton bundle object that the cuda runtime and tools expect. This is
/// intentionally visible externally.
[[gnu::section(KITSUNE_CUDA_BUNDLE_SECTION)]]
CudaBundle __kitcuda_bundle;

/// The global variable that contains an opaque pointer to the registered
/// fat binary. This is returned by the call to __cudaRegisterFatBinary. It is
/// eventually passed to __cudaUnregisterFatBinary.
///
/// Eventually, this should become part of the singleton kitcuda runtime object
/// so it needn't be global.
static void *__kitcuda_handle = nullptr;

/// This is called from the ctor's generated by Kitsune.
extern "C" void __kitcuda_register_fatbin(void) {
  if (__kitcuda_handle)
    return;

  // The object version is currently set to 1 because that is what it is set
  // when compiling cuda code with clang. It is not clear when, or if, this will
  // ever change.
  __kitcuda_bundle.magic = 0x466243b1;
  __kitcuda_bundle.version = 1;
  __kitcuda_bundle.fatbin = (void *)&__nv_fatbin;
  __kitcuda_bundle.filename_or_fatbin = nullptr;

  __kitcuda_handle = __cudaRegisterFatBinary(&__kitcuda_bundle);

  // This is only present to allow __cudaUnregisterFatBinary to be called.
  // Eventually, this should be folded into the singleton kitcuda runtime
  // object. In that case, we will be guaranteed that the object's destructor
  // will run, so this will be unnecessary.
  std::atexit([]() { __cudaUnregisterFatBinary(__kitcuda_handle); });
}

/// This is called from the ctor's generated by Kitsune. This has fewer
/// parameters than cuda's register function because we use this in a very
/// limited manner. For instance, we know that the names of the global variables
/// are guaranteed to be identical in the host and device. Other comments are
/// inline within the function.
extern "C" void __kitcuda_register_var(void *var, const char *name,
                                       size_t size) {
  // FIXME?: Why is this always set to zero? The API is asking if this is
  // "external". Is this asking if it has external linkage? Or is it asking
  // if this is externally defined (as in C's extern)? In either case, why
  // are we always passing 0 here? Is this just the "safer" course, or is it
  // that we just haven't yet encountered a situation where this should be
  // non-zero? Or does cuda require this to be zero currently because it is
  // they who have not implemented something?
  int ext = 0;

  // Only non-constant globals need to be registered.
  int constant = 0;

  __cudaRegisterVar(__kitcuda_handle, /* Handle to the registered fat binary */
                    var,              /* The shadow variable in host code */
                    name,             /* The name of the global in the host */
                    name,             /* The name of the global in the device */
                    ext,              /* Is this global external */
                    size,             /* The size, in bytes, of the global */
                    constant,         /* Is the global constant */
                    0 /* Per the documentation, this must always be 0 */);
}

/// This is called from the ctor's generated by Kitsune. It is called after
/// we have finished registering all the global variables and kernel functions.
/// TODO: Check if calling this is strictly necessary.
extern "C" void __kitcuda_register_fatbin_end() {
  __cudaRegisterFatBinaryEnd(__kitcuda_handle);
  __kitcuda_destroy();
}
