//===- PipelineUtils.h - Utilities to populate pass pipelines --*- C++ -*--===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Utilities to construct Kitsune's pass pipelines.
//
//===----------------------------------------------------------------------===//

#include "kitsune/Passes/PipelineUtils.h"
#include "kitsune/Analysis/TapirTargetAnalysis.h"
#include "kitsune/CodeGen/CodeGenFatBinaries.h"
#include "kitsune/CodeGen/LowerKitsuneIntrinsics.h"
#include "kitsune/CodeGen/StripKitsuneAddrSpaces.h"
#include "kitsune/Transforms/CreateEmbBitcode.h"
#include "kitsune/Transforms/EmbLinkLibDeviceBitcode.h"
#include "kitsune/Transforms/EmbOptimize.h"
#include "kitsune/Transforms/EmbPrepare.h"
#include "kitsune/Transforms/EmbResolveLibDeviceCalls.h"
#include "kitsune/Transforms/GenerateCtors.h"
#include "kitsune/Transforms/Prefetching.h"
#include "kitsune/Transforms/RecomputeKernelProperties.h"

using namespace llvm;

bool llvm::useTapirLowering(ThinOrFullLTOPhase phase,
                            const PipelineTuningOptions &pto) {
  if (not pto.TTOpts)
    return false;
  else if (pto.TTOpts->getTTID() == TTID::Nolo)
    return false;
  else if (phase == ThinOrFullLTOPhase::ThinLTOPreLink or
           phase == ThinOrFullLTOPhase::FullLTOPreLink)
    return false;
  else
    return true;
}

ModulePassManager
llvm::populateKitPreTapirPasses(PassBuilder &pb, OptimizationLevel optLevel,
                                ThinOrFullLTOPhase ltoPhase,
                                const PipelineTuningOptions &pto) {
  ModulePassManager mpm;

  // Since the tapir lowering passes and post-tapir Kitsune passes are only
  // truly effective at optimization levels O1 or higher, only run the pre-tapir
  // passes at non-zero optimization levels.
  if (optLevel.getSpeedupLevel() > 0) {
    pb.invokeKitsunePreTapirEarlyEPCallbacks(mpm, optLevel);

    mpm.addPass(CreateEmbBitcodePass());

    pb.invokeKitsunePreTapirLateEPCallbacks(mpm, optLevel);
  }

  return mpm;
}

ModulePassManager
llvm::populateKitPostTapirPasses(PassBuilder &pb, OptimizationLevel optLevel,
                                 ThinOrFullLTOPhase ltoPhase,
                                 const PipelineTuningOptions &pto) {
  ModulePassManager mpm;

  // At optimization level O0, loop spawning will not have been run, so there
  // is no reason to run the passes that operate on the code generated by it.
  if (optLevel.getSpeedupLevel() > 0) {
    pb.invokeKitsunePostTapirEarlyEPCallbacks(mpm, optLevel);

    mpm.addPass(PrefetchingPass());
    mpm.addPass(EmbResolveLibDeviceCallsPass());
    mpm.addPass(EmbPreparePass());
    mpm.addPass(EmbLinkLibDeviceBitcodePass());
    mpm.addPass(EmbOptimizePass());

    pb.invokeKitsunePostTapirLateEPCallbacks(mpm, optLevel);

    mpm.addPass(RecomputeKernelPropertiesPass());
    mpm.addPass(GenerateCtorsPass());

    pb.invokeKitsunePostTapirLastEPCallbacks(mpm, optLevel);
  }

  return mpm;
}

void llvm::populateKitCodeGenPasses(legacy::PassManager &pm,
                                    std::optional<TapirTargetOptions> tto) {
  if (tto) {
    pm.add(createTapirTargetAnalysisWrapperPass(tto));
    pm.add(createLowerKitsuneIntrinsicsLegacyPass());
    pm.add(createStripKitsuneAddrSpacesLegacyPass());
    pm.add(createCodeGenFatBinariesLegacyPass());
  }
}
