# Builds only Kitsune's documentation. This does not build other documentation
# from the broader LLVM project.

name: Kitsune Build Documentation

permissions:
  contents: read

on:
  # This workflow can be run manually. In this case, do so unconditionally.
  workflow_dispatch:

  # On a push, trigger the workflow only if the documentation sources have
  # changed.
  # FIXME: This list is more extensive than it needs to be. The Kitsune
  # documentation is contained within only a few directories, so we should trim
  # this down since we don't really need to build the other documentation.
  push:
    paths:
      - 'clang/docs/**'
      - 'flang/docs/**'
      - 'kitsune/docs/**'
      - 'lld/docs/**'
      - 'llvm/docs/**'
      - '.github/workflows/kitsune-docs.yml'

jobs:
  check-docs-build:
    name: Test Kitsune documentation build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kitsune
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'llvm/docs/requirements-hashed.txt'

      - name: Install Python dependencies
        run: |
          pip install -r llvm/docs/requirements-hashed.txt

      - name: Setup directories
        id: setup-directories
        run: |
          KITSUNE_BUILD_ROOT="$(pwd)/build"
          KITSUNE_BUILD_DIR="${KITSUNE_BUILD_ROOT}/build"
          KITSUNE_DOCS_DIR="${KITSUNE_BUILD_ROOT}/kitsune-docs"
          echo "build-dir=${KITSUNE_BUILD_DIR}" >> "${GITHUB_OUTPUT}"
          echo "docs-dir=${KITSUNE_DOCS_DIR}" >> "${GITHUB_OUTPUT}"
          mkdir -p ${KITSUNE_BUILD_DIR}
          mkdir -p ${KITSUNE_DOCS_DIR}

      - name: Configure
        env:
          KITSUNE_BUILD_DIR: ${{ steps.setup-directories.outputs.build-dir }}
        run: |
          cmake -G Ninja \
                -S llvm \
                -B ${KITSUNE_BUILD_DIR} \
                -DCMAKE_BUILD_TYPE=Release \
                -DKITSUNE_ENABLE_LANGS='c;cxx' \
                -DKITSUNE_ENABLE_TAPIR_TARGETS= \
                -DKITSUNE_BUILD_DOCS=ON

      - name: Build documentation
        env:
          KITSUNE_BUILD_DIR: ${{ steps.setup-directories.outputs.build-dir }}
        run: |
          ninja -C ${KITSUNE_BUILD_DIR} kitsune-docs

        # Copy the documentation to a staging directory so we can generate an
        # artifact from it easily.
      - name: Copy documentation
        env:
          KITSUNE_BUILD_DIR: ${{ steps.setup-directories.outputs.build-dir }}
          KITSUNE_DOCS_DIR: ${{ steps.setup-directories.outputs.docs-dir }}
        run: |
          srcdir="${KITSUNE_BUILD_DIR}/tools/kitsune/docs"
          cp -r "${srcdir}/html" "${KITSUNE_DOCS_DIR}"
          cp -r "${srcdir}/man" "${KITSUNE_DOCS_DIR}"

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: kitsune-docs-current
          path: ${{ steps.setup-directories.outputs.docs-dir }}
          compression-level: 9
          if-no-files-found: error
