# Builds Kitsune on a range of platforms. The specific tapir targets that are
# built depend on what is supported on that platform.

name: Kitsune Test

permissions:
  actions: write
  contents: read

on:
  # This workflow can be run manually. In this case, run it unconditionally.
  workflow_dispatch:

  # When triggering the workflow on a push, only do so if certain directories
  # has changed.
  push:
    paths:
      - 'clang/**'
      - 'flang/**'
      - 'kitsune/**'
      - 'lld/**'
      - 'llvm/**'
      - '.github/workflows/kitsune-test-defaults.yml'

concurrency:
  # Only allow one instance of this workflow on a given branch. This ensures
  # that pushes to a branch will cancel any workflow that was triggered.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # freebsd-x86:
  #   name: FreeBSD (x86)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup variables
  #       id: vars
  #       run: |
  #         build_dir="${{ github.workspace }}/build"
  #         echo "build-dir=${build_dir}/build" >> "${GITHUB_OUTPUT}"
  #         echo "ccache-dir=${build_dir}/ccache" >> "${GITHUB_OUTPUT}"
  #         echo "ccache-key=ccache-freebsd-x86" >> "${GITHUB_OUTPUT}"

  #     - name: Checkout Kitsune
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Restore ccache
  #       id: ccache-restore
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: ${{ steps.vars.outputs.ccache-dir }}
  #         key: ${{ steps.vars.outputs.ccache-key }}

  #     - name: Configure, build and test
  #       uses: vmactions/freebsd-vm@v1
  #       env:
  #         CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
  #       with:
  #         envs: 'CCACHE_DIR'
  #         release: 14.3
  #         sync: sshfs
  #         copyback: false
  #         usesh: true
  #         prepare: |
  #           pkg install -y ccache cmake git libxml2 ninja
  #           echo "runner:    ubuntu-latest (running FreeBSD as a VM)"
  #           echo "system:    $(uname -a)"
  #           echo "cpu:       $(sysctl -n hw.model)"
  #           echo "cores:     $(sysctl -n hw.ncpu)"
  #           echo "memory:    $(sysctl -n hw.memsize) B"
  #         run: |
  #           build_dir=${{ steps.vars.outputs.build-dir }}
  #           mkdir -p ${build_dir}
  #           cmake -G Ninja \
  #                 -B ${build_dir} \
  #                 -S llvm \
  #                 -DCMAKE_BUILD_TYPE=Release \
  #                 -DKITSUNE_ENABLE_EXPERIMENTS=OFF \
  #                 -DKITSUNE_ENABLE_LANGS='c;cxx' \
  #                 -DKITSUNE_ENABLE_TAPIR_TARGETS='opencilk' \
  #                 -DLLVM_CCACHE_BUILD=ON \
  #                 -DLLVM_ENABLE_ASSERTIONS=ON \
  #                 -DLLVM_TARGETS_TO_BUILD=host
  #           # ninja -v -C ${build_dir} check-llvm check-clang check-lld
  #           # ninja -j1 -v -C ${build_dir} check-mlir
  #           # ninja -j1 -v -C ${build_dir} check-flang
  #           ninja -v -C ${build_dir} check-kitsune

  #           ccache_key=${{ steps.vars.outputs.ccache-key }}
  #           ccache_size=$(du -sh "${CCACHE_DIR}" | awk -F' ' '{ print $1; }')
  #           echo "Cache key:                    ${ccache_key}"
  #           echo "Cache size:                   ${ccache_size}"
  #           ccache -s

  #     - name: Delete old ccache
  #       id: ccache-delete
  #       if: steps.ccache-restore.outputs.cache-hit
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         gh cache delete --repo ${{ github.repository }} \
  #             ${{ steps.vars.outputs.ccache-key }}

  #     - name: Save ccache
  #       id: ccache-save
  #       uses: actions/cache/save@v4
  #       if: always()
  #       with:
  #         path: ${{ steps.vars.outputs.ccache-dir }}
  #         key: ${{ steps.vars.outputs.ccache-key }}

  linux-x86:
    name: Linux (x86)
    runs-on: ubuntu-24.04
    steps:
      - name: Setup variables
        id: vars
        run: |
          build_dir="${{ github.workspace }}/build"
          echo "build-dir=${build_dir}/build" >> "${GITHUB_OUTPUT}"
          echo "ccache-dir=${build_dir}/ccache" >> "${GITHUB_OUTPUT}"
          echo "ccache-key=ccache-linux-x86" >> "${GITHUB_OUTPUT}"

      - name: Checkout Kitsune
        id: checkout
        uses: actions/checkout@v4

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

      - name: Setup system
        id: setup-system
        run: |
          sudo apt-get install -y ccache
          echo "runner:    ubuntu-24.04"
          echo "system:    $(uname -a)"
          echo "cpu:       $(cat /proc/cpuinfo | grep "model name" | sed 's/model name\s*:\s*//g' | sort | uniq)"
          echo "cores:     $(cat /proc/cpuinfo | grep -E "^processor" | wc -l)"
          echo "memory:    $(cat /proc/meminfo | grep MemTotal | sed 's/MemTotal:\s*//g')"

      - name: Configure
        id: configure
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          tapir_targets='opencilk'
          build_dir=${{ steps.vars.outputs.build-dir }}
          mkdir -p ${build_dir}
          cmake -G Ninja \
                -B ${build_dir} \
                -S llvm \
                -DCMAKE_BUILD_TYPE=Release \
                -DKITSUNE_ENABLE_EXPERIMENTS=OFF \
                -DKITSUNE_ENABLE_LANGS='c;cxx' \
                -DKITSUNE_ENABLE_TAPIR_TARGETS="${tapir_targets}" \
                -DLLVM_ENABLE_ASSERTIONS=ON \
                -DLLVM_CCACHE_BUILD=ON

      - name: Build and test
        id: test
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          ninja -v -C ${build_dir} check-llvm check-clang check-lld
          # ninja -j1 -v -C ${build_dir} check-mlir
          # ninja -j1 -v -C ${build_dir} check-flang
          ninja -v -C ${build_dir} check-kitsune

      - name: Print ccache stats
        id: ccache-stats
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          ccache_key=${{ steps.vars.outputs.ccache-key }}
          ccache_size=$(du -sh "${CCACHE_DIR}" | awk -F' ' '{ print $1; }')
          echo "Cache key:                    ${ccache_key}"
          echo "Cache size:                   ${ccache_size}"
          ccache -sv

      - name: Delete old ccache
        id: ccache-delete
        if: steps.ccache-restore.outputs.cache-hit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --repo ${{ github.repository }} \
              ${{ steps.vars.outputs.ccache-key }}

      - name: Save ccache
        id: ccache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

  linux-arm:
    name: Linux (arm)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup variables
        id: vars
        run: |
          build_dir="${{ github.workspace }}/build"
          echo "build-dir=${build_dir}/build" >> "${GITHUB_OUTPUT}"
          echo "ccache-dir=${build_dir}/ccache" >> "${GITHUB_OUTPUT}"
          echo "ccache-key=ccache-linux-arm" >> "${GITHUB_OUTPUT}"

      - name: Checkout Kitsune
        id: checkout
        uses: actions/checkout@v4

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

      - name: Setup system
        id: setup-system
        run: |
          sudo apt-get install -y ccache
          echo "runner:    ubuntu-24.04-arm"
          echo "system:    $(uname -a)"
          echo "cpu:       $(cat /proc/cpuinfo | grep "model name" | sed 's/model name\s*:\s*//g' | sort | uniq)"
          echo "cores:     $(cat /proc/cpuinfo | grep -E "^processor" | wc -l)"
          echo "memory:    $(cat /proc/meminfo | grep MemTotal | sed 's/MemTotal:\s*//g')"

      - name: Configure
        id: configure
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          tapir_targets='opencilk'
          build_dir=${{ steps.vars.outputs.build-dir }}
          mkdir -p ${build_dir}
          cmake -G Ninja \
                -B ${build_dir} \
                -S llvm \
                -DCMAKE_BUILD_TYPE=Release \
                -DKITSUNE_ENABLE_EXPERIMENTS=OFF \
                -DKITSUNE_ENABLE_LANGS='c;cxx' \
                -DKITSUNE_ENABLE_TAPIR_TARGETS="${tapir_targets}" \
                -DLLVM_ENABLE_ASSERTIONS=ON \
                -DLLVM_CCACHE_BUILD=ON

      - name: Build and test
        id: test
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          ninja -v -C ${build_dir} check-llvm check-clang check-lld
          # ninja -j1 -v -C ${build_dir} check-mlir
          # ninja -j1 -v -C ${build_dir} check-flang
          ninja -v -C ${build_dir} check-kitsune

      - name: Print ccache stats
        id: ccache-stats
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          ccache_key=${{ steps.vars.outputs.ccache-key }}
          ccache_size=$(du -sh "${CCACHE_DIR}" | awk -F' ' '{ print $1; }')
          echo "Cache key:                    ${ccache_key}"
          echo "Cache size:                   ${ccache_size}"
          ccache -sv

      - name: Delete old ccache
        id: ccache-delete
        if: steps.ccache-restore.outputs.cache-hit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --repo ${{ github.repository }} \
              ${{ steps.vars.outputs.ccache-key }}

      - name: Save ccache
        id: ccache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

  macosx-x86:
    name: MacOSX (x86)
    runs-on: macos-15-intel
    steps:
      - name: Setup variables
        id: vars
        run: |
          build_root="${{ github.workspace }}/build"
          echo "build-dir=${build_root}/build" >> "${GITHUB_OUTPUT}"
          echo "ccache-dir=${build_root}/ccache" >> "${GITHUB_OUTPUT}"
          echo "ccache-key=ccache-macosx-x86" >> "${GITHUB_OUTPUT}"

      - name: Checkout Kitsune
        id: checkout
        uses: actions/checkout@v4

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

      - name: Setup system
        id: setup-system
        run: |
          brew install ccache
          echo "runner:    macos-15-intel"
          echo "system:    $(uname -a)"
          echo "cpu:       $(sysctl -n machdep.cpu.brand_string)"
          echo "cores:     $(sysctl -n hw.ncpu)"
          echo "memory:    $(sysctl -n hw.memsize) B"

      - name: Configure
        id: configure
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        # Pass -DLLVM_DISABLE_ASSEMBLY_FILES=ON to work around test failure on
        # some lld tests:
        #
        #     https://github.com/llvm/llvm-project/issues/81967
        #
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          mkdir -p ${build_dir}
          cmake -G Ninja \
                -B ${build_dir} \
                -S llvm \
                -DCMAKE_BUILD_TYPE=Release \
                -DKITSUNE_ENABLE_EXPERIMENTS=OFF \
                -DKITSUNE_ENABLE_LANGS='c;cxx' \
                -DKITSUNE_ENABLE_TAPIR_TARGETS=opencilk \
                -DKITSUNE_SYSROOT="$(xcrun --show-sdk-path)" \
                -DLLVM_ENABLE_ASSERTIONS=ON \
                -DLLVM_DISABLE_ASSEMBLY_FILES=ON \
                -DLLVM_CCACHE_BUILD=ON

      - name: Build and test
        id: test
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        # FIXME: This currently does not run check-llvm because we get test
        # failures because of a missing -lSystem.  This is likely some issue
        # with the sysroot because it works fine on MacOSX (arm), but debugging
        # it is unlikely to be straightforward. For now, we have to figure out
        # how to get a number of other things built and running so we prioritize
        # getting the runs to pass and use the ccache correctly.
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          ninja -v -C ${build_dir} check-clang check-lld
          # ninja -j1 -v -C ${build_dir} check-mlir
          # ninja -j1 -v -C ${build_dir} check-flang
          ninja -v -C ${build_dir} check-kitsune

      - name: Print ccache stats
        id: ccache-stats
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          ccache_key=${{ steps.vars.outputs.ccache-key }}
          ccache_size=$(du -sh "${CCACHE_DIR}" | awk -F' ' '{ print $1; }')
          echo "Cache key:                    ${ccache_key}"
          echo "Cache size:                   ${ccache_size}"
          ccache -sv

      - name: Delete old ccache
        id: ccache-delete
        if: steps.ccache-restore.outputs.cache-hit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --repo ${{ github.repository }} \
              ${{ steps.vars.outputs.ccache-key }}

      - name: Save ccache
        id: ccache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

  macosx-arm:
    name: MacOSX (arm)
    runs-on: macos-15
    steps:
      - name: Set variables
        id: vars
        run: |
          build_root="${{ github.workspace }}/build"
          echo "build-dir=${build_root}/build" >> "${GITHUB_OUTPUT}"
          echo "ccache-dir=${build_root}/ccache" >> "${GITHUB_OUTPUT}"
          echo "ccache-key=ccache-macosx-arm" >> "${GITHUB_OUTPUT}"

      - name: Checkout Kitsune
        id: checkout
        uses: actions/checkout@v4

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          brew install ccache

      - name: Print system info
        id: system-info
        run: |
          echo "runner:    macos-15"
          echo "system:    $(uname -a)"
          echo "cpu:       $(sysctl -n machdep.cpu.brand_string)"
          echo "cores:     $(sysctl -n hw.ncpu)"
          echo "memory:    $(sysctl -n hw.memsize) B"

      - name: Configure
        id: configure
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        # Pass -DLLVM_DISABLE_ASSEMBLY_FILES=ON to work around test failure on
        # some lld tests:
        #
        #     https://github.com/llvm/llvm-project/issues/81967
        #
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          mkdir -p ${build_dir}
          cmake -G Ninja \
                -B ${build_dir} \
                -S llvm \
                -DCMAKE_BUILD_TYPE=Release \
                -DKITSUNE_ENABLE_EXPERIMENTS=OFF \
                -DKITSUNE_ENABLE_LANGS='c;cxx' \
                -DKITSUNE_ENABLE_TAPIR_TARGETS=opencilk \
                -DKITSUNE_SYSROOT="$(xcrun --show-sdk-path)" \
                -DLLVM_ENABLE_ASSERTIONS=ON \
                -DLLVM_DISABLE_ASSEMBLY_FILES=ON \
                -DLLVM_CCACHE_BUILD=ON

      - name: Build and test
        id: test
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          build_dir=${{ steps.vars.outputs.build-dir }}
          ninja -v -C ${build_dir} check-llvm check-clang check-lld
          # ninja -j1 -v -C ${build_dir} check-mlir
          # ninja -j1 -v -C ${build_dir} check-flang
          ninja -v -C ${build_dir} check-kitsune

      - name: Print ccache stats
        id: ccache-stats
        env:
          CCACHE_DIR: ${{ steps.vars.outputs.ccache-dir }}
        run: |
          ccache_key=${{ steps.vars.outputs.ccache-key }}
          ccache_size=$(du -sh "${CCACHE_DIR}" | awk -F' ' '{ print $1; }')
          echo "Cache key:                    ${ccache_key}"
          echo "Cache size:                   ${ccache_size}"
          ccache -sv

      - name: Delete old ccache
        id: ccache-delete
        if: steps.ccache-restore.outputs.cache-hit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --repo ${{ github.repository }} \
              ${{ steps.vars.outputs.ccache-key }}

      - name: Save ccache
        id: ccache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ steps.vars.outputs.ccache-dir }}
          key: ${{ steps.vars.outputs.ccache-key }}
